boa-dev/boa

- Cargo.lock
- src/bin/bin.rs
- src/lib/syntax/parser.rs
- tests/js/defineVar.js
This urges a discussion:
- What do the `Position` attributes do in the `Expr` structs? They don't have a use currently, but I can't imagine they were thrown in there by Bebbington "just because".
- The solution proposed is probably more of a band-aid than an actual solution. At least until we can figure out what the `start` and `end` (`Position`) attrs are for.
> Remove calls to the mk macro on final returns in parser.rs

- src/lib/syntax/ast/expr.rs
- src/lib/syntax/parser.rs
- tests/js/defineVar.js
- Removed the `Position` (`start` and `end`) attributes from the `Expr` struct as it didn't seem like they were currently necessary.
- Nested blocks (i.e. `if` statements) now get parsed correctly
> Removed Position attributes from the Expr structs

- Cargo.toml
@shekohex at some point im sure thre will be a `boa-core` but this is the best i can do for now.
> make wasm-bindgen an optional feature, but installed by default, fixes #21

- src/lib/js/value.rs
Not sure if I'm missing something, but I noticed some things that didn't make sense to me at a first glance.
Numbers are now `true` when they are not `0` and not `NAN`. I'm not sure if my test-cases for `NAN` and `-0` make sense though.
> Fix some cases in value is_true()

- src/lib/syntax/lexer.rs
Decimal digits are optional in JavaScript, this means the following is valid:
```js
let foo = 10.;
```
Which makes it possible to make the following property accesses (which look quite awkward):
```js
let foostr = 10..toString();
```
I haven't made any tests for the second case as I'm not sure where and how I'd do it. Also, I have almost zero knowledge about lexers/parsers and the like, so if there is a better way to achieve this, let me know :)
(I also don't know if this is spec compliant 🤷‍♂️)
> Allow numbers without decimal digits to be followed by a dot

- src/lib/js/string.rs
Hey there, I saw your JSConf talk about writing a toy JS engine, and I wanted to contribute. I am not very experienced in Rust, so bear with me :)!
------
I implemented [trim](https://tc39.es/ecma262/#sec-trimstring)/[trimEnd](https://tc39.es/ecma262/#sec-string.prototype.trimend)/[trimStart](https://tc39.es/ecma262/#sec-string.prototype.trimstart) to get my toes wet, which are part of #13.
There is a subtle difference in what Rust regards whitespace, and what is considered whitespace in the ECMAScript language. From what I could gather in both languages, it appears that Rust does consider `U+0085` (next line) as whitespace but not `U+FEFF` (zero width non-breaking space), and vice versa for ECMAScript.
I wrote a bit of JavaScript to compare to the v8 impl, all console logs should print …
> Add trim/trimStart/trimEnd to string prototype

- src/lib/js/string.rs
- tests/js/test.js
PR for implementation of some of the prototype methods on the String object:
- [String.prototype.concat ( ...args )](https://tc39.es/ecma262/#sec-string.prototype.slice)
- [String.prototype.endsWith ( searchString [ , endPosition ] )](https://tc39.es/ecma262/#sec-string.prototype.endswith)
- [String.prototype.includes ( searchString [ , position ] )](https://tc39.es/ecma262/#sec-string.prototype.includes)
- [String.prototype.indexOf ( searchString [ , position ] )](https://tc39.es/ecma262/#sec-string.prototype.indexof)
- [String.prototype.lastIndexOf ( searchString [ , position ] )](https://tc39.es/ecma262/#sec-string.prototype.lastindexof)
- [String.prototype.repeat ( count )](https://tc39.es/ecma262/#sec-string.prototype.repeat)
- [String.prototype.slice ( start, end …
> concat(), repeat(),  slice() and all "searchString" based String prototype methods (#13)

- src/bin/bin.rs
Adds argument parsing in the main function of bin.rs which enables specifying a CLI argument as the file to read from: if not argument is specified, it still defaults to tests/js/test.js. #35 
Also adds and prints usage information on incorrect CLI options (and rudimentary error reporting, for the case the file specified doesn't exists, by implict `Result<E, T>` conversion):
```
Usage:
boa [file.js]
Interpret and execute file.js
(if no file given, defaults to tests/js/test.js")
```
Where "boa" is the debug binary created by `cargo`: `target/debug/bin`.
> Add ability to specify a file to read from to the Boa binary (#35)

- src/bin/bin.rs
- src/lib/environment/environment_record_trait.rs
- src/lib/js/array.rs
- src/lib/js/string.rs
- src/lib/syntax/ast/token.rs
This PR implements the basis of the Array object (and its internal representation) similarly to String. This is part of the work towards completion of Array prototype methods #36. 
It uses an internal Object to store the mapping between indices and Values. This may need review (does this still work with Array indexing etc), and otherwise an alternative approach will need to be developed through this PR.
> Implement bare Array object with prototype field

- src/bin/bin.rs
- src/lib/environment/environment_record_trait.rs
- src/lib/js/string.rs
- src/lib/syntax/ast/token.rs
- src/lib/syntax/parser.rs
- tests/js/test.js
Hi!
This is my first contribution to the project, great work! I'm working on doing test for the parser (#40), and I've just created the first changes. Note that I ran `cargo fmt`, so there are minor format changes in other places.
I wanted to create the PR asap, so that you could review it and let me know if I'm following the proper procedure. Real changes are in the `src/lib/syntax/parser.rs` file, where I added a `tests` module. For now, it just contains tests for strings, arrays and declarations.
I found some errors in the parser, though:
- Trailing commas in array assignments make the parser fail ([spec link][array_assignment]).
- `const` declarations work with empty expressions when they shouldnt ([spec_link][empty_const]).
For this last error, I would suggest to change the …
> Parser tests

- src/lib/js/array.rs
This implementation of concat() introduces a helper function for further Array prototype work: it is usually desirable to take all input Arrays and construct and entirely new Array from some combination/altering of their values.
Starts the work of implementing Array.prototype (#36).
Further useful helper functions may convert from Array objects to underlying HashMap or even to Vec directly (by taking all indexed values).
Hopefully this implementation of concat() allows other people to start working on the Array prototype.
Sorry for duplicated commits/messy history, not sure how it got like that.
> Implement Array.prototype: concat(), push(), pop() and join()

- src/lib/js/string.rs
Addition of new String.prototype methods padStart() and padEnd():
https://tc39.es/ecma262/#sec-string.prototype.padend
https://tc39.es/ecma262/#sec-string.prototype.padstart
Completes more of the outstanding tasks from #13.
> Implement String.prototype.{padStart(), padEnd()}

- src/lib/syntax/parser.rs
Hey Jason, just saw your JSConf EU talk, it was great!
I have added support for parsing arrays which include elisions as well as trailing commas. The elision is parsed into an "undefined", but I'm not sure if that's semantically the best thing to do. Perhaps a new expression should be used to indicate that an element has been elided or the metadata should be stored on the array node. Fixes #45.
> Parse array elisions and trailing commas

- Cargo.lock
- Cargo.toml
- README.md
- src/lib/lib.rs
I also updated `Cargo.toml` to adapt it to the common license syntax, and upgraded dependencies. I also had to remove the check for unsafe code, but this might need some extra care (using a feature or something in that sense).
> Added MIT/Unlicense licenses

- src/lib/js/array.rs
The PR implements the following prototype methods for Array objects:
* Array.prototype.reverse ( ) - The elements of the array are rearranged so as to reverse their order. The object is returned as the result of the call.
* Array.prototype.shift ( ) - The first element of the array is removed from the array and returned.
* Array.prototype.unshift ( ...items ) - The arguments are prepended to the start of the array, such that their order within the array is the same as the order in which they appear in the argument list.
More items to tick off the list for #36 Implement Array prototype methods.
This PR may conflict with testing effort being made as part of #63 Unit testing for Array and String.
> Implementation of Array.prototype.{shift(), unshift(), reverse()}

- .gitignore
- src/lib/js/array.rs
- src/lib/js/string.rs
- src/lib/lib.rs
> Unit testing for Array and String

- src/lib/environment/declarative_environment_record.rs
- src/lib/environment/function_environment_record.rs
- src/lib/environment/global_environment_record.rs
- src/lib/environment/lexical_environment.rs
- src/lib/environment/mod.rs
- No functionality gains or bug fixes, just spelling edits
> Spelling edit to file names, functions, and vars: decler* -> declar*

- Cargo.lock
- Cargo.toml
- src/lib/exec.rs
- src/lib/js/mod.rs
- src/lib/js/object.rs
- src/lib/js/object/internal_state.rs
- src/lib/js/regexp.rs
- src/lib/js/value.rs
- src/lib/syntax/ast/constant.rs
- src/lib/syntax/ast/token.rs
- src/lib/syntax/lexer.rs
- src/lib/syntax/parser.rs
This PR aims to add full support for regex literals.
Things still to do:
> Add support for regex literals

- .devcontainer/devcontainer.json
- Cargo.lock
- Cargo.toml
- Dockerfile
- src/bin/shell.rs
I also fixed a few issues with the `devcontainer.json`.
This makes the command line arguments typesafe and also generates a nice help and error message:
```shell
boa 0.3.0
USAGE:
boashell <file>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
ARGS:
<file>    the javascript file to be evaluated
```
> Set proper foundation for boashell

- CHANGELOG.md
- Cargo.toml
- benches/exec.rs
- src/bin/shell.rs
- src/lib/exec.rs
- src/lib/js/array.rs
- src/lib/js/boolean.rs
- src/lib/js/function.rs
- src/lib/js/regexp.rs
- src/lib/js/string.rs
- src/lib/lib.rs
- src/lib/realm.rs
This doesn't fix #119 but it helps with that.
We would still need to add the functionality for boa shell.
This removes InterpreterBuilder and replaces it with `Realm` which is to be inline with the spec
> replacing ExecutorBuilder with Realm

- .gitignore
- CHANGELOG.md
- src/lib/exec.rs
- tests/js/test.js
Fixes #113 
Just like the original issue claimed, this was a two line fix...
... but I didn't stop there! I don't feel comfortable making a change without tests, so I built out the `tests/js/test.js` file to (A) include a test for my fix and (B) include some scaffolding for future JS smoke tests.
If you think this needs some changes, feel free to ping me or make some commits on my branch. I'd also be willing to remove the testing changes. They don't really "fit" in this pull request and I'd understand if you are philosophically opposed to them.
> unassigned var is undefined

- src/lib/exec.rs
- src/lib/js/value.rs
- src/lib/syntax/ast/op.rs
- src/lib/syntax/parser.rs
Implement `**` and `**=`. This fixes #89.
> Implement exponentiation operator

- src/lib/js/regexp.rs
- src/lib/js/string.rs
an implementation of strings.match from issue #114
> implement string.match(regexp)

- src/lib/js/regexp.rs
- src/lib/js/string.rs
Implementation for #115.
Since `matchAll` is [part of RegExp prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/@@matchAll), and `String` objecti is calling it internally, I tried to follow that with my implementation.
There is still some work needed for `matchAll` to be finished. The method should return a JS iterator, but with this implementation it's returning an array. From what I understand, we don't have iterators implemented yet.
> String match all fixes #115

- src/lib/environment/declarative_environment_record.rs
- src/lib/environment/lexical_environment.rs
- src/lib/exec.rs
- src/lib/js/array.rs
- src/lib/js/boolean.rs
- src/lib/js/function.rs
- src/lib/js/regexp.rs
- src/lib/js/string.rs
`const` and `let` are now scoped to the block, while `var` is scoped to
the surronding function (or global).
**NB!** Another bigger change is that all tests have been changed to use `var`
instead of `let` or `const`. This is because every time `forward` is
called with some new Javascript to evaluate, we parse it as a block,
hence variables can only persist across calls to `forward` if they are
defined using `var`. I assume it is intentional to parse each call as a
separate block, because a block is the only `ExprDef` which can contain
multiple statements.
Closes #39
> Implement block scoped variable declarations

- src/lib/builtins/array.rs
> array: implement array.slice

- src/lib/environment/lexical_environment.rs
- src/lib/exec.rs
This PR fixes https://github.com/jasonwilliams/boa/issues/195
Currently the `Interpreter` handles early returns by setting an `is_return` flag when it reaches a return expression. When executing a block expression, the interpreter will skip any sub-expressions if the flag is set, and then unset it.
This bug occurred when the return expression was located inside a block nested in the function's one,
to fix this, this PR unset the `is_return` flag only when leaving the "root block" of a function.
I used the EnvironementType of the block environment to identify such "root blocks".
I hope this helps
> Fix early return

- src/lib/builtins/array.rs
- src/lib/environment/lexical_environment.rs
- src/lib/exec.rs
This PR fixes a bug introduced in #180 . While creating array, we need to set it's prototype as well. 
A helper function `new_array` is added and all usages have been replaced.
> Fixed array creation bug in `Array.slice` implementation

- src/lib/builtins/array.rs
Implementation for https://github.com/jasonwilliams/boa/issues/164.
> Array.prototype.fill method implementation

- README.md
Adjust headings in readme file
> [README.md] Adjust headings importance and update Usage section

- src/lib/builtins/array.rs
I am a rust newbie and my code may not be good. But I will continue to improve this code.
> feat: Implement Array.prototype.toString

- src/lib/syntax/lexer.rs
> [lexer: single-line-comment] Fix bug when single line comment is last line of file 

- src/lib/syntax/lexer.rs
Am not sure about those macros at the top of the file. I just removed ? in three of them that were throwing an error.
> Replace error throwing with panic in "Lexer::next()"

- src/lib/syntax/lexer.rs
Several changes regarding 0_ token.
- preview_next None check before analyzing the x,b,o token (because it can be end of stream)
- Addition of 0X and 0B along with 0x 0b.
- replace of if/else with match
- commenting-out non-strict legacy octal token, which errors out in strict mode
- previous bullet will error out on the last part added which is 11.8.3 clause from spec
> Fix lexing of "0_" token

- src/lib/lib.rs
This removes all of the clippy warnings
> fix clippy, revert to just correctness, perf and style

- src/bin/bin.rs
- src/bin/shell.rs
- src/lib/lib.rs
- src/lib/wasm.rs
Fixes #234. I put the wasm-related stuff in its own module. I also conditionally re-exported the contents of this module, as the `evaluate` function is public and I was unsure if making it private would break semver.
> Fixed compilation without "wasm-bindgen" feature

- src/lib/lib.rs
- src/lib/syntax/lexer.rs
- src/lib/syntax/parser.rs
I went through and fixed some of the immediately obvious panics in the lexer, though more work still needs to be done. I removed all `unwrap` calls and replaced them with `expect`. I also made `parser_expr` return a `Result<Expr, String>` and edited `forward` and `forward_val` accordingly.
> Fixed some panics in the lexer

- src/lib/syntax/lexer.rs
> fix arithmetic operations with no space

- src/lib/syntax/lexer.rs
Fixes scientific notation with floats. Resolves #204
> Fixed parsing of floats with scientific notation

- boa/src/builtins/array.rs
New PR. Array.isArray is useful for test.
> feat: Implement Array.isArray

- boa/src/lib.rs
- boa/src/syntax/lexer.rs
- boa/src/syntax/parser.rs
- boa_cli/src/main.rs
This fixes a bug in comment lexing, where the initial `/` was not being included in the comment token, and the line number and column numbers were wrong. This would break the numbering of a whole file if there was a multiline comment.
Also, I have added the line and column numbers to the parsing errors, and properly printed them in case of failure, instead of panicking with a debug message.
This should make debugging much easier.
> Fixed comments lexing

- boa/src/syntax/parser/mod.rs
- boa/src/syntax/parser/tests.rs
This fixes #251, the parsing of empty returns. I added some tests to make sure it doesn't break again.
> Fixed empty returns

- README.md
- boa/src/realm.rs
- boa_cli/src/main.rs
- docs/debugging.md
I believe this should close #142 and should make some progress towards #74.
If this PR (gets accepted / is satisfactory) I can continue working on other features needed to complete #74.
> Add print & REPL functionality to CLI

- .vscode/launch.json
- .vscode/tasks.json
- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
* Taken from @xSke's older branch
* Also some fixes to the debugger
* Tests added
> Addition of forEach()

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
I implemented the `Array.prototype.filter` method according to the spec. Took the implementation of `map` as a reference, let me know if I missed something.
> Implement Array.prototype.filter method

- boa/src/builtins/math.rs
- boa/src/builtins/math/mod.rs
- boa/src/builtins/math/tests.rs
I implemented some more Math functions which already have an equivelant in the rust standard library. There are still a couple more that have to be implemented, but they require a bit more work as they have some side effects or are not in the rust standard library. Those are out of scope for this PR.
<details> 
<summary>List of Math object functions</summary>
</details>
> Add methods with f64 std equivelant to Math object

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/console.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/environment/declarative_environment_record.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/lib.rs
- boa/src/syntax/ast/constant.rs
- boa/src/syntax/ast/keyword.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/ast/punc.rs
- boa/src/syntax/ast/token.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/parser/mod.rs
- boa_cli/Cargo.toml
This PR is to the `parser` branch, in order to keep developing the new parser in #281 .
I added indentation for the `fmt::Display` implementation in AST nodes, and also improved greatly how the final code looks. It should look pretty close to how a programmer would write it.
I also took the opportunity to fix a bunch of warnings. Some of them were showing in the builds, some of them were silenced. I added some extra lints in order to find them.
There are only a couple of warnings left: the usage of the `dbg!()` macro, that in my personal opinion should be a warning (we should remove the usage of the macro before merging into production) and a couple of unused methods, that should be removed in the case we end up not needing them.
Let me know if you want any change.
> Added indentation and better Display implementation for AST nodes

- boa/Cargo.toml
- boa/src/builtins/array/tests.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/function/tests.rs
- boa/src/builtins/math/tests.rs
- boa/src/builtins/number/tests.rs
- boa/src/builtins/regexp/tests.rs
- boa/src/builtins/string/tests.rs
- boa/src/builtins/symbol/tests.rs
- boa/src/builtins/value/mod.rs
- boa/src/environment/lexical_environment.rs
- boa/src/exec/mod.rs
- boa/src/lib.rs
- boa/src/syntax/ast/constant.rs
- boa/src/syntax/ast/keyword.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/ast/pos.rs
- boa/src/syntax/ast/punc.rs
- boa/src/syntax/ast/token.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/parser/mod.rs
I have ported #261 to the new parser (#281) (this should close #261). And I'm working on fixing the tests that don't pass. I'm getting this error:
```
ParsingError: Unexpected Token 'empty' at line 1, col 13
```
When parsing:
```javascript
var empty = [ ];
var one = ["a"];
var many = ["a", "b", "c"];
var duplicates = ["a", "b", "c", "a", "b"];
```
So, I'll try to fix that variable creation tomorrow if possible. Feel free to add suggestions.
> New parser fixes tests failing against #281

- boa/src/exec/mod.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/parser/mod.rs
Fixed all tests from the new parser #281
```
test result: ok. 127 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```
:tada: :tada: :tada:
> Fixed all tests

- boa/src/syntax/parser/cursor.rs
- boa/src/syntax/parser/mod.rs
This adds a simple cursor structure to the new parser (#281), which enables doing simpler operations, and making it easier to understand.
This also brings token referencing to the parser, to avoid so much cloning. Most of the cloning only happens when we need to return an error, in which case, it doesn't matter if it takes us a bit more. But for the rest, I think this should be faster. This closes #284.
I also took the opportunity to improve a bit further the documentation and the parser errors.
> Added cursor to parser

- boa/benches/parser.rs
- boa/benches/string.rs
- boa/src/lib.rs
- boa/src/syntax/parser/cursor.rs
- boa/src/syntax/parser/mod.rs
- boa/src/syntax/parser/tests.rs
- boa/src/wasm.rs
- boa_cli/src/main.rs
Changed `Cursor` to take in a `&[Token]` and removed unnecessary *cloning* in expression parsing for new parser #281.
> Changed Cursor to take in a &[Token].

- boa/src/lib.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/tests.rs
- boa/src/syntax/parser/mod.rs
I also removed an unused function in the parser and added a test for #294, currently ignored. This now correctly reports the column and line number for that specific issue.
> Fixed positions in regexes and strict operators

- Cargo.lock
- boa/Cargo.toml
- boa/benches/exec.rs
- boa/benches/fib.rs
- boa/benches/parser.rs
- boa/benches/string.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
I have changed the system allocator for Jemallocator as the global allocator for the binary and the benchmarks. Jemalloc makes the binary bigger, but the performance should increase nicely, which is something we probably want in a compiler.
My benchmarks show around 10% improvement or more in some cases.
> Use jemallocator

- CONTRIBUTING.md
- README.md
- docs/debugging.md
I updated the documentation related to how to contribute to the project. I modified the usual `dbg!(&tokens)` and `dbg!(&expr)` to instead use the `-t` and `-a` CLI options, updated some links, and reduced duplication of information. I see a couple of images in the `./docs/img/` folder, but I don't see them referenced anywhere. Are we using them? Maybe they can be removed.
> Updated contribution documentation

- Cargo.lock
- boa/Cargo.toml
- boa/benches/exec.rs
- boa/benches/fib.rs
- boa/benches/parser.rs
- boa/benches/string.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
Builds currently fail on Windows
Reverts jasonwilliams/boa#298
https://github.com/rust-analyzer/rust-analyzer/issues/696
> Revert "Use jemallocator" fixes #309

- boa/src/syntax/parser/tests.rs
Test for constructor precedence in the parser.
It can be quite verbose to read, i'm not sure if there's a better way of testing the AST output
> adding test for #273

- Cargo.toml
This will add build profiles for benchmarks and tests. It will also add a thin optimization layer to development builds, and make sure that benchmarks are run with the same build profiles as the release builds.
> Added more build profiles

- .github/workflows/rust.yml
I added continuous integration for windows.
- Rename `Check` **to** `Check on Linux`
- Added `Check on Windows`
- Rename `Test Suite` **to** `Test Suite on Linux`
- Added `Test Suite on Windows`
I did not add `Rust Fmt on Windows` and `Rust Clippy on Windows`, since there are not os specific.
what do you think? @Razican @jasonwilliams 
Also should I add for benchmark too?
> Added continuous integration for windows

- dev/bench/data.js
This updates old benchmarks so that they show in the same graphs in the benchmarks page. Note that this will show a huge worsening in parsing, since we now benchmark lexing and parsing together (they will work at the same time _soon_).
> Renamed old benchmarks

- Cargo.lock
- boa/Cargo.toml
- boa/benches/exec.rs
- boa/benches/lexer.rs
- boa/benches/parser.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
As per the list of [supported targets][targets] for jemallocator, it seems that only `x86_64-unknown-linux-gnu` is properly supported with all tests passing. So I added a conditional dependency that will only build in those targets and will only use jemallocator then. This fixes #309.
[targets]: https://crates.io/crates/jemallocator#user-content-platform-support
> Added jemallocator only for Linux targets

- .github/workflows/master.yml
This should fix the build in the `master` branch. It will also properly upload a `doc/` folder to the `gh-pages` branch (for now using a `test` branch). This also removes the need to have a `secrets.USERNAME` in the repo.
It seems that the old action was broken, and this should be working better. I had to do a trick not to have a mess in the files in the branch, but I think it should be fine. Let's try it.
> Fixing master build

- Cargo.lock
- Cargo.toml
- boa/Cargo.toml
- boa/src/lib.rs
- boa_cli/Cargo.toml
- boa_wasm/Cargo.toml
- boa_wasm/src/lib.rs
- index.js
- webpack.config.js
> create boa-wasm package

- README.md
This just fixes the link in the README to the development documentation. I also noticed that the development documentation no longer has private items since the last commit, but might have been a spurious error, since it was working just before. Let's see if it stays like this.
> Fixed doc link in README

- Cargo.lock
- boa/Cargo.toml
- boa/src/lib.rs
- boa/src/syntax/ast/constant.rs
- boa/src/syntax/ast/keyword.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/ast/pos.rs
- boa/src/syntax/ast/punc.rs
- boa/src/syntax/ast/token.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
- boa_wasm/Cargo.toml
This simplifies the `boa` crate even further: it removes the `serde-ast` feature, but the `serde` dependency is still optional, and can be activated by activating the `serde` feature (as I did in the CLI binary).
Then I also removed the export of `serde_json`. This is not a good practice, since the crates using `boa` as a library might want to use their own version of `serde_json` or any other serializer for outputing the data.
This makes it mandatory for any user of the library to add a serializer as a dependency, so I added `serde_json` as a dependency to the CLI.
> Removed the `serde-ast` feature and the `serde_json` export

- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/console/tests.rs
- boa/src/builtins/function/tests.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/exec/mod.rs
- boa/src/syntax/ast/token.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/tests.rs
- boa/src/syntax/parser/expression/primary/array_initializer/tests.rs
- boa/src/syntax/parser/expression/primary/mod.rs
- boa/src/syntax/parser/expression/tests.rs
- boa/src/syntax/parser/statement/declaration/tests.rs
- boa/src/syntax/parser/statement/iteration/tests.rs
- boa/src/syntax/parser/tests.rs
This will close #331 and unblock #328
> Fix #331 "We only get `Const::Num`, never `Const::Int`"

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
This is supposed to fix #209.
While trying to fix this bug I encountered another bug were we only get `Const::Num` and never `Const::Int`
This PR is blocked until it is fixed.
I will create another PR addressing that bug.
> fix #209 "Calling Array with one argument"

- .vscode/tasks.json
- boa/benches/exec.rs
- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/console/mod.rs
- boa/src/builtins/error.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/math/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/internal_methods_trait.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/exec/mod.rs
- boa/src/lib.rs
- boa/src/realm.rs
- boa/src/syntax/ast/constant.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/lexer/tests.rs
> Refactor old function with new function object

- boa/benches/exec.rs
- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
> Implement for loop

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/console/mod.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/property.rs
- boa/src/builtins/value/mod.rs
- boa/src/environment/declarative_environment_record.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/environment/object_environment_record.rs
- boa/src/realm.rs
- boa/src/syntax/ast/constant.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/ast/op.rs
- boa_wasm/Cargo.toml
This fixes #356. Note that this requires the git version of `rust-gc` until https://github.com/Manishearth/rust-gc/issues/92 gets done. An upgrade to rust-gc would also include new types implementing `Trace` OOB and a very reduced dependency tree without having to depend on many `syn` and `quote` versions.
> Changed HashMap and HashSet for Fx versions

- boa/src/builtins/function/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/exec/mod.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/parser/expression/assignment/arrow_function.rs
- boa/src/syntax/parser/expression/primary/array_initializer/mod.rs
- boa/src/syntax/parser/expression/primary/array_initializer/tests.rs
- boa/src/syntax/parser/expression/primary/function_expression.rs
- boa/src/syntax/parser/expression/primary/object_initializer/mod.rs
- boa/src/syntax/parser/expression/primary/object_initializer/tests.rs
- boa/src/syntax/parser/expression/primary/tests.rs
- boa/src/syntax/parser/expression/tests.rs
- boa/src/syntax/parser/function/tests.rs
- boa/src/syntax/parser/mod.rs
- boa/src/syntax/parser/statement/block.rs
- boa/src/syntax/parser/statement/break_stm/tests.rs
- boa/src/syntax/parser/statement/continue_stm/tests.rs
- boa/src/syntax/parser/statement/declaration/hoistable.rs
- boa/src/syntax/parser/statement/declaration/lexical.rs
- boa/src/syntax/parser/statement/declaration/tests.rs
- boa/src/syntax/parser/statement/iteration/for_statement.rs
- boa/src/syntax/parser/statement/iteration/tests.rs
- boa/src/syntax/parser/statement/switch/mod.rs
- boa/src/syntax/parser/statement/throw/tests.rs
- boa/src/syntax/parser/statement/variable.rs
- boa/src/syntax/parser/tests.rs
This closes #369 but it's blocked on `rust-gc` releasing a new version, which should happen anytime now, since it has already been tagged.
> Optimised all `Vec<Node>` in `Node` to be `Box<[Node]>`

- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
- boa/src/syntax/ast/node.rs
- boa/src/syntax/parser/expression/primary/function_expression.rs
- boa/src/syntax/parser/expression/primary/object_initializer/mod.rs
- boa/src/syntax/parser/expression/primary/object_initializer/tests.rs
This also adds the `name` property to functions. It fixes #266 and makes progress towards #12.
There is one extra thing that is not solved though:
```javascript
let a = function() {};
a.name;
```
This should show `a`, but this is currently not happening. I guess that the solution is to change the assignment expression to change the `name` of the function.
I duplicated most of the execution code for declarations/expressions, though, this can probably be improved in the future. I used this to set the `name` of the function:
```rust
val.set_field_slice("name", to_value(name.clone()));
```
This is not super [spec](https://tc39.es/ecma262/#sec-setfunctionname) compliant, but do you think it's good for now?
> Implemented function expressions

- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/value/mod.rs
Objects were using boxed hashmaps and RCs, which does not make much sense, since the data in a hashmap is already in the heap, so I just changed that. It should be a small optimization.
> Removed one indirection from objects

- boa/src/exec/tests.rs
- boa/src/syntax/parser/expression/assignment/arrow_function.rs
- boa/src/syntax/parser/expression/assignment/mod.rs
- boa/src/syntax/parser/expression/mod.rs
- boa/src/syntax/parser/expression/primary/function_expression.rs
- boa/src/syntax/parser/expression/primary/mod.rs
- boa/src/syntax/parser/function/mod.rs
- boa/src/syntax/parser/statement/break_stm/mod.rs
- boa/src/syntax/parser/statement/continue_stm/mod.rs
- boa/src/syntax/parser/statement/declaration/hoistable.rs
- boa/src/syntax/parser/statement/declaration/lexical.rs
- boa/src/syntax/parser/statement/declaration/tests.rs
- boa/src/syntax/parser/statement/mod.rs
- boa/src/syntax/parser/statement/try_stm/mod.rs
- boa/src/syntax/parser/statement/variable.rs
This adds `BindingIdentifier` parsing ([spec](https://tc39.es/ecma262/#prod-BindingIdentifier)). This allows creating bindings with `yield` and `await` as identifiers.
I added some tests. Note that this should only be possible in non-strict mode, but we do not currently support strict/non-strict modes. That's something we should probably do in the future.
I was a bit unsure on what did `IdentifierReference` and `LabelIdentifier` productions meant with those `[~Yield]` and `[~Await]`. Do they work the same way as `BindingIdentifier`?
I also improved readability of some tests.
> Added `BindingIdentifier` parsing.

- boa/src/builtins/value/mod.rs
- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
This Pull Request fixes/closes #321 
- Add implementation for unary void operator
- Add implementation for unary delete operator
> Implement unary void, delete operators

- CODE_OF_CONDUCT.md
This PR adds a code of conduct to Boa. I just downloaded the Contributor Covenant 2.0 from https://www.contributor-covenant.org/ and added it to the repo.
There is only one thing that we must change before merging: the contact method that community members should use in case they would like to report a violation to the code. This is usually an email address of the person or group of people that are in charge of moderating the community in case someone violates the COC.
I think this is important enough so that every collaborator should approve the PR before merging it, so please read it and see if there is any improvement to be made, too.
[Rendered](https://github.com/jasonwilliams/boa/blob/coc/CODE_OF_CONDUCT.md)
> Added code of conduct based on Contributor Covenant 2.0

- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request fixes/closes #393.
- make NaN a number
- add test for it
> fix `NaN` is lexed as identifier, not as a number

- .vscode/tasks.json
- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/error.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/environment/declarative_environment_record.rs
- boa/src/environment/environment_record_trait.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/environment/object_environment_record.rs
- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
Fixes https://github.com/jasonwilliams/boa/issues/264
Fixes https://github.com/jasonwilliams/boa/issues/360
> implement "this"

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
This Pull Request fixes/closes #398 .
- Adds the field length with the proper length of the string to the context
- Adds a test for testing the fields is set correctly.
> Fix for 0 length new String

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/bigint/tests.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/number/tests.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/value/conversions.rs
- boa/src/builtins/value/mod.rs
- boa/src/builtins/value/operations.rs
- boa/src/builtins/value/tests.rs
- boa/src/exec/mod.rs
- boa/src/syntax/ast/bigint.rs
- boa/src/syntax/ast/constant.rs
- boa/src/syntax/ast/mod.rs
- boa/src/syntax/ast/token.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/parser/expression/primary/mod.rs
> Feature `BigInt`

- boa/src/builtins/value/mod.rs
- boa/src/builtins/value/operations.rs
- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
- boa/src/syntax/ast/node.rs
Corrected impl of typeof to follow specification by using relevant
AST node directly instead of using UnaryOp
This Pull Request fixes #359.
- Adjusts implementation of TypeOf to use Node::TypeOf instead of Node::UnaryOp
> Corrected impl of typeof

- Cargo.lock
- boa/Cargo.toml
- boa_cli/Cargo.toml
- package.json
- yarn.lock
I upgraded all dependencies both for our wasm demo and for our core in Rust. This (with some potential extra upgrades until the release) should get merged for 0.8.
> Dependency upgrade

- boa/src/syntax/parser/statement/if_stm/mod.rs
- boa/src/syntax/parser/statement/if_stm/tests.rs
- Fixes parsing error caused by if statement without else block preceded by a newline
This example on master will give a parsing error:
```js
if (x) {} // <--- newline here
```
It produces this error:
```
Parsing Error: unexpected token '}' at line 1, col 11
```
> Fixed parsing if statement without else block preceded by a newline

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/exec/declaration/mod.rs
- boa/src/exec/mod.rs
- boa/src/realm.rs
- Removed unnesecary `FunctionKind` and cleanup
- Added `name` property to global objects. example: BigInt.name === "BigInt"
- Added `length` property to global objects. example: Boolean.length === 1
- Made arrow functions only callable.
- Fixes function objects constructability and callability.
Not all function objects are constructable or callable for example:
|        Type        | constructable 				|  callable |
| ------------------ | ---------------------------- |-----------|
| Arrow Functions    |    false  				    |   true    |
| Function Decl/Expr |    true   				    |   true    |
| Classes            |    true       				|   false   |
| Builtins           | false (unless explicit true) |   true    |
More informations see: …
> Fix function object constructable/callable

- boa/src/builtins/json/mod.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/value/mod.rs
Closes #345 
Fixes #403 
Additionally, wrote and ignored some tests that should be addressed once #405 is fixed.
> Json stringify replacer

- .github/workflows/rust.yml
Relates to issue #378.
- Updated codecov action version specified to 1.0.7 (latest version) to try and see if this fixes the problem with tokenless codecov not working.
> Update to use a newer version of codecov github action

- README.md
This adds the CodeCov badge to the README, and fixes the Build Status badge, that was pointing to Travis-CI instead of GitHub actions.
Note: I used https://actions-badge.atrox.dev/ to get a badge for GitHub actions.
> Fixed badges in README

- .github/workflows/pull_request.yml
Our benchmarks action now lives in `boa-dev`, so I updated the GitHub action.
> Our benchmarks action now lives in boa-dev

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
This Pull Request fixes/closes #443
- HasOwnProperty now uses GetOwnProperty instead of GetProperty
> Has own property should call get own property

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/exec/exception.rs
- boa/src/exec/mod.rs
- boa/src/exec/operator/mod.rs
- boa/src/exec/tests.rs
- Added `TypeError` implementation.
- Fixed `RangeError` and `Error` throwing.
- Moved throwing code to `Interpreter`.
- Added `throw_range_error()` and `throw_type_error()` to `Interpreter`.
Now with this PR it should be easier to throw exceptions, for example:
```rust
fn function_that_throws(_: &mut Value, args: &[Value], ctx: &mut Interpreter) -> ResultValue {
if args.is_empty() {
return ctx.throw_range_error("Some message");
}
ctx.throw_type_error("Some other message")
}
```
This is more or less the way `neon` crate does it.
> Added `TypeError` implementation

- boa/benches/README.md
- boa/benches/exec.rs
This Pull Request tries to change the execution benchmarks in order to only benchmark the actual execution. This should give us much more interesting information on the actual execution.
To be determined:
- Should we rename the benchmarks in order to not show a huge drop on execution time in the benchmarks web page?
- Should we maintain old benchmarks of Realm + exec too and just duplicate the benchmarks?
I can also add benchmarks for #427, #429 and #430 if you'd like.
> Execution benchmarks now only take execution into account

- boa/src/syntax/ast/token.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/tests.rs
Very basic template literal implementation, of lexer only.
> [TemplateLiteral] Basic lexer implementation

- boa/src/builtins/json/mod.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/value/conversions.rs
- boa/src/builtins/value/mod.rs
This Pull Request addresses objects created from JSON parse #452.
- Removes `impl From<JSONValue> for Value { ... }` conversion.
- Removes `ValueData::from_json` and `ValueData::to_json`
- Adds `Value::from_json` and `Value::to_json`
- Adds the object prototype to object created from JSON objects in `Value::from_json()`
It does not yet address Booleans, Arrays, Strings, Numbers or Null.
> Add proto object to from json

- boa/src/exec/field/mod.rs
- boa/src/exec/tests.rs
Closes #210 
I've added 4 tests, to test accessing properties on functions and strings with both bracket and dot notation.
> [Property accessor - executor] fix bracket accessing on non-objects types

- boa/src/builtins/array/tests.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/nan/mod.rs
- boa/src/builtins/nan/tests.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/tests.rs
> [NaN] handle NaN token as identifier

- boa/src/builtins/function/mod.rs
- boa/src/environment/function_environment_record.rs
- boa/src/syntax/ast/node/mod.rs
This PR adds some `Copy` implementation to some enumerations that can be stored in the stack by adding an empty trace implementation to them. This could improve execution times a bit.
> Small optimisation in some types that can be `Copy`

- boa/src/builtins/value/tests.rs
- boa/src/exec/declaration/mod.rs
- boa/src/exec/tests.rs
> [FunctionDeclaration - execution] evaluate declaration into undefined not function

- Cargo.lock
- boa/Cargo.toml
- boa/benches/exec.rs
- boa_cli/Cargo.toml
Adding string benchmarks as mentioned in #465.
> Added string benchmarks, and updated dependencies

- boa/benches/exec.rs
> Added `String`, `Boolean` and `Number` object benchmarks

- boa/src/exec/field/mod.rs
This Pull Request fixes/closes #482.
- mod.rs to_object function call error handling to use ? operator
> Added error propagation in Field access

- boa/src/builtins/mod.rs
- Fix the order of builtins (`Object` should be initialized before `Array`)
- Removed `vec![]` from builtins
This unblocks #434
> Fixed global objects initialization order

- boa/src/builtins/array/mod.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
- boa/src/builtins/value/mod.rs
This Pull Request fixes/closes #434
- Adds `propertyIsEnumerable` function to Object Prototype
- Uses `propertyIsEnumerable` to test that values coming out of `JSON.parse(...)` are enumerable
> 434 json parse enumerability

- boa/src/builtins/function/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/exec/tests.rs
This pull request fixes #505 
- Fixed calling a function with less amount of arguments than the function declaration parameters.
This is blocked until #501 lands
> Fixed function call with unspecified arguments

- boa/src/builtins/json/mod.rs
- boa/src/builtins/json/tests.rs
This Pull Request fixes/closes #509
- `JSON.stringify(undefined);` now returns undefined according to [spec](https://tc39.es/ecma262/#sec-json.stringify)
> JSON.stringify(undefined) should return undefined

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
This Pull Request fixes/closes #513.
- Implements Object.is() method per issue request specs (w/o strict ?).
- Adds unit test for example code.
> Implement Object.is() method issue #513

- boa/src/builtins/math/mod.rs
This Pull Request addresses all of the Math methods that simply call the Rust f64 equivalents #514 
- It refactors the following methods to use a `map_or` instead of if statements.
- `Math::abs`
- `Math::acos`
- `Math::acosh`
- `Math::asin`
- `Math::asinh`
- `Math::atan`
- `Math::atanh`
- `Math::cbrt`
- `Math::ceil`
- `Math::cos`
- `Math::cosh`
- `Math::exp`
- `Math::floor`
- `Math::round`
- `Math::sin`
- `Math::sinh`
- `Math::sqrt`
- `Math::tan`
- `Math::tanh`
- `Math::trunc`
> update pass through math methods

- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
This Pull Request fixes/closes #483.
- Changed the `to_object` implementation to throw a `TypeError` when passed an `undefined` or `null` value.
Best,
> TypeError when to_object is passed null or undefined

- boa/src/builtins/math/mod.rs
This Pull Request fixes/closes #514
- Refactors the following methods:
- `Math::atan2`
- `Math::log`
- `Math::log10`
- `Math::log2`
- `Math::min`
- `Math::pow`
- `Math::sign`
> clean up the rest of the math methods

- docs/profiling.md
[summarize](https://github.com/rust-lang/measureme/blob/master/summarize/Readme.md) has now added [support for boa](https://github.com/rust-lang/measureme/pull/116) to start using it.
It's similar to `crox` except instead of Chrome flamegraph its a table of where time is being spent, there is an example in the documentation
I've updated the documentation to show how to use it.
> updating docs to add summarize

- boa/src/builtins/math/mod.rs
- boa/src/builtins/math/tests.rs
This Pull Request fixes/closes #524.
It changes the following (work-in-progress):
> add remaining math methods (#524)

- boa/src/builtins/json/tests.rs
- boa/src/builtins/value/mod.rs
This Pull Request fixes/closes #405
See NOTE 5 in the [spec](https://tc39.es/ecma262/#sec-json.stringify).
- Addresses Symbol handling in `JSON.stringify(...)`
- Converts `Symbol()`s to `null` when in an array.
- Does not add fields whose value is `Symbol()` to objects.
> fix json.stringify symbol handling

- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/number/conversions.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/value/conversions.rs
- boa/src/builtins/value/display.rs
- boa/src/builtins/value/mod.rs
- boa/src/builtins/value/operations.rs
- boa/src/builtins/value/tests.rs
- boa/src/exec/conditional/mod.rs
- boa/src/exec/iteration/mod.rs
- boa/src/exec/mod.rs
- boa/src/exec/operator/mod.rs
- boa/src/exec/tests.rs
**What is the problem with the current implementation of `Value`s operations?**
The problem is that they are not spec compliant for objects, for example `ToNumber` (`to_number`) for objects it is supposed to call `to_primitive` and because it does not the code `new Number(6) + 3` is broken and does not give the expected output `9`. Also because `to_number` is called by `Value`s operators, this means that the `Value` operations can throw exceptions and it requires context and should return a `ResultValue`.
- Removed `Value::is_true()` (this is a duplicate of `to_boolean`)
- Added `to_int32`, `to_uint32` and `to_length` to `Interpreter`
- Made `to_integer` spec compliant
- Made `Value` operators => functions (these functions take in an `Interpreter`, and can throw …
> Fix all `Value` operations and add unsigned shift right

- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/mod.rs
- boa/src/exec/exception.rs
- Implement `SyntaxError` object
- Add `.construct_syntax_error()` and `.throw_syntax_error()`
- Made error objects construction use `to_string()` (spec compliant and some cleanup)
- Fix missing `name` field in `prototype` of error objects
> Feature `SyntaxError`

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- Uncomented one of the `concat` test case (the other one is fixed by #520)
- Added a test case for a generic `concat` method (as described in spec) 
- Removed deprecated comment.
> Cleanup and added test for `String.prototype.concat`

- boa/src/exec/call/mod.rs
- boa/src/exec/mod.rs
- boa/src/exec/new/mod.rs
Minor refactor. Also added BoaProfiled to `impl Executable for New`
> Refactor exec/expression into exec/call and exec/new

- boa/src/builtins/math/mod.rs
- boa/src/builtins/math/tests.rs
- boa/src/builtins/value/conversions.rs
- Did some cleaning of the `Math` methods
- Made `Math` methods call `Interpreter::to_number()` and `Interpreter::to_uint32()` 
- Fix bugs where some methods were panicking when no argument was supplied.
- Added `From<u32>` for `Value`
Slowly deprecating the `Value`s `to_` methods, Removed `Math`s methods dependency on `Value::to_*` methods
> Made all `Math` methods spec compliant

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/console/mod.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/number/tests.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/builtins/symbol/tests.rs
> Merged `create` into `init` for builtins

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
Implements Object.create builtin method
> [builtins - object] Object.create

- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR changes the description of the feature request and custom issue templates.
It should avoid issues like #552, where a new ECMAScript feature is requested, but we have no links to the spec or no description of the feature, with no code example that would be affected.
> Improved the description of the issue templates

- Cargo.lock
- boa/benches/parser.rs
- boa/src/builtins/math/tests.rs
As suggested in https://github.com/boa-dev/boa/pull/486#issuecomment-655682389, this adds a new benchmark to check parsing of code with multiple goal symbol switching.
> Added benchmark for goal symbol switching

- boa/Cargo.toml
- boa/benches/exec.rs
- boa/benches/full.rs
This adds benchmarks for full program execution.
Sometimes we have benchmarks that tell us things like "the parser is now 50% slower", but what does that mean for the whole program execution? Maybe it's just a 1% speed reduction.
Also, we have no benchmarks to check improvements if for example, we create the realm in a new thread in parallel to lexing + parsing. This should reduce at least a bit the full program execution time, but there is no way to measure it.
With this PR, all execution benchmarks get duplicated by using our `exec()` function, that creates a realm, lexes and parses and finally executes everything. This should give us insights on how each change affects to a full workflow.
I also took the opportunity to remove some non-needed black boxes from old benchmarks. They were …
> Added benchmarks for full program execution

- boa/src/builtins/bigint/tests.rs
- boa/src/builtins/object/tests.rs
- boa/src/exec/operator/tests.rs
- boa/src/exec/tests.rs
This Pull Request ensures tests that catch errors are testing the error type as well as just the message, as mentioned in [this PR](https://github.com/boa-dev/boa/pull/561#issuecomment-657228578).
> Ensure tests test error type

- boa/src/builtins/number/mod.rs
- boa/src/builtins/number/tests.rs
This Pull Request adds the missing Number and Global methods:
- isFinite()
- isNaN()
- Number.isFinite()
- Number.isInteger()
- Number.isNaN()
- Number.isSafeInteger()
> Add missing Number methods.

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
I implemented `Array.prototype.reduce` according to the [spec](https://tc39.es/ecma262/#sec-array.prototype.reduce). Let me know if I missed anything as this is my first time contributing.
> Implement Array.prototype.reduce

- boa/src/exec/call/mod.rs
- boa/src/exec/field/mod.rs
- tester/src/main.rs
Fixed the stack overflow bug :D
This is the example code that caused it:
```js
let x;
x.y(); // this will overflow
```
- Removed check for `Symbol`  when it should only check for `Object` in GetField/Const , this was from when we did not have symbol primitives (pre-#419 ) (this is another bug).
- Removed the ignore cases for these tests since the either pass or fail, not overflow.
- Added some tests to ignore `Array.prototype.indexOf` they don't stop the tester but they "freeze" it (iterate from 0 to a very large number like `u32::MAX`).
Now it reaches a **lot** more, but still gets stuck by `indexOf` in some tests.
> Fixed stack overflow bug

- boa_cli/Cargo.toml
This PR make boa binary the default when calling `cargo run`, so we don't have to do `cargo run --bin boa`
> Made `boa_cli` bin default binary when calling `cargo run`

- boa/src/builtins/string/mod.rs
- test_ignore.txt
This fixes the buffer overflow caused by replace when the second argument function throws.
- Removed test that overflows from ignore list.
> Fixed `String.prototype.replace` stack overflow when function throws

- Cargo.lock
- boa/src/builtins/number/mod.rs
- boa/src/builtins/number/tests.rs
- boa/src/builtins/value/display.rs
This Pull Request is related to #507 .
- Made number object printing `Number { numberValue }`.
- `-0` is now `-0` instead of positive `0` this is done by V8 and SpiderMonkey, even though it does against the tostring spec, in REPL we are not bound by the ECMAScript spec so we can do this, it makes it easier to know if the number is a `-0` or a positive `0`.
- Made `Number.prototype.toString()` spec compliant
- Enabled `Number.prototype.toString()` tests
```js
new Number(1000); // -> Number { 1000 }
```
> Spec Compliant `Number.prototype.toString()`, better `Number` object formating and `-0`

- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/object/internal_methods.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/string/tests.rs
- boa/src/builtins/value/conversions.rs
- boa/src/builtins/value/display.rs
- boa/src/builtins/value/mod.rs
- boa/src/exec/mod.rs
- boa/src/exec/new/mod.rs
- boa/src/exec/tests.rs
- boa/src/syntax/parser/tests.rs
This Pull Request fixes/closes #578 .
> Extracted `__proto__` from internal slots

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- Fixed `String.prototype.trim()`
- Fixed `String.prototype.trimStart()`
- Fixed `String.prototype.trimEnd()`
- Add tests
> Fix string prototype `trim` methods

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- Make `String.prototype.repeat()` ECMAScript specification compliant
- Made repeat use `Interpreter`s `to_string`
- Added a string limit as V8 and spidermonkey does (`2 ^ 32 - 1`).
- Added tests.
> Make `String.prototype.repeat()` ECMAScript specification compliant

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
I implemented `Array.prototype.reduceRight` pretty similarly to reduce, with a few small changes mostly related to `usize` constraints.
> Implement Array.prototype.reduceRight

- Cargo.lock
- boa/src/builtins/value/display.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
This Pull Request fixes/closes #507 .
- Better error formatting `errorName: message`, example `TypeError: 'this' is not an object`
- Made readline (`"> "`) bold cyan color
- uncaught errors: `Uncaught: errorMessage` in red in cli
Example:
> Better error formatting and cli color

- Cargo.lock
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
This Pull Request fixes/closes #341 .
- Made readline `"> "` to `">> "`, looks much nicer ;) 
- Added color to keywords (bold yellow) 
- Added color to reserved words (`true`, `false`, `Infinity`) purple color
- Added color to `undefined` gray
- Added matching bracket validation (the cli will wait untill closing `}`, `)`, `]`) so we can do something like:
```js
function x() {
let y = 3;
}
```
Example: some dummy code:
The line 5 `undefined` is not colored because it is not part of the line that is being read, its output from `forward_val`
BTW: we can change the colors at any time :)
> Added keyword and operator colors and matching bracket validator to cli

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/console/mod.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/global_this/mod.rs
- boa/src/builtins/infinity/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/math/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/nan/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/builtins/undefined/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/exec/mod.rs
- boa/src/realm.rs
This Pull Request closes #585.
- Moves create_intrinsics from Realm to Interpreter
- Changes the signature of the `init` function from `pub(crate) fn init(global: &Value) -> (&str, Value)` to `pub(crate) fn init(interpreter: &mut Interpreter) -> (&'static str, Value)`, allowing the init functions to reference the interpreter
- Add the Well-Known Symbols to the Symbol object
> Implement Well-Known Symbols

- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/regexp/tests.rs
- boa/src/builtins/string/mod.rs
- Removed Dependency of Internal State
- Removed Dependency of Internal slots
- Merged create into init (like all the other objects)
- Specialized `RegExp` object
- Removed wrong methods that should be getters (but we don't support getter so I disabled them for now)
BTW: This is not to make the methods spec compliant, this PR only focus on removing the dependency (I tried not to change the old behaviour). Making the methods spec compliant should be done in a separate PR.
> `RegExp` specialization

- boa_cli/src/helper.rs
- boa_cli/src/main.rs
- Added syntax highlighting for strings (`""`, `''`)
- Split rustyline helper to a separate file (`helper.rs`)
- Made colors for highlighting constants.
> Added syntax highlighting for strings

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- Made `String.prototype.indexOf` spec compliant.
- Added tests
> Made `String.prototype.indexOf` spec compliant.

- boa/src/exec/operator/mod.rs
- boa/src/exec/tests.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/ast/punctuator.rs
- boa/src/syntax/parser/expression/assignment/mod.rs
This Pull Request fixes/closes #569 .
- Adds the comma operator
- Changes assignment operator parsing so that the comma operator is not parsed as part of the assignment (explained below)
- Adds tests
Examples:
```js
var a, b;
b = 10;
a = (b++, b);
// a is now 11, b is now 11
```
```js
var a, b;
b = 10;
a = (b += 5, b - 1);
// a is now 14, b is now 15
```
```js
var a, b;
b = 10;
a = (b += 5, b *= 2, b - 1);
// a is now 29, b is now 30
```
The reason why assignment operator parsing is changed is because otherwise, for cases like the second example, the parser continues to parse the tokens after the comma operator as part of the assignment. For the second example, this would cause the `b` to be assigned the value of `5, b - 1` (which is `b - 1`). So I made a minor …
> Implement the comma operator

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- Fixed `String.prototype.indexOf()` bug, when the search string is empty
- Added test.
> Fixed `String.prototype.indexOf()` bug, when the search string is empty

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- Made `String.prototype.lastIndexOf()` spec complaint
- Added tests
> Made `String.prototype.lastIndexOf()` spec compliant

- boa/src/builtins/function/mod.rs
- boa/src/builtins/object/internal_methods.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/value/mod.rs
> Removed internal_slots from object

- boa/src/builtins/value/mod.rs
- boa/src/builtins/value/tests.rs
- Removed `Value::as_num_to_power()` this is not spec complaint and `Value::pow()` should be used instead.
- Added pow operator tests
> Remove `Value::as_num_to_power()`

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/console/mod.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/math/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/symbol/mod.rs
This Pull Request fixes/closes #531 
- make_builtin_fn now takes &Interpreter as an argument.
- Call sites are updated according to the new function signature of make_builtin_fn
> Set __proto__ of function instances

- boa/src/builtins/number/mod.rs
- boa/src/builtins/property/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/builtins/value/operations.rs
- boa/src/builtins/value/tests.rs
- boa/src/builtins/value/type.rs
- boa/src/exec/operator/mod.rs
This Pull Request fixes/closes #615 .
- Adds a spec complaint `Value::abstract_relation()` with `TriState` for the three possible states (true, false, and undefined)
- Added `Value::lt()` 
- Added `Value::le()`
- Added `Value::gt()`
- Added `Value::ge()`
- Added documentation
- Removed `Type::Date` for value types, there is no type `"date"`.
- Added tests for relational operators
- Added fast paths for common operations
> Fix abstract relational comparison (`<`, `>`, `<=` and `=>`)

- boa/src/builtins/object/gcobject.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/value/tests.rs
This Pull Request fixes/closes #608.
- Adds RecursionLimiter. This tracks the `GcObject` pointers that have been visited during a `Debug::fmt` call.
- Adds a test for the stack overflow.
The same object cannot appear twice in the output, by design. JS object graphs tend the be huge, and comprehending a massive data dump is nearly impossible. If the same object appears twice, even if not recursive, it is always elided. The following graph:
```js
let a = {};
a.c = a;
let b = {
d: a, e: a
};
debug(b);
```
Would print:
```js
{
d: {
c: ... // Recursion protected
},
e: ... // Will never appear twice
}
```
> Fix Stack Overflow for `Debug::fmt`

- boa/src/builtins/math/mod.rs
- boa/src/builtins/value/mod.rs
- boa/src/builtins/value/tests.rs
- boa/src/exec/tests.rs
This PR is related to https://github.com/boa-dev/boa/issues/445#issuecomment-674524820
- Renamed `Value::to_uint32()` **=>** `Value::to_u32()`
- Renamed `Value::to_int32()` **=>** `Value::to_i32()`
> Rename `Value::to_*int32` to `Value::to_*32`

- boa/src/exec/block/mod.rs
- boa/src/exec/statement_list.rs
- boa/src/exec/tests.rs
This PR changes the default result of `statement_list` from `null` to `undefined`.
> Change default return type from null to undefined

- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
This Pull Request fixes #532, #533, & #641.
> Fix 532, 533, 641

- boa/src/builtins/array/mod.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/object/internal_methods.rs
- boa/src/builtins/object/iter.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/property/mod.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/builtins/symbol/tests.rs
- boa/src/builtins/value/conversions.rs
- boa/src/builtins/value/display.rs
- boa/src/builtins/value/mod.rs
- boa/src/environment/global_environment_record.rs
- boa/src/exec/call/mod.rs
- boa/src/exec/field/mod.rs
- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
- Added `iter` method to object to iterate over all (indexed, string and symbol) keys (`PropertyKey`) and value (`Property`)
- Added `keys` method to object to iterate over all (indexed, string and symbol) keys (`PropertyKey`)
- Added `values` method to object to iterate through all the (indexed, string and symbol) values (`Property`).
- Added `symbol_properties` method to object to iterate over symbol keys (`RcSymbol`) and value (`Property`)
- Added `symbol_property_keys` method to object to iterate over symbol keys (`RcSymbol`)
- Added `symbol_property_values` method to object to iterate over symbol values (`Property`)
- Added `index_properties` method to object to iterate over index keys (`u32`) and value (`Property`)
- Added `index_property_keys` method to …
> Index `PropertyKey`, `Object` iterators and symbol support

- boa/src/exec/mod.rs
- boa/src/exec/tests.rs
This Pull Request fixes/closes #644 and #631.
- Adds support for `undefined` expr
- Makes the `Node` match exhaustive (I have `ConditionalOp` and `Continue` as a local WIP, but they don't really belong in this PR)
> Fix undefined constant expression evaluation

- boa/src/exec/tests.rs
The last few PR's introduced a failing test + a rust fmt issue.
Note the 'as u128' is because usize cannot fit the value 100000000000 in all environments.
This should fix both but I'm a little unsure about the test so it would be great if you could check it @HalidOdat ?
> Test + fmt fix

- boa/src/builtins/object/gcobject.rs
- boa/src/exec/new/mod.rs
- It does not make sense for `GcObject::contruct()` to take `'this'` since it constructs it.
> Make `GcObject::contruct` not take `'this'`

- boa/src/exec/block/mod.rs
- boa/src/exec/break_node/mod.rs
- boa/src/exec/conditional/mod.rs
- boa/src/exec/iteration/mod.rs
- boa/src/exec/iteration/tests.rs
- boa/src/exec/mod.rs
- boa/src/exec/statement_list.rs
- boa/src/exec/switch/mod.rs
- boa/src/exec/tests.rs
- Add support for executing ConditionalOp
- Add support for executing continue statements (it is missing label support like break)
- Remove the "match anything" branches where they weren't necessary.
> Add missing ops to exec module

- boa/src/builtins/object/gcobject.rs
- Implement `std::error::Error` for `BorrowError` and `BorrowMutErrror`
> Implement `std::error::Error` for `GcObject` borrow errors

- boa/src/builtins/object/gcobject.rs
- boa/src/builtins/object/mod.rs
- Added documentation to `GcObject` methods
- Added type aliases `Ref` and `RefMut` to abstract the gc.
> Add documentation to `GcObject` methods

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/math/tests.rs
Added approx_eq! macro for expm1 tests due to floating point arithmetic
inaccuracies, using default ULP & epsilon values. approx_eq! macro does
not work for NaN values, however, for tests this should be okay anyway!
Solves #664.
This Pull Request fixes/closes #664.
- `builtins::math::tests::expm1` strict equals assertion to approx_eq assertion
> Added approx_eq! macro for expm1 tests.

- boa/examples/classes.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/object/internal_methods.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/property/attribute/mod.rs
- boa/src/builtins/property/mod.rs
- boa/src/exec/mod.rs
- boa/src/lib.rs
This is related to #445 and #446 
- Added `NativeObject` trait
- If an type implements `Debug`, `Any` + `Trace` it automatically is an `NativeObject`
- It calls `Trace` trait so this is not unsound
- Removed `internal state`
- Added example
- Added `Class` for native class creation. see example in `boa/examples`.
> Feature native class objects (`NativeObject` and `Class` traits)

- boa/src/builtins/function/mod.rs
- boa/src/builtins/function/tests.rs
- boa/src/builtins/object/gcobject.rs
- boa/src/exec/mod.rs
- boa/src/syntax/ast/node/mod.rs
- boa/src/syntax/ast/node/statement_list.rs
Fixes #663 
This commit fixes the panic when a function mutates itself. The issue happens since we borrow the object and when we call the statementList of the object we borrow_mut the object again to mutate it.
- This adds a RcStatementList to cheaply clone StatementList
- It calls the run on the body of the function after dropping the first borrow by returning only the body after setting up the function local env
Thank you @HalidOdat for their help 😃
> Fix panic when calling function that mutates itself

- boa/src/builtins/object/gcobject.rs
- Added `#[track_caller]` to `GcObject` methods that panic. This should make finding borrow error much easier.
> Add `#[track_caller]` to `GcObject` methods that can panic

- .github/workflows/test262.yml
- .github/workflows/webassembly.yml
- .gitignore
- .gitmodules
- .prettierignore
- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- boa/Cargo.toml
- boa/src/builtins/array/mod.rs
- boa/src/builtins/math/tests.rs
- boa/src/exec/tests.rs
- boa/src/lib.rs
- boa/src/syntax/ast/position.rs
- boa/src/syntax/lexer/tests.rs
- boa/src/syntax/parser/cursor/buffered_lexer/tests.rs
- boa/src/syntax/parser/tests.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
- boa_wasm/src/lib.rs
- test_ignore.txt
- tester/Cargo.toml
- tester/src/exec.rs
- tester/src/main.rs
- tester/src/read.rs
- tester/src/results.rs
This Pull Request fixes/closes #12.
- It adds a new crate to the workspace, the `tester` crate, in charge of running the test suite.
- It adds a submodule to the project, `./test262`, which contains the [test262][test262] repo.
- Modifies `forward_val()` and `parse_expr()` in order to properly throw a `SyntaxError`, which closes #539.
This is still early work in progress, and it's blocked waiting for #559 to land, and probably other things we didn't notice. I wanted to show you the design, though, to see if you like it. Note that it's currently everything in one file, so this is something we need to put in multiple modules.
This branch is based in the `new_lexer` branch. And the current main blocker is the fact that line terminators are not skipped by default, as …
> Add ECMAScript test suite (test262)

- .github/dependabot.yml
Should stop webassembly CI from failing.
This Pull Request fixes/closes CI failing in latest push
> Formats dependabot.yml with Prettier

- .github/dependabot.yml
Added `boa_tester` to `dependabot.yml` so dependabot can monitor its dependencies.
> Dependabot for `boa_tester`

- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/context.rs
- boa/src/exec/tests.rs
- boa/src/object/mod.rs
- boa/src/value/display.rs
- boa/src/value/mod.rs
This Pull Request fixes/closes #607.
- Rename `Object::prototype()` to `Object::prototype_instance()`
- Rename `Object::set_prototype()` to `Object::set_prototype_instance()`
> Feat: Rename Object::prototype() and Object::set_prototype()

- boa/examples/classes.rs
- boa/src/class.rs
- boa/src/gc.rs
- boa/src/lib.rs
- Put the gc stuff in the `gc` module. This cleans the root imports and adds some other gc stuff in the `gc` module
Instead of this
```rust
boa::{Value, Result, Trace, Finalize};
```
we can do this:
```rust
boa::{
gc::{Trace, Finalize},
Value, Result,
};
```
> Feature `gc` module

- .github/workflows/test262.yml
Unsure as to whether this should be committed or not, but should fix
failing CI
- `test262.yml`'s commit section to add test262 as a tracked file
> Fix CI Commit failure

- Cargo.lock
- boa/Cargo.toml
This should fix the benchmarks.
> Revert criterion version to `=0.3.2`

- boa/src/value/mod.rs
This Pull Request fixes/closes #690.
- preserve order of array items on Value::to_json
> fix Value::to_json order of items in array

- boa/src/builtins/symbol/mod.rs
- boa/src/context.rs
https://github.com/boa-dev/boa/pull/704#discussion_r490840748
- Add `Context::well_known_symbols()` method.
- Add `WellKnownSymbols` struct
- Add getters for the symbols to `WellKnownSymbols` struct
With this PR we can now do:
```rust
let mut context = Context::new();
let iterator = context.well_known_symbols().iterator_symbol();
```
instead of:
```rust
let mut context = Context::new();
let iterator = context.global_object().get_field("Symbol").get_field("iterator").as_symbol().unwrap();
```
Also there is a problem with this ^, what if we override `Symbol` object like:
```js
globalThis.Symbol = 10;
```
Now the above code will panic, we should have a way to access the well known symbols without being tied to the global bindings.
What do you think? @joshwd36
> Cache well known symbols

- boa/src/builtins/function/tests.rs
- boa/src/object/gcobject.rs
> Fix panic when a self mutating function is constructing an object

- boa/src/exec/operator/mod.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/ast/punctuator.rs
- boa/src/syntax/parser/expression/tests.rs
This Pull Request fixes #621 
- Adds support for unsigned right shift assignment operator (>>>=)
- Adds a test for the operator
> Add support for >>>=

- boa/src/builtins/array/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/exec/call/mod.rs
- boa/src/exec/field/mod.rs
- boa/src/object/mod.rs
- boa/src/value/mod.rs
This Pull Request starts the work on #577.
- `Value::to_object` now returns `Result<GcObject>` rather than `Result<Value>`
- Move `Value::new_object_from_prototype` to `Object::new_object_from_prototype`
- Minor changes in other files to accomodate the new API
I assume those minor changes will be cleaned up once the separation of the `Object` and `Value` API is complete.
> Refactor: Value::to_object to return GcObject

- boa/src/value/operations.rs
Add a fast path for addition of 2 values of kind `String` which doesn't require `Value::to_string` to be invoked on one of them.
Discussed on Discord with @HalidOdat who gave me the go-ahead
> Add fast path for string concatenation

- boa/src/exec/tests.rs
- boa/src/value/mod.rs
- Set a length on new String objects
- Add a test
This Pull Request fixes/closes #720.
> Fix hanging test262 bug by setting the length on String objects

- Cargo.lock
- boa/Cargo.toml
was blocked due to incompatibilities with `critcmp`, however,
`critcmp` has released v0.1.4 and so `critcmp` is no longer functional
with older versions of criterion. This may require criterion compare
action modification
> chore(boa): update criterion from 0.3.2 to 0.3.3

- .github/workflows/test262.yml
It seems that the previous fix was not complete, since we were trying to push changes into the `master` branch instead of the `gh-pages` branch. This should fix that.
> New fix attempt

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
This Pull Request fixes/closes #729.
- `Object::to_string`returns a `Value::String` respecting the spec: https://tc39.es/ecma262/#sec-object.prototype.tostring
> Fix output of Object.toString()

- .github/workflows/rust.yml
adds macos checks and tests to pull request ci
- automated testing and checks to include MacOS using GitHub Actions
> Add MacOS check and test to CI

- boa/src/builtins/string/mod.rs
- boa/src/exec/statement_list.rs
both set of comments aren't needed.
We won't have labels at StatementList level so they can be ignored
> remove deprecated comments

- .github/codecov.yml
- .github/workflows/rust.yml
- Disable codecov annotations in PR
- Ignore tests when calculating coverage
> Ignore tests from codecov count and disable annotations

- .github/workflows/master.yml
It seems that some benchmarks are not showing properly in the graphs. This might be because we are not using the upstream version of the GitHub action, which includes some fixes. This could potentially fix that, and if it does, I can retroactivelly fix the benchmarks, since they need a re-adjustment anyways.
> Using the upstream version of the benchmark action

- .github/workflows/master.yml
Reverts boa-dev/boa#768. Until https://github.com/rhysd/github-action-benchmark/pull/48 gets merged, let's revert this. I tried to generate a release of the action myself, but I was unable to do it.
> Revert "Using the upstream version of the benchmark action"

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
This Pull Request fixes/closes #755.
- Updating `startsWith`, `endsWith`, `includes` to throw `TypeError` if regex is passed in.
- Adding tests.
> Throw TypeError if regexp is passed to startsWith, endsWith, includes

- boa_tester/src/main.rs
This fixes a duplicate attribute name in the generated results for test262 tests.
> Fixing a duplicated attribute in test262 results

- boa/src/builtins/json/mod.rs
- boa/src/builtins/json/tests.rs
This Pull Request closes #784.
Instead of panicking when an argument is not provided to `JSON.parse()`, a syntax error is raised like other JavaScript implementations.
> Fix zero argument panic in JSON.parse()

- boa/src/builtins/function/mod.rs
- boa/src/builtins/function/tests.rs
- boa/src/object/mod.rs
The `Function.prototype` is itself a function that has `__proto__ == Object.prototype`. I Know this is very weird
- Make `Function.prototype` a function that return `undefined`
- Add tests
Here is the spec:
> Make `Function.prototype` a function

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
- boa/src/object/internal_methods.rs
This Pull Request fixes/closes #552.
- It adds define_properties to both internal and external Object struct
> Add Object.defineProperties and handle props argument in Object.create

- boa/src/syntax/lexer/cursor.rs
- boa/src/syntax/lexer/tests.rs
Switch to treating bare carriage return as an OS9-style newline, like v8.
Fixes #771
- In `Cursor::next_char`, when we get a `'\r'`, we now try to consume a `'\n'`, and regardless of whether we find one we advance a newline. This has the effect of treating all of `["\r\n", "\n", "\r"]` as identical.
- Removed `Cursor::carriage_return`, as it's now unused.
> Fix lexer span panic with carriage return

- boa/Cargo.toml
- boa/src/builtins/console/mod.rs
- boa/src/builtins/mod.rs
- boa/src/context.rs
- boa/src/lib.rs
- boa/src/value/mod.rs
- boa_cli/Cargo.toml
- boa_wasm/Cargo.toml
This Pull Request fixes/closes #718 .
- Put `console` object behind a feature flag 
- Documented features
> Feature `console` crate feature

- boa/src/builtins/error/eval.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/tests.rs
- boa/src/builtins/mod.rs
- boa/src/context.rs
> Feature `EvalError`

- boa/src/builtins/function/mod.rs
- boa/src/builtins/function/tests.rs
- boa/src/builtins/object/tests.rs
- boa/src/builtins/regexp/mod.rs
This Pull Request fixes/closes #797.
-Implement Function.prototype.call
-Add a test to ensure it works
> Feature `Function.prototype.call`

- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/tests.rs
- boa/src/builtins/error/uri.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/context.rs
> Feature `URIError`

- boa/src/builtins/array/mod.rs
This Pull Request fixes the failure of test262 in CI by adding a check in `Array.prototype.map` and correcting `Array.prototype.reduceRight` for length 1.
- `Array.prototype.map` now throws a `RangeError` if the `length` of the received object is greater than 2^32 - 1, as per the spec.
- `Array.prototype.reduceRight` now works correctly for length 1.
> Fix 2 bugs that stopped test262

- boa/src/builtins/array/array_iterator.rs
- boa/src/builtins/array/mod.rs
- boa/src/builtins/date/tests.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/iterable/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/string_iterator.rs
- boa/src/context.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/object_environment_record.rs
- boa/src/object/gcobject.rs
- boa/src/object/internal_methods.rs
- boa/src/object/iter.rs
- boa/src/object/mod.rs
- boa/src/property/attribute/mod.rs
- boa/src/property/attribute/tests.rs
- boa/src/property/mod.rs
- boa/src/value/conversions.rs
- boa/src/value/display.rs
- boa/src/value/mod.rs
- boa/src/value/tests.rs
This PR adds a nice API for creating Property Descriptor (`DataDescriptor` and `AccessorDescriptor`) by making illegal state unrepresentable, for example `get` and `value` in the same property descriptor (which is not allowed, but was possible with the old implementation), which we needed dynamic checks to prove that it was not the case (performance penalty), but now we leverage the Type System for this as well as it makes implementing #591 and accessors so much easier.
- Rename `Property` => `PropertyDescriptor`
- Add `DataDescriptor` for defining data descriptors
- Add `AccessorDescriptor` for defining accessor descriptors
- Make `PropertyDescriptor` an enum
- Remove `HAS_*` form `Attribute`
- Remove `Value::update_property` related to #577
> Refactor `PropertyDescriptor`

- boa/src/syntax/parser/expression/mod.rs
Removes one unnecessary parameter.
> [parser Expression] minor expression macro simplification

- README.md
This PR adds a link to the Test262 conformance test suite. I also modified the description of the project, since it seemed to be creating some misunderstandings. We are interpreting JavaScript, not so much compiling it to a different thing.
> Added a link to the Test262 results in the README

- boa/src/syntax/lexer/cursor.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request fixes/closes #808 .
- Add `InnerIter::peek_iter()` and store the peeked char in `InnerIter` instance instead of `Cursor`
- Fix invalid Unicode code point in lexer test
The issue is caused by a bug in `Cursor::fill_bytes`. When `Cursor::fill_bytes` was called after `Cursor::peek`, the iter would be incremented to peek the next char but the peeked char would not be filled to the buffer. This PR introduces a new method `InnerIter::peek_char` and stores the peeked char in `InnerIter` so that it can fill the peeked char to input buffer when invoking `InnerIter::fill_bytes` correctly.
The test `syntax::lexer::tests::codepoint_with_no_braces` is updated in this PR. Since `\uD83D` is a surrogate code point, the test will panic when calling …
> Fix tokenizing Unicode escape sequence in string literal

- boa/src/object/gcobject.rs
This solves the clippy warning we were getting, and it might speed up things a bit. As far as I understand, there is no need to use stable sorting, right? Especially since we don't have two keys with the same name.
> Using unstable sort for sorting keys on `to_json()` for GC objects

- boa/src/builtins/array/tests.rs
- boa/src/builtins/map/tests.rs
- boa/src/context.rs
- boa/src/syntax/ast/node/array/mod.rs
This Pull Request fixes https://github.com/boa-dev/boa/issues/793
- Makes spread operator to use iterator as per spec https://tc39.es/ecma262/#sec-runtime-semantics-arrayaccumulation
- Breaks `Map` spreading, because Map does not implement iterator. That's why I opened https://github.com/boa-dev/boa/issues/810
> [exec Array] implement spread operator using iterator

- boa_cli/Cargo.toml
This PR makes it so `cargo run` runs the `boa` binary like it used to before `boa_tester` was introduced.
`boa_tester` can still be run with `cargo run --bin boa_tester`.
-Sets the default run binary to `boa`
> Set default-run to `boa` removing need for `--bin`

- boa/src/context.rs
Some terms were really wrong, like "parser_expr" or "Ok(expr)". 
I also made some opinionated minor modification (like put the private method with one statement inline, and split parsing and execution into two statements).
> [boa context] Minor refactor and rename in eval() method

- boa/src/profiler.rs
moves all OS profiling to use SerializationSink as the previous types
have been deprecated
Closes #839
> fix(profiler): update profiler to match current measureme api

- boa/src/syntax/parser/expression/update.rs
As per https://www.ecma-international.org/ecma-262/11.0/index.html#prod-UpdateExpression the right hand side of prefix increment/decrement can be an UnaryExpression and not just LeftHandSideExpression.
> Allow UnaryExpression with prefix increment/decrement

- boa/src/builtins/array/mod.rs
- boa/src/builtins/number/mod.rs
- extracts return from if let statement
- fixes clippy error in nightly
> style(boa): minor cleanup

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
- Implements `Object.getOwnPropertyDescriptor( object, property )` and `Object.getOwnPropertyDescriptors( object )`
> Implement Object.getOwnPropertyDescriptor() and Object.getOwnPropertyDescriptors()

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- .github/workflows/rust.yml
- .github/workflows/test262.yml
This should simplify the workflow configuration, and the cache should now be more efficient. Hopefully will reduce build times a bit, since it also adds cache for MacOS and Windows builds.
> Updated cache in workflows

- .github/workflows/rust.yml
- Cargo.lock
We seem to have MacOS builds failing saying that they don't find a couple of derive crates:
```
Warning: error[E0463]: can't find crate for `serde_derive` which `serde_json` depends on
```
and
```
error[E0463]: can't find crate for `gc_derive` which `gc` depends on
```
This is very, very strange, and might be a compiler / cargo regression, since it only happens there. This PR updates the MacOS cache to also cache the registry, and we update the cache keys (and the dependencies) to make sure we start with a clean cache.
> Improved MacOS cache handling and updated dependencies

- boa/src/builtins/json/tests.rs
- boa/src/value/mod.rs
> Fix JSON stringification for fractional numbers

- .github/workflows/rust.yml
It seems that MacOS builds were failing in PRs because somehow the cache doesn't work on MacOS builds in PRs. So let's remove it. It will take a bit longer to compile, but benchmarks and test262 are the bottleneck anyways.
> Removed cache from MacOS builds

- boa/src/context.rs
- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/operator/unary_op/mod.rs
- boa/src/syntax/ast/node/statement_list/mod.rs
- boa/src/vm/compilation.rs
- boa/src/vm/instructions.rs
- boa/src/vm/mod.rs
- boa_cli/src/main.rs
- Added `-`, `*`, `/`, `**`, `%`, `&`, `|`, `<<`, `>>`, `>>>`, `<`, `>`, `==`, `===`, `!=`, `!==`, `=>`, `<=`, `in`, `instanceof` operators
- Added unary operators `+`, `-`, `typeof`, `void`, `!`, `~`
- Added undefined, null, bool, string, bigint, rational literals
- When the `vm` flag is set we use the eval bytecode version and when its not we use the regular.
> More bytecodes

- boa/src/builtins/function/mod.rs
- boa/src/builtins/function/tests.rs
> Implement Function.prototype.apply

- boa/src/syntax/ast/op.rs
- boa/src/syntax/lexer/number.rs
This Pull Request fixes/closes #772 .
- boa::parse panics on invalid input. This behavior is not expected, and I fixed this to emit error on invalid input
- fixed typo in boa/src/syntax/ast/op.rs
> Make boa::parse emit error on invalid input, not panic

- boa/src/builtins/bigint/conversions.rs
- boa/src/builtins/bigint/tests.rs
This fixes the `cannot convert to BigInt` errors documented in https://github.com/boa-dev/boa/issues/817.
> Support more number literals in BigInt's from string constructor

- boa/src/builtins/array/array_iterator.rs
- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/iterable/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/map/map_iterator.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/string_iterator.rs
- boa/src/class.rs
- boa/src/context.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/object_environment_record.rs
- boa/src/object/gcobject.rs
- boa/src/object/internal_methods.rs
- boa/src/object/mod.rs
- boa/src/value/display.rs
- boa/src/value/mod.rs
- boa/src/value/type.rs
**Why move the methods?**
Moving Object internal methods to `GcObject` because we borrow the object and we hold on to it and if an accessor (getters/setters) was to access the object it will give a borrow panic.
I expect some performance regression, since we do more borrow checks.
> Move `Object` internal object methods to `GcObject`

- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/bigint/tests.rs
Fixes some radix panics from https://github.com/boa-dev/boa/issues/817
> Fix `BigInt.prototype.toString()` radix checks

- boa/src/builtins/bigint/tests.rs
- boa/src/value/operations.rs
- boa/src/value/tests.rs
> Fix remainder by zero

- boa_tester/src/main.rs
- boa_tester/src/read.rs
These changes add support for running a specific test or suite in `boa_tester`. For example, specifying `-s test/built-ins/BigInt` will only run the `BigInt` suite, while specifying `-s test/built-ins/BigInt/asIntN/arithmetic.js` will only run the specified test. If nothing gets specified, it defaults to running the full suite.
> Support running a specific test/suite in boa_tester

- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/bigint/operations.rs
- boa/src/builtins/bigint/tests.rs
- boa/src/value/operations.rs
This should fix the panics from https://github.com/boa-dev/boa/issues/883. However, I'm not very sure if this is the right way to do it or if there is a better way to generate errors instead of panicking, so I would appreciate some feedback on it.
> Fix some panics related to BigInt operations

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
These changes address the `failed to get argument for String method` panics documented in #817.
> Fix some panics in String.prototype properties

- boa_tester/src/results.rs
We were removing historical Test262 results, and this should fix it. I will later commit a fix to gh-pages to recover results retroactively.
> Fixing historical results being removed from Test262 results

- boa_tester/src/results.rs
This is hopefully the latest fix. It was now duplicating the results. We now also add some extra debug output in case it happens again.
> Another fix for the historical results generation

- boa/src/syntax/parser/error.rs
- boa/src/syntax/parser/statement/iteration/for_statement.rs
This removes the panics in `for...in` parsing. It will still fail, but at least we don't bring the process down. This comes from the idea that "every panic is a bug", not just an unimplemented feature.
> Added "unimplemented" syntax errors

- boa/src/object/internal_methods.rs
- boa/src/value/mod.rs
- Accessors now return undefined.
> Fix Accessors panics

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
This supersedes both #903 and #904. It bumps `regress` to 0.2, which brings many nice and new features and fixes. I also took the opportunity to reduce a bit the size of the `RegExp` structure by changing strings to `Box<str>`, which might show a small performance increase.
> Upgraded regress to 0.2.0

- boa/src/builtins/symbol/mod.rs
- boa/src/context.rs
- Change symbol hash from u32 to u64, This is done because it is possible to overflow the u32 hash since its only 4 bilion,  but a u64 is `18_446_744_073_709_551_616` even if we crated a symbol every `1ns` it would take `584` years (so... pretty much will never overflow)
> Change Symbol hash to `u64`

- boa/src/context.rs
This Pull Request fixes/closes #891.
- Add `Context::register_global_property`
This allows us to register any global property (primitive value, object, constructor, etc) with a property key  (symbol, string, number) and the attributes that the property will be bound to the global object. (see `register_global_property` doc test/example)
> Feature `Context::register_global_property()`

- boa/src/builtins/symbol/mod.rs
- boa/src/object/gcobject.rs
- boa/src/object/mod.rs
- boa/src/object/tests.rs
- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/operator/tests.rs
- fixed @@hasinstance symbol call
- added `get_method()` and `ordinary_has_instance()` for `GcObject`
- implemented `instanceof` operator
This Pull Request fixes/closes #796.
> Implementation of `instanceof` operator

- boa/src/syntax/parser/function/mod.rs
- boa/src/syntax/parser/mod.rs
- boa/src/syntax/parser/statement/block/mod.rs
- boa/src/syntax/parser/statement/mod.rs
- boa/src/syntax/parser/statement/switch/mod.rs
This Pull Request closes #892.
- Empty statements are now parsed without error
- Semicolons are no longer skipped at the end of the parse loop
In the original issue, it was mentioned that there might be a problem with empty `StatementLists` as well. I couldn't find a case where it didn't work as is, but I still brought the semicolon skip up a little higher.
I'm not sure if any specific tests should be written for this, but if so I can add them.
This PR improves conformance by 0.07% :smile:
> Added check to ignore semicolon in parser

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
This Pull Request fixes/closes #751.
- Adds String.prototype.codePointAt
- Adds a few more tests
- Fixes two Clippy linting suggestions
> Implement String.prototype.codePointAt

- Cargo.lock
- boa_cli/Cargo.toml
It seems that the new `rustyline` requires a new "derive" version, but dependabot was opening PRs with one or the other being updated, so they were failing. This fixes that and also updates the test262 module.
> Upgraded rustyline and test262

- boa/src/syntax/lexer/string.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request fixes #827.
- Parsing of Unicode escape sequences
- Lexer tests
> Fix Unicode character escape sequence parsing

- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/map/map_iterator.rs
- boa/src/builtins/number/conversions.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/context.rs
- boa/src/environment/function_environment_record.rs
- boa/src/object/gcobject.rs
- boa/src/object/internal_methods.rs
- boa/src/object/mod.rs
- boa/src/property/mod.rs
- boa/src/syntax/ast/node/field/get_field/mod.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/parser/statement/mod.rs
- boa/src/value/mod.rs
- boa/src/value/type.rs
This Pull Request fixes #957.
- Unresolved or misinterpreted links in the documentation
> Fix unresolved links in documentation

- boa/src/syntax/lexer/comment.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request fixes #963.
- Lexing of single line comment
> Fix single line comment lexing with CRLF line ending

- boa/src/builtins/date/tests.rs
This Pull Request fixes #967.
- Unit tests `date_proto_to_time_string` and `date_proto_to_string`
> Fix unit tests that can be failed due to daylight saving time

- boa/Cargo.toml
- boa/src/builtins/json/mod.rs
- boa/src/builtins/json/tests.rs
This Pull Request fixes/closes #346 .
- `JSON.stringify()` now supports `space` parameter
> Implement the optional `space` parameter in `JSON.stringify` 

- boa/src/builtins/number/mod.rs
- boa/src/builtins/number/tests.rs
This Pull Request closes #349.
- Implementation of Number.prototype.toPrecision is complete.
- Tests of the aforementioned method were enabled.
> Implement Number.prototype.toPrecision

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
This Pull Request fixes #971 .
- The `length` property of an array is set to non enumerable
> Fix enumerable attribute on array length property

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- boa/src/value/mod.rs
- boa/src/value/tests.rs
This Pull Request fixes #973.
-    The length property of a string is set to non enumerable
> Fix enumerable attribute on string length property

- boa/src/context.rs
- boa/src/lib.rs
- boa_cli/src/main.rs
- boa_tester/src/exec.rs
This Pull Request is a follow-up PR for #915, which closes #876.
This PR may also improve run-time performance slightly since it removes the unnecessary bytes to utf8 chars conversion when reading the files.
- Read the file input in bytes (`boa_cli`)
Except for file input in `boa_cli`, all the other places still take input in str and convert it to bytes afterward:
The crate `rustyline` reads input in strings and takes care of it.
`wasm_bindgen` makes JS interface and takes input in strings.
The benchmark still uses `include_str!` to read the bench scripts. Since the files are read in compile-time, it does not affect the run-time performance. Keep it as it can also benefit because it checks if there are any invalid chars in the bench scripts in compile time. …
> Read file input in bytes instead of string

- boa/src/context.rs
This Pull Request fixes #980.
- Prototypes for `String`, `Number` and `Boolean`
> Fix prototypes for Number, String and Boolean

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
- boa/src/object/gcobject.rs
This Pull Request closes #982 .
- Implementation of `Object.prototype.isPrototypeOf
- Fix `construct` when the prototype of the constructor is not an object
> Implement Object.prototype.isPrototypeOf

- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/value/display.rs
This Pull Request fixes/closes #998 .
- Evaluation of logical expressions
> Fix logical expressions evaluation

- boa/src/builtins/number/mod.rs
- boa/src/builtins/number/tests.rs
This Pull Request fixes/closes #1000 .
- Comparison between numbers
> Fix comparison with infinity

- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/number.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request fixes #994 
- Lexing of numbers
> Add numeric separator lexing

- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/operator/tests.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/ast/punctuator.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/operator.rs
- boa/src/syntax/lexer/tests.rs
- boa/src/syntax/parser/expression/assignment/conditional.rs
- boa/src/syntax/parser/expression/mod.rs
- boa/src/syntax/parser/expression/tests.rs
This Pull Request fixes/closes #1012.
- Lexing of `??` and `??=`
- Parsing of logical expressions
- Execution of `??` and `??=`
> Implement coalescing (?? and ??=)

- boa/src/syntax/ast/node/block/mod.rs
- boa/src/syntax/ast/node/declaration/arrow_function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/async_function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/async_function_expr/mod.rs
- boa/src/syntax/ast/node/declaration/function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/function_expr/mod.rs
- boa/src/syntax/ast/node/statement_list/mod.rs
- boa/src/syntax/ast/node/switch/mod.rs
This Pull Request fixes/closes #842
- Renames the `statements` property of the `StatementList` struct to `items`
- Renames the `StatementList::statements()` function to `StatementList::items()`
> StatementList: Rename `statements` to `items`

- boa/src/builtins/object/mod.rs
- boa/src/object/gcobject.rs
- Fix panic when argument is not supplied.
- Fix panic when `this` is not a object.
- Fix Symbol property handling.
> Fix `Object.prototype.hasOwnProperty()`

- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/date/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/lib.rs
- boa/src/object/mod.rs
- boa/src/syntax/lexer/cursor.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/tests.rs
- Fixes Clippy errors (based on `cargo clippy -Z unstable-options --fix`)
- if we want to turn off the range.contains() thing that's okay too
- ~~Ignores the `unnecessary_wraps` Clippy lint; it looks like we want all `NativeFunction`s to return a Result, which entails "unnecessary" wrapping.~~ turns out this is just a Nightly Rust thing
> Fix Clippy erorrs

- boa/src/builtins/object/mod.rs
- boa/src/object/gcobject.rs
- Fix panic if first argument is not supplied.
- Fix panic if second argument is not supplied.
- Fix bug when the second argument is not a object.
- Implemented `DefinePropertyOrThrow()`
> Fix `Object.defineProperty()`

- boa_tester/src/read.rs
This Pull Request fixes #984.
- Test suite name generation
> Fix test suite name when it contains a dot

- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/operator/tests.rs
- boa/src/syntax/ast/op.rs
- boa/src/syntax/ast/punctuator.rs
- boa/src/syntax/lexer/operator.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request implements logical assignment operators (`&&=` and `||=`).
- Lexing of `&&=` and `||=`
- Execution of `&&=` and `||=`
> Implement logical assignment operators (&&= and ||=)

- boa/src/syntax/parser/expression/assignment/mod.rs
This Pull Request implements early error for non-assignable nodes in assignment.
- `is_assignable` function in `Assignment` parsing
> Implement early errors for non-assignable nodes in assignment

- Cargo.lock
- boa_wasm/Cargo.toml
- package.json
- webpack.config.js
- yarn.lock
This also fixes the `yarn serve` that was not working since we added `getrandom` 0.2.0 as a dependency.
> Upgraded dependencies, removed deprecated deps, updated the test262 submodule

- boa/src/value/mod.rs
- boa/src/value/tests.rs
This Pull Request implements the use of  `Symbol.toPrimitive` in the `to_primitive` method of `Value`.
- `to_primitive` method of `Value` to support `Symbol.toPrimitive`
> Implement support of Symbol.toPrimitive

- boa/src/syntax/ast/node/call/mod.rs
- boa/src/syntax/ast/node/new/mod.rs
- boa/src/syntax/ast/node/spread/mod.rs
- boa/src/syntax/ast/node/spread/tests.rs
This Pull Request fixes spread in new and call expressions:
- Execution of new and call expressions so that it can use an iterable in spread
> Fix spread in new and call expressions

- boa/src/builtins/function/mod.rs
- boa/src/object/mod.rs
This Pull Request fixes the attributes on properties `length` and `name` of functions and constructors. These properties should be configurable (see [spec for length][length-spec] and [spec for name][name-spec]).
- Default attributes of `name` and `length` for functions and constructors
- Add `name` property to built-ins functions
[length-spec]: https://tc39.es/ecma262/#sec-function-instances-length
[name-spec]: https://tc39.es/ecma262/#sec-function-instances-name
> Fix attributes on properties of functions and constructors

- boa/src/builtins/function/mod.rs
- boa/src/environment/declarative_environment_record.rs
- boa/src/environment/environment_record_trait.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/environment/object_environment_record.rs
- boa/src/gc.rs
- boa/src/object/gcobject.rs
This PR works on #823.
- Adds an `allow_name_reuse` parameter to `EnvironmentRecordTrait::create_mutable_binding`
- Fixes the panic in `S10.2.1_A3.js` from the test262 test suite
- Allows the following code to run correctly without crashing Boa:
```js
function test(x, x) {
return x;
}
test(0, 1); // should return `1`
```
> Don't panic when function parameters share names

- boa/src/syntax/ast/node/operator/unary_op/mod.rs
This Pull Request fixes an issue with `delete` when the property to delete is not configurable. In this case, `delete` should not remove the property from the object, and it should return `false`.
- The execution of the `delete` operator
> Fix delete when the property is not configurable

- .vscode/tasks.json
- boa/Cargo.toml
- boa/src/context.rs
- boa/src/lib.rs
- boa/src/profiler.rs
- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/operator/unary_op/mod.rs
- boa/src/syntax/ast/node/statement_list/mod.rs
- boa/src/vm/compilation.rs
- boa/src/vm/instructions.rs
- boa/src/vm/mod.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
This does run!
Nodes implement `CodeGen` which generates instructions onto a stack held in Context.
The `VM` will interpret the instructions from Context.
There are some issues:
- only basic instructions are added, but im working off https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Internals/Bytecode for now it should be easy to add more in.
- The Stack is a Vec, this isn't ideal (we may be able to live with it for now) but the stack should really be a fixed sized array. This isn't possible because Value can't be copied in there as it holds Rc and Gc values. Can we have fixed-sized Values that hold a pointer?
- I needed to copy the Instruction vec, i couldn't find a way to pass in both `ctx` and `ctx.instructions` together without it moaning about "mutable borrowing" …
> Bytecode Interpreter (new branch)

- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/regexp/tests.rs
Regress panics on "Invalid character escape"s.
However on V8 and other JS engines these seem to be acceptable.
```js
const a = /,\;/;
```
was causing issues in Boa, due to regress panicing and us not catching.
This PR now changes it to a SyntaxError, however this is a temporary fix, ideally it should be accepted.
Raised upstream:
https://github.com/ridiculousfish/regress/issues/26
> wrap the regress error for now

- boa/src/builtins/regexp/mod.rs
- boa/src/object/internal_methods.rs
This Pull Request is related to #817.
- Removes some panics from `RegExp` methods, but it's probably not 100% spec compliant.
> Fixed some extra regex panics

- boa/src/builtins/object/mod.rs
- boa/src/object/gcobject.rs
- boa/src/object/mod.rs
- boa/src/value/display.rs
This Pull Request is related to #817.
- `Object.setPrototypeOf` and `Object.getPrototypeOf` are spec compliant
> Fixed some panics

- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
This Pull Request implements `String.prototype.split`
- Add the method implementation
- Add unit tests
> Implement String.prototype.split

- boa/src/syntax/ast/node/declaration/function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/mod.rs
- boa/src/syntax/ast/node/declaration/tests.rs
This Pull Request fixes/closes #669.
If a binding for the function name already exists, we should simply override it (`set_mutable_binding`), otherwise we need to create a new binding. For this to be accurate, we need to also fix #858, since now we are simply overriding the binding (potentially `let` or `const`).
This seems to fix it, however, I haven't found this in the documentation. The implementation of `var` also seems to follow this. Could anybody provide a link to the part where this is described in the documentation?
> Modify environment binding behaviour of function

- Cargo.lock
- boa/src/builtins/array/tests.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/number/tests.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/context.rs
- boa/src/syntax/ast/node/operator/unary_op/mod.rs
- boa/src/value/mod.rs
- boa/src/value/tests.rs
- boa_wasm/Cargo.toml
- yarn.lock
This PR works towards a panic-free boa. It fixes:
- Panics in `RegExp`
- Wrong `delete` argument
- `parseInt()` panics if radix was out of bounds.
- Spec-compliant `parseInt()` function.
I also took the opportunity to update the dependencies and the test262 submodule, and fix a couple of clippy warnings in tests, along with a documentation link.
> Fixed a bunch of test262 panics (#817)

- boa/src/object/gcobject.rs
This eliminates a number of panics in the Test262 suite.
This Pull Request works on #817.
- allows name reuse when declaring the arguments variable
> Support overriding the `arguments` variable

- boa/src/builtins/map/mod.rs
- boa/src/builtins/string/mod.rs
This PR fixes a couple of panics when working with regular expressions. I also tried to fix a double-borrow in `Map` but I only got to a bit of a better syntax, without fixing the panic.
> More panic fixes

- boa/src/syntax/parser/cursor/buffered_lexer/mod.rs
- boa/src/syntax/parser/cursor/buffered_lexer/tests.rs
- boa/src/syntax/parser/expression/assignment/arrow_function.rs
- boa/src/syntax/parser/expression/assignment/mod.rs
- boa/src/syntax/parser/function/tests.rs
Fixes #1032 
Fixes a bug in arrow function parsing which prevented the assignment of arrow functions with a single argument using parentheses (e.g. `let foo = (a) => a` )
Arrow functions with > 1 argument or arrow functions that don't use parentheses already parse correctly
> Arrow parse

- CHANGELOG.md
- Cargo.lock
- README.md
- boa/Cargo.toml
- boa_cli/Cargo.toml
- boa_tester/Cargo.toml
- boa_unicode/Cargo.toml
- boa_wasm/Cargo.toml
> Changelog v0.11

- boa/src/builtins/function/mod.rs
This PR fixes the attribute configurable of the length property of arguments.
> Fix attribute configurable of the length property of arguments

- boa/examples/classes.rs
> Fixed spelling

- boa/src/syntax/parser/expression/primary/object_initializer/mod.rs
- boa/src/syntax/parser/expression/primary/object_initializer/tests.rs
Fix `get` and`set` so they can be used as short method name in object.
> Fix get/set as short method name in object

- boa/src/builtins/array/array_iterator.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/global_this/mod.rs
- boa/src/builtins/iterable/mod.rs
- boa/src/builtins/map/map_iterator.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/for_in_iterator.rs
- boa/src/builtins/string/string_iterator.rs
- boa/src/context.rs
- boa/src/object/internal_methods.rs
- boa/src/realm.rs
- boa/src/syntax/ast/node/call/mod.rs
- boa/src/syntax/ast/node/template/mod.rs
- boa/src/value/mod.rs
This Pull Request works on #577.
- Change Realm::global_object field from `Value` to `GcObject`
- Change `make_builin_fn`'s `parent` argument from `&Value` to `&GcObject`
- Change iterators' `create_prototype` functions to return `GcObject` rather than `Value`
> Refactor: Change Realm::global_object field from Value to GcObject

- boa/src/builtins/map/mod.rs
This Pull Request fixes/closes #1058.
- Move to an index-based approach to iterating during for-each.
This approach still has issues, as mentioned in https://github.com/boa-dev/boa/issues/1058#issuecomment-761894098
> Fix panics from multiple borrows of Map.

- boa/src/syntax/ast/node/call/mod.rs
- boa/src/value/mod.rs
- Add primitive promotion to objects for method calls on primitives when non const `GetField` is used
- Remove a forgotten TODO comment
> Add primitive promotion for method calls on GetField

- boa/src/syntax/lexer/string.rs
- boa/src/syntax/lexer/template.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request fixes/closes #1078 and some bugs mentioned in the discussion of this PR.
- Minor refactor string literal lexer (for future use in lexing unicode escape in identifier name)
- Fix lexing octal escape sequence in string literal
- Fix behavior of zero escape sequence
- Fix `\` followed by a line terminator sequence
- Fix `\v`
- Fix lexing `\8` and `\9` in strict mode.
- Add more tests
> Fix lexing escapes in string literal and minor refactor

- boa/src/builtins/date/mod.rs
This Pull Request fixes/closes #1054 
- Add function `time_clip`
- Apply `time_clip` to methods of `Date`
- Add overflow checks when creating and setting `Date`
This PR resolves all known and unexplored out-of-range panics - more stable now. However, the test mentioned in the issue still failed. That is because the valid date range of `chrono::naive::NaiveDate` in Rust is smaller than the range of `Date` in JavaScript, which makes the behavior different.
> Fix out-of-range panics of Date

- boa/src/builtins/json/tests.rs
- boa/src/builtins/string/tests.rs
- boa/src/syntax/lexer/string.rs
- boa/src/syntax/lexer/template.rs
- boa/src/syntax/lexer/tests.rs
> Fix line terminator in string literal

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/number/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/syntax/lexer/number.rs
- boa/src/value/mod.rs
This Pull Request fixes/closes #1063 .
- Add dependency `fast_float` to parse float string
- Fix parsing floats panic in number lexer
- Fix bugs in `parseFloat`, `parseInt`, and `Value::to_number`
> Fix parsing floats panics and bugs

- .github/workflows/rust.yml
`cargo tarpaulin` is failing on every commit due to https://github.com/xd009642/tarpaulin/issues/517, which is also reported in cargo in https://github.com/rust-lang/cargo/issues/9220, and should be fixed when https://github.com/rust-lang/cargo/pull/9229 lands.
For the time being, we can deactivate coverage checks, which should make builds start to pass again.
> Deactivating cargo tarpaulin

- boa/src/vm/mod.rs
This Pull Request reduces code duplication in VM execution, this refactoring let me find issue #1041.
- It factors out the push of the result to the stack.
- It adds a macro for binary operations.
I did not use the macro equality, in order to keep the balance with the inequality code which, due to the `!` before the `into`, would still need the macro. When using the `binop` macro, one might want to put the call in a single line instead of using `{ ... }`.
I do not know whether upstream wants this change, but I submit it just in case. I do not know if the vm feature is enabled in CI.
This PR also fixes #1041.
> Removed duplicated code in vm.run using macros.

- boa/src/exec/tests.rs
- boa/src/syntax/ast/node/mod.rs
- boa/src/syntax/parser/statement/mod.rs
- boa/src/syntax/parser/tests.rs
This Pull Request fixes/closes #892.
- Add a new Node type: `Empty`.
- Parse the Empty
If we remove this line, `var a;` will be two statements, a VariableStatement and an EmptyStatement. That's not what we want.
Otherwise, `if(foo()) ;` won't work. We must do the same as [statement section in ecma262 spec](https://tc39.es/ecma262/#prod-Statement).
> Fully implement EmptyStatement

- boa_tester/src/exec.rs
- boa_tester/src/main.rs
Small change that would make the logs a lot more readable.
> Include name in verbose results output of boa-tester

- boa/src/syntax/ast/node/template/mod.rs
- boa/src/syntax/lexer/template.rs
- boa/src/syntax/lexer/tests.rs
- boa/src/syntax/lexer/token.rs
- boa/src/syntax/parser/expression/left_hand_side/template.rs
- boa/src/syntax/parser/expression/primary/mod.rs
- boa/src/syntax/parser/expression/primary/template/mod.rs
- boa/src/syntax/parser/function/mod.rs
- boa/src/syntax/parser/mod.rs
This Pull Request makes the evaluation of cooked template strings lazily, which improves the performance in some cases and fixes invalid escapes in raw template strings. The following sample is now supported
```javascript
function hello(s) { 
return s.raw; 
}
hello`\u\x`;
```
- Add struct `TemplateString` and update template related keywords
- Update tests
- Fix bug: `` `use strict`; `` can not be used to invoke strict mode
> Lazy evaluation for cooked template string

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/conversions.rs
- boa/src/builtins/math/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/exec/tests.rs
- boa/src/lib.rs
- boa/src/object/internal_methods.rs
- boa/src/syntax/ast/node/declaration/arrow_function_decl/mod.rs
- boa/src/syntax/ast/node/field/get_const_field/mod.rs
- boa/src/syntax/ast/node/field/get_field/mod.rs
- boa/src/syntax/ast/node/template/mod.rs
- boa/src/syntax/parser/expression/primary/template/mod.rs
- boa/src/value/mod.rs
- boa/src/value/operations.rs
- boa/src/value/tests.rs
- boa_cli/src/helper.rs
This Pull Request changes the code to respect the new lints, nothing special.
> Style: Respect the new lints from 1.51

- boa/src/environment/declarative_environment_record.rs
- boa/src/environment/environment_record_trait.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/environment/object_environment_record.rs
- boa/src/object/gcobject.rs
- boa/src/syntax/ast/node/block/mod.rs
- boa/src/syntax/ast/node/iteration/for_in_loop/mod.rs
- boa/src/syntax/ast/node/iteration/for_of_loop/mod.rs
This Pull Request fixes/closes #989 by changing the environment traversal logic to use outer environments rather than the lexical environment stack.
This is implemented by moving much of `LexicalEnvironment` logic into `EnvironmentRecordTrait` and making it recursive, allowing for most of the tasks to be implemented without cloning any `Gc` values while still keeping the borrow checker happy.
In addition to that, `FunctionEnvironmentRecord` has been updated to use `DeclarativeEnvironmentRecord` to remove duplicated code. This is similar to how `GlobalEnvironmentRecord` currently works.
Finally, an additional test for #989 was added.
> Rework environment records

- boa/src/builtins/json/mod.rs
- boa/src/object/gcobject.rs
- boa/src/value/mod.rs
This Pull Request fixes/closes #1064.
- Makes `Value::to_json`, `GcObject::to_json` return an optional `JSONValue`. If the value cannot be converted into a JSON value, the functions return `None`.
> Return optional value in to_json functions (fixes #1064)

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/array/mod.rs
- boa/src/builtins/date/tests.rs
- boa/src/syntax/lexer/mod.rs
- boa_cli/Cargo.toml
- boa_cli/src/main.rs
- boa_tester/Cargo.toml
- boa_unicode/src/tests.rs
This PR just fixes some clippy warnings that appeared with the latest Rust version released this week, and it also takes the opportunity to update some dependencies.
> Upgraded dependencies and fixed some clippy warnings/errors

- boa/src/builtins/math/mod.rs
- Implement `Math[ @@toStringTag ]`
> Implement `Math[ @@toStringTag ]`

- boa/src/builtins/json/mod.rs
- Implement `JSON[ @@toStringTag ]`
> Implement `JSON[ @@toStringTag ]`

- boa/src/builtins/symbol/mod.rs
- Implement `Symbol.prototype.description` accessor
> Implement `Symbol.prototype.description` accessor

- boa/src/builtins/regexp/mod.rs
- boa/src/syntax/lexer/mod.rs
- Implement `RegExp.prototype.global` accessor
- Implement `RegExp.prototype.multiline` accessor
- Implement `RegExp.prototype.dotAll` accessor
- Implement `RegExp.prototype.ignoreCase` accessor
- Implement `RegExp.prototype.unicode` accessor
- Implement `RegExp.prototype.sticky` accessor
- Implement `RegExp.prototype.flags` accessor
> Implement RegExp flag accessors

- test_ignore.txt
Things have improved **a lot** in the last months. This allows us to remove some ignored tests from the ignore list, so that they can actually be tested. We were even passing some of them!
> Removed a bunch of ignored tests that we no longer need to ignore

- boa_tester/src/results.rs
When the test262 conformance comments are added to a PR, it will now show the percentage symbol for the conformance, to show up it's actually a conformance percentage.
This is just a small cosmetic change for PR comments.
> Improved conformance comment format

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
This Pull Request fixes part of #36 .
- Implements Array.prototype.flat
- Implements Array.prototype.flatMap
- Implements abstract function FlattenIntoArray
- Adds test for both builtins
A few things I wasn't sure about:
- I was pretty literal with following the spec, I can tone that back a bit
- The FlattenIntoArray abstract method is supposed to return a "non-negative integer" (it's called recursively and this return value determines when the recursion ends). I had it return a `Value::Integer` for convenience but I didn't know if it should maybe return a primitive `u32` instead
- I have a value compare against `Number::MAX_SAFE_INTEGER` per the spec, but it's a `u32` so couldn't be larger than `2^53` anyways. I didn't test any arrays with huge numbers of …
> Implement Array.prototype.flat/flatMap

- boa/src/builtins/map/mod.rs
This Implements `Map.prototype[ @@toStringTag ] `
This is based on #1225
resolves #1229
> Implement Map.prototype[ @@toStringTag ]

- boa/src/builtins/bigint/mod.rs
This Pull Request fixes/closes #1230.
- Implements BigInt.prototype[ @@toStringTag ]
> Implement BigInt.prototype[ @@toStringTag ]

- boa/src/syntax/ast/keyword.rs
- boa/src/syntax/lexer/cursor.rs
- boa/src/syntax/lexer/identifier.rs
- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/tests.rs
This Pull Request add the support of Unicode escapes (`\uXXXX` and `\u{ cp }`) in identifier names. An example for this is:
```javascript
let \u0078 = 10;
console.log(x); // x = 10
```
- Update identifier lexer
- Throw syntax error when there are Unicode escapes in keyword
- Add True, False, Null to keywords (used only in lexing)
- Add unit tests
Some methods in `lexer/cursor.rs` are not used after this PR. Instead of removing them from the source code, I kept them for future use. The `#[allow(dead_code)]` is added to prevent clippy error.
> Support Unicode escape in identifier names

- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/object/mod.rs
- boa/src/object/internal_methods.rs
- boa/src/object/mod.rs
- boa/src/value/equality.rs
- boa/src/value/hash.rs
This makes the API much more intuitive.
- Make `same_value` a static method of `Value`
- Make `same_value_zero` a static method of `Value`
> Make `same_value` and `same_value_zero` static methods

- boa/src/builtins/array/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/math/mod.rs
> Fix Array.prototype.filter

- boa/src/builtins/function/mod.rs
This Pull Request fixes #1241.
> Fix slice index panic in add_rest_param

- boa/src/object/gcobject.rs
This Pull Request fixes #1059. The object was getting borrowed in `to_json` to iterate over its keys, preventing mutable borrows. The fix was to collect the keys first and to iterate over them. This will also make the test behave as expected as it will prevent properties added during iteration from being enumerated.
> Fix GcObject to_json mutable borrow panic

- boa/src/builtins/reflect/mod.rs
- boa/src/object/gcobject.rs
- boa/src/syntax/ast/node/new/mod.rs
- boa/src/syntax/ast/node/statement_list/mod.rs
This PR is a rewrite of #988, implementing default parameter support and merging `call` and `construct` implementations into a single internal method.
---
Modern JavaScript has support for default parameters in functions. Boa has support for the syntax but currently default parameters are ignored. For example, this code:
```javascript
function test(a, b = 2, c = a + b) {
console.log(a, b, c);
}
test()
test(1)
```
Result produced by current Boa master:
```
undefined undefined undefined
1 undefined undefined
undefined
```
Expected result:
```
undefined 2 NaN
1 2 3
undefined
```
> Add default parameter support

- boa/src/builtins/math/mod.rs
This Pull Request fixes/closes [#1269](https://github.com/boa-dev/boa/issues/1269)
- `Math.hypot.length` to be `2`
> Fixed hypot length bug

- boa_tester/src/results.rs
This pull request fixes code tags not being applied to test262 comments correctly.
> Fix test262 comment formatting

- boa_tester/src/read.rs
- boa_tester/src/results.rs
- test_ignore.txt
Previously, if a panic was fixed and it was now failing, it would be considered as a "new failure". This considers it a panic fix.
> Don't consider panic fixes as "new failures"

- boa/src/builtins/string/tests.rs
- boa/src/object/internal_methods.rs
This Pull Request makes ```GetOwnProperty``` for ```String``` objects behave according to specification ( https://tc39.es/ecma262/#sec-string-exotic-objects-getownproperty-p )
```
const str = "abc";
console.log(str[0]);
```
previously resulted in printing ```undefined```, now it results in printing ```"a"```
> Support GetOwnProperty for string exotic object

- boa/src/builtins/function/mod.rs
- boa/src/environment/declarative_environment_record.rs
- boa/src/environment/environment_record_trait.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/environment/object_environment_record.rs
- boa/src/object/gcobject.rs
- boa/src/realm.rs
This Pull Request fixes environment record panics that appeared after #1131.
The panics were caused by creating errors inside of environment record methods which used `&mut self`. Creating errors would involve getting values from environment records, causing gc to panic. This is fixed by making most environment record methods use `&self` and relying on internal mutability instead.
> Fix environment record panics

- .github/workflows/rust.yml
- .vscode/tasks.json
- boa/src/context.rs
- boa/src/exec/mod.rs
- boa/src/syntax/ast/node/block/mod.rs
- boa/src/syntax/ast/node/identifier/mod.rs
- boa/src/syntax/ast/node/iteration/do_while_loop/mod.rs
- boa/src/syntax/ast/node/iteration/for_in_loop/mod.rs
- boa/src/syntax/ast/node/iteration/for_loop/mod.rs
- boa/src/syntax/ast/node/iteration/for_of_loop/mod.rs
- boa/src/syntax/ast/node/iteration/while_loop/mod.rs
- boa/src/syntax/ast/node/object/mod.rs
- boa/src/syntax/ast/node/statement_list/mod.rs
- boa/src/syntax/ast/node/switch/mod.rs
- boa/src/vm/compilation.rs
- boa/src/vm/instructions.rs
- boa/src/vm/mod.rs
- boa/src/vm/tests.rs
The VM branch was failing to build. This uses the latest API changes made on Context.
This PR also introduces a new state to the executor, the `Error` state. This lets the VM know that an error has happened and immediately stops, leaving the error value on the top of the stack. Going forward this can be used to unwind the stack.
As the current path doesn't make use of this arm it should be backwards compatible.
> fix VM branch

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
This Pull Request checks off part of #36.
- Adds Array.of static method
- Adds Array.of tests
> Implement Array.of

- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/regexp/tests.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
This Pull Request implements part of #1304 .
- implement RegExp.prototype [ @@search ] ( string )
- implement String.prototype.search ( regexp )
ECMASCript Test262 test suite results:
```diff
Results:
Total tests: 78897
- Passed tests: 26797
+ Passed tests: 26833
Ignored tests: 15628
- Failed tests: 36472 (panics: 0)
+ Failed tests: 36436 (panics: 0)
- Conformance: 33.96%
+ Conformance: 34.01%
```
> implement RegExp.prototype [ @@search ] ( string )

- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/regexp/tests.rs
This Pull Request implements part of #1304 .
- Implement `get RegExp[@@species]`
- Add tests rust tests for `get RegExp[@@species]`
> Implement get RegExp[@@species]

- boa/src/builtins/array/mod.rs
- boa/src/builtins/error/eval.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/error/uri.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/reflect/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/context.rs
- boa/src/syntax/ast/node/declaration/function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/function_expr/mod.rs
- boa/src/syntax/ast/node/operator/assign/mod.rs
- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/template/mod.rs
- boa/src/value/mod.rs
- boa/src/value/tests.rs
While working on some RegExp functions I noticed, that some tests currently fail because `Value.set_field` always silently no-ops if the property is not writable. For example [match](https://tc39.es/ecma262/#sec-regexp.prototype-@@match) sets the `lastIndex` property multiple times (6.c and 6.f.iii.3.c). It uses the abstract [7.3.4 Set ( O, P, V, Throw )](https://tc39.es/ecma262/#sec-set-o-p-v-throw) operation that takes a boolean argument `throw` and should throw if the property is not writable.
I adjusted the `Value.set_field` function to make it somewhat similar to `7.3.4 Set ( O, P, V, Throw )`. I adjusted all uses of the function to match the spec, if it could be referenced. For uses without clear spec reference, I just set throw to false, so that the current behavior is not …
> Allow Value.set_field to throw

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
This Pull Request checks off a method from #36.
- Adds the method Array.prototype.copyWithin
- Adds a test for said method
Had to take a few liberties to make the code more readable, but it should be spec compliant nonetheless. Please tell me if I overlooked something to fix it asap.
> Implement Array.prototype.copyWithin

- boa/src/builtins/array/tests.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/date/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/syntax/lexer/string.rs
- boa/src/syntax/parser/cursor/buffered_lexer/mod.rs
- boa/src/value/operations.rs
A few refactors and style fixes to respect new `clippy` and `rustfmt`.
> Respect Rust 1.53

- boa/src/builtins/string/mod.rs
- test_ignore.txt
This Pull Request fixes/closes #1306.
- renames filter to filler in accordance with spec
- adds empty string check to StringPad function
> fix(boa): fix stringpad abstract operation

- boa/src/syntax/parser/function/mod.rs
- boa/src/syntax/parser/function/tests.rs
- boa/src/syntax/parser/mod.rs
This allows scripts like these to compile:
```js
"use strict";
function Hello() {}
```
> Scripts should not be considered in a block

- boa/src/builtins/array/mod.rs
- test_ignore.txt
This Pull Request fixes/closes #1306.
- throws TypeErrException according to spec for len + argCount > MAX_SAFE_INTEGER
> fix(boa): fixes unshift maximum size

- boa/src/builtins/array/mod.rs
I'll just wait for CI and merge this.
> Style: Respect rustfmft

- boa/src/builtins/array/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/regexp/mod.rs
This fixes 3 documentation warnings that we were having.
> Fixed documentation warnings

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/string/mod.rs
This Pull Request progresses on #13.
- adds string.prototype.normalize
- uses `unicode_normalization` crate
> feat(boa): adds normalize method

- boa/src/builtins/array/mod.rs
- boa/src/builtins/iterable/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/regexp/regexp_string_iterator.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/tests.rs
- boa/src/object/gcobject.rs
- boa/src/object/mod.rs
Relates to #1304
- Refactor regexp exec function
- Refactor regexp match function
- Refactor regexp matchAll function
- Refactor regexp test function
- Implement regexp split function
- Refactor string split function
- Implement RegExpStringIterator
- Implement get RegExp.prototype.source
> Refactor / Implement RegExp functions

- dev/bench/index.html
This Pull Request closes #1055.
- Adds a dark mode toggle to the top-left of the benchmarks page
- Upgrades Chart.js from v2.9 to v3.4 for improved API
> Add dark mode to benchmarks page

- boa/src/bytecompiler.rs
- boa/src/vm/code_block.rs
- boa/src/vm/mod.rs
- boa/src/vm/opcode.rs
- Implement switch statement with break support.
- Remove `_to_bytes()` free function, use `.to_ne_bytes()` instead.
- Fix use_expr bug for operator assign.
> Implement switch statement for vm

- boa/src/builtins/map/map_iterator.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/map/ordered_map.rs
- boa/src/builtins/map/tests.rs
- boa/src/object/mod.rs
This Pull Request fixes #1092.
- Changes the key of `OrderedMap` to a `MapKey`, which contains either a key or an empty value.
- Allows locking a map to allow safe iteration.
- When an entry is deleted while the map is locked, it replaces the entry with an empty value to maintain the indexes.
- When the map is unlocked any empty entries are deleted.
- Locks are implemented as a guard object so that they are released even if an error occurs.
**Concerns/Questions**
- Due to the requirements of the `indexmap::Equivalent` trait `OrderedMap` now has the key as a `Value` rather than a generic parameter. I think this should be fine as I don't think there are other uses of `OrderedMap` that might require a different key. It may even be possible to implement the …
> Use lock for map iteration

- boa/src/context.rs
This commit adds an example code snippet that demonstrates the usage of Boa when someone wants to execute a simple function that should be embedded into an application that support scripting extensions.
For example, extension through scripting is considered in https://github.com/aixigo/PREvant/issues/41
> Add Example to Execute a Function of a Script File

- .github/workflows/release.yml
- webpack.config.js
This Pull Request fixes/closes #122
- webpack.config.js 
- release.yml
> Implement gh-page workflow on release

- boa/src/builtins/array/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa_tester/src/exec/mod.rs
- test_ignore.txt
This Pull Request fixes/closes #1306.
- skips undefined values on callback
todo: speedup execution of [construct array](https://github.com/boa-dev/boa/blob/cf5ffbf1ad13d3a4cef8b0ce4025fa68859f9306/boa/src/builtins/array/mod.rs#L253-L277), currently stalls for large arrays of mainly undefined values.
> fix(boa): 15.4.4.19-8-c-ii-1.js

- boa/src/builtins/string/mod.rs
This Pull Request relates to #13.
- implements at method for strings
> feat(boa): implements `at` method for string

- boa/src/builtins/symbol/mod.rs
- Implement `Symbol.for( key )`
- Implement `Symbol.keyFor( sym )`
> Implement `Symbol.for` and `Symbol.keyFor`

- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
This Pull Request implements named capture groups for regular expressions.
- Implement support named capture groups regular expressions
- Implement support backreferences to named capture groups regular expressions
- Fix regexp `lastIndex` to be the number for utf16 codepoints instead of utf8
I implemented this feature in the regress library in https://github.com/ridiculousfish/regress/pull/34.
The 262 test `annexB/built-ins/RegExp/named-groups/non-unicode-malformed-lookbehind.js` is expected to fail, because regress now parses named backreferences and assumes that the `unicode` flag is always true.
> Implement RegExp named capture groups

- boa/src/bigint.rs
- boa/src/builtins/number/mod.rs
- boa/src/syntax/ast/node/operator/unary_op/mod.rs
- boa/src/value/mod.rs
- follows spec more rigorously
- todo: work out why hex bigint fails
> fix(boa): bitwise not operation

- boa/examples/closures.rs
- boa/src/builtins/array/mod.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/set/mod.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/context.rs
- boa/src/object/gcobject.rs
- boa/src/object/internal_methods.rs
- boa/src/object/mod.rs
- boa/src/syntax/ast/node/declaration/arrow_function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/function_expr/mod.rs
- boa/src/value/operations.rs
- boa/src/vm/mod.rs
- boa_tester/src/exec/mod.rs
This Pull Request fixes/closes #1439 #1441 #1440 #1443.
- Implement closure functions
- Implement a way to register through context
- Add example for closure `examples/closures.rs`
> Implement closure functions

- boa/src/builtins/array/mod.rs
- boa/src/builtins/array/tests.rs
- boa/src/builtins/iterable/mod.rs
- boa/src/property/mod.rs
- boa/src/value/conversions.rs
- boa/src/value/mod.rs
Related to #577 
- Make functions that should be deprecated/removed `pub(crate)` (`.get_field`, `.set_property`, `.has_field`, etc)
- Make all `Array.prototype` methods spec compliant.
- `Array.prototype.map`
- `Array.prototype.indexOf`
- `Array.prototype.lastIndexOf`
- `Array.prototype.find`
- `Array.prototype.findIndex`
- `Array.prototype.flat`
- `Array.prototype.flatMap`
- `Array.prototype.fill`
- `Array.prototype.includes`
- `Array.prototype.slice`
- `Array.prototype.reduce`
- `Array.prototype.reduceRight`
- `Array.prototype.copyWithin`
> Make `Array.prototype` methods spec compliant

- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/function/tests.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/tests.rs
- boa/src/builtins/string/tests.rs
- boa/src/builtins/symbol/tests.rs
- boa/src/lib.rs
- boa/src/syntax/mod.rs
- boa/src/value/tests.rs
This PR fixes clippy lints and makes lints warnings instead of errors. Why do we want this? It's because as clippy becomes "smarter" it's going to detect more, and they all will be errors, breaking our builds. This mostly affects nightly users as they have the latest version of clippy, but it still applies for stable (like now).
Changed CI so clippy lint warnings cause a CI failure
> Fix clippy errors

- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/regexp/regexp_string_iterator.rs
- boa/src/builtins/string/mod.rs
- boa/src/object/gcobject.rs
This Pull Request relates to #1304.
- Refactor the regexp constructor to match the spec
- Fix various errors in regexp functions
The test `built-ins/RegExp/prototype/Symbol.split/limit-0-bail.js` is now failing, because `Regexp[Symbol.split]` gets the `flags` property from the regexp prototype, which is undefined. I'm not sure where the root cause for that is, as everything in the immediate call path seems spec compliant to me. But I think we can fix that later as the split implementation itself seems spec compliant.
> Refactor regexp costructor

- boa/src/builtins/json/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/object/gcobject.rs
- boa/src/object/internal_methods.rs
- boa/src/object/mod.rs
- boa/src/object/property_map.rs
- boa/src/value/display.rs
Refactors object properties from `Object` by creating a `PropertyMap` struct.
- Adds the `PropertyMap` struct
- Changes `Object` to contain a `properties` field of type `PropertyMap`
- Adds a `properties() -> &PropertyMap` function to `Object`
- Renames `iter.rs` to `property_map.rs`
> Extract `PropertyMap` struct from `Object`

- boa/src/builtins/object/mod.rs
- boa/src/syntax/ast/node/call/mod.rs
- boa/src/syntax/ast/node/field/get_const_field/mod.rs
- boa/src/syntax/ast/node/field/get_field/mod.rs
- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/operator/unary_op/mod.rs
- boa/src/syntax/ast/node/template/mod.rs
- boa/src/value/mod.rs
- boa/src/value/type.rs
- boa/src/vm/code_block.rs
- boa/src/vm/mod.rs
This Pull Request fixes/closes #1436.
- implements the operator `typeof` as `Value::type_of`
- changes `get_type` to be equivalent to the `Type(v)` operation in the [spec](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-data-types-and-values)
- replaces calls to `type_of` with `get_type`
> Implement new `Value::type_of` method

- boa/src/builtins/string/tests.rs
- boa/src/object/internal_methods.rs
This Pull Request fixes/closes #1459.
This changes StringGetOwnProperty to use String::from_utf16_lossy. This fixes the issue mentioned, but of course `String::from_utf16_lossy` is only a hack for the missing full UTF16 support. In my opinion it is the best way to go, as writing the codepoint as an escaped string may cause even more unexpected behavior.
> Change StringGetOwnProperty to produce the same strings that the lexer produces

- boa/src/context.rs
- Implement `Context::construct_error()`
- Implement `Context::throw_error()`
> Feature throw `Error` object

- boa/src/builtins/regexp/mod.rs
- boa/src/object/gcobject.rs
- Return function execution result from constructor if the function returned
- Fix `Construct` calls in RegExp
> Return function execution result from constructor if the function returned

- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/string.rs
This Pull Request relates to #13.
- Implement String.prototype.replaceAll
- Implement StringIndexOf on JsString
- Fix some utf16 related bugs in GetSubstitution
Not all tests in the `built-ins/String/prototype/replaceAll` suite pass. I checked all failing tests and each one can be attributed to some other bug/missing feature. I will open issues for those who have none.
> Implement `String.prototype.replaceAll`

- boa/src/builtins/date/mod.rs
This Pull Request fixes/closes #1476.
- Properly handle `NaN` in `new Date()`
> Properly handle `NaN` in `new Date()`

- boa/src/builtins/array/array_iterator.rs
- boa/src/builtins/array/mod.rs
- boa/src/builtins/map/map_iterator.rs
- boa/src/builtins/set/set_iterator.rs
This Pull Request implements the abstract operation `CreateArrayFromList`.
- Creates new function `Array::create_array_from_list`
- Replaces calls to other functions with calls to the above.
- Removes the function `Array::construct_array`, as it is equivalent to `create_array_from_list`
> Implement abstract operation `CreateArrayFromList`

- boa/src/bigint.rs
This Pull Request fixes/closes #1401.
- adds crude memory check on bigint bitsize
- throws range error if exceeds 1B bits
> fix(boa): fixes panic on bigint size

- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/object/internal_methods.rs
- boa/src/property/mod.rs
This Pull Request adds the `Object.keys(...)` function.
It's my first contribution, sorry if something is missing, incorrect or dirty, I tried to implement it to-spec.
> Implement `Object.keys` and `Object.entries`

- boa/src/builtins/symbol/tests.rs
- boa/src/exec/tests.rs
- boa/src/lib.rs
- boa/src/syntax/ast/node/iteration/tests.rs
- boa/src/value/tests.rs
Towards https://github.com/boa-dev/boa/issues/803
> tests: add check_output test helper

- boa/src/builtins/date/mod.rs
- boa/src/builtins/date/tests.rs
- Handle high and negative values in `new Date()`
- Refactor `Date` setter methods
- Refactor some `Date` getter methods
- Implement `Date.prototype[Symbol.toPrimitive]` method
> Date refactor

- boa/src/object/internal_methods.rs
This Pull Request fixes/closes #1501.
- Adjust `EnumerableOwnPropertyNames` to use all `String` type property keys
This looks different from the [spec](https://tc39.es/ecma262/#sec-enumerableownpropertynames), because the meaning of `String` in `4.a: If Type(key) is String, then` is different than our internal `PropertyKey` enum types `String`, `Symbol` and `Index`. Our internal `Index` type is a `String` type in the context of the spec.
This PR is only a fix for this specific function. We should change our `[[OwnPropertyKeys]]` to be spec compliant, but I think we should wait with that until #1354 is merged, because `[[OwnPropertyKeys]]` is defined multiple times for different object types.
> Adjust `EnumerableOwnPropertyNames` to use all `String` type property keys

- boa/src/builtins/array/array_iterator.rs
- boa/src/builtins/array/mod.rs
- boa/src/builtins/map/map_iterator.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/set/mod.rs
- boa/src/builtins/set/set_iterator.rs
- boa/src/property/mod.rs
- Removes all enums of `PropertyNameKind` likes and replaces them with `PropertyNameKind`
Specifically, with #1471 I realized there were several enums akin to `PropertyNameKind` (`ArrayIterationKind`, `SetIterationKind` and `MapIterationKind`), meaning we could just unify them in a single type to avoid repetition.
> Reuse `PropertyNameKind` for all iterators

- boa/src/syntax/ast/node/declaration/arrow_function_decl/mod.rs
- boa/src/syntax/parser/expression/left_hand_side/member.rs
This Pull Request fixes/closes #1429.
- Allow `NewExpression` without arguments
- Fix arrow functions to not be constructable
> Allow `NewExpression` without arguments

- .github/workflows/rust.yml
- boa/examples/classes.rs
- boa/src/class.rs
This Pull Request fixes/closes #1262.
- Initializes the prototype of a new `ClassBuilder` to `Object object`.
- Improves the documentation of the example `classes.rs`.
> Fix panic on example `classes.rs`

- boa/src/builtins/object/mod.rs
> Implement `Object.values()`

- boa/src/builtins/object/mod.rs
- Implement `Object.prototype.valueOf`
> Implement `Object.prototype.valueOf`

- boa/src/syntax/parser/expression/primary/object_initializer/mod.rs
- boa/src/syntax/parser/expression/primary/object_initializer/tests.rs
This Pull Request fixes/closes #1308.
- Adds to the PropertyDefinition parser to look for object shorthand properties
This takes a shortcut from [the spec](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-object-initializer), it skips the use of `IdentifierReference` from the Object Initializer portion of the spec and instead parses `prop` as if it was `prop: prop` (`PropertyName/AssignmentExpression` pair).
This allows the change to only occur in the parser, as we [currently don't have an evaluation](https://github.com/boa-dev/boa/blob/master/boa/src/syntax/ast/node/object/mod.rs#L91) for `IdentifierReference`. The [evaluation semantics](https://tc39.es/ecma262/#sec-runtime-semantics-propertydefinitionevaluation) for …
> Implement parsing for object shorthand properties

- boa/src/exec/tests.rs
- boa/src/syntax/parser/expression/primary/object_initializer/tests.rs
After merging #1324, which was a bit outdated but didn't have merge conflicts, the compilation of the tests was failing. This fixes it by updating the syntax.
> Fixed tests compilation

- boa/src/builtins/array/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/reflect/mod.rs
- boa/src/object/gcobject.rs
- boa/src/object/internal_methods/mod.rs
- boa/src/object/mod.rs
- boa/src/object/operations.rs
- Implement `Object.seal( o )`
- Implement `Object.isSealed( o )`
- Implement `Object.freeze( o )`
- Implement `Object.isFrozen( o )`
- Implement `SetIntegrityLevel` spec function
- Implement `TestIntegrityLevel` spec function
- Add `IntegrityLevel` enum 
- Make some object operations public, like `JsObject::get`, `JsObject::set`, etc
> Implement `Object.seal/isSealed/freeze/isFrozen`

- boa/src/syntax/ast/node/mod.rs
- boa/src/syntax/ast/node/object/mod.rs
- boa/src/syntax/parser/expression/primary/object_initializer/mod.rs
- Implement `ComputedPropertyName` in `ObjectLiteral`
> Implement `ComputedPropertyName` in `ObjectLiteral`

- boa/src/builtins/array/mod.rs
This Pull Request closes #1517.
- `Array.of` will no longer panic if the object constructor doesn't return an object.
- `Array.of` will throw a `TypeError` when this happens, which is not spec-compliant, but as we mentioned in #1517, we cannot implement a proper function constructor just yet.
> Fixed Array.of panic with a non-conforming type error

- boa/src/string.rs
Every time we call `.get("length", context)` (and we do this a lot), this is bad for two reasons a new `JsString` is allocated every time, we do not utilize the `Rc` nature of `JsString` ref count and comparisons between to same `JsString` that point to the same memory is just a pointer compare.
> Constant `JsString`s

- Cargo.lock
- boa/Cargo.toml
- boa/examples/closures.rs
- boa/src/builtins/function/mod.rs
- boa/src/context.rs
- boa/src/object/gcobject.rs
- boa/src/object/mod.rs
This Pull Request fixes/closes #1515.
- Refactors `ClosureFunction` into a proper trait, with an additional `Copy` bound.
- Replaces `Rc<ClosureFunction>` with `Box<dyn ClosureFunction>` inside `Function`.
- Documents parts of the `function` module.
> Restrict `ClosureFunction` to only `Copy` closures

- boa/src/builtins/object/mod.rs
- Implement `Object.preventExtensions()`
- Implement `Object.isExtensible()`
> Implement `Object.preventExtensions()` and `Object.isExtensible()`

- boa/src/exec/tests.rs
- boa/src/syntax/ast/node/object/mod.rs
- boa/src/syntax/ast/node/object/tests.rs
- boa/src/syntax/parser/expression/primary/object_initializer/tests.rs
- boa/src/syntax/parser/tests.rs
This Pull Request fixes/closes #214.
- Add spread operator for object initializer
> Implement spread for objects

- boa/src/builtins/json/tests.rs
- boa/src/object/gcobject.rs
This Pull Request fixes/closes #672.
- Always return `undefined` from functions that do not `return`
- Fix `JSON.parse` test
> Always return `undefined` from functions that do not `return`

- boa/src/builtins/json/mod.rs
- boa/src/object/property_map.rs
- boa/src/object/tests.rs
This Pull Request fixes/closes  #1539.
- Replace `FxHashMap` with `IndexMap` in object properties
Benchmarks look good for this. Minimal gains on most benches and some minimal losses.
> Replace `FxHashMap` with `IndexMap` in object properties

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/console/mod.rs
- boa/src/builtins/date/mod.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/reflect/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/set/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/class.rs
This Pull Request fixes/closes #1490.
- Adds a new trait `JsArgs` to add new methods to `[JsValue]`
- Implements a new method `get_or_undefined` for `[JsValue]`
- Replaces calls to `args.get(n).cloned().unwrap_or_default()` with `args.get_or_undefined()`
This should improve the usability of the api by not having to `unwrap_or_default` everytime we want an argument inside a builtin function.
> Implement new `get_or_undefined` method for `[JsValue]`

- boa/src/builtins/array/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/date/mod.rs
- boa/src/builtins/error/eval.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/error/uri.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/set/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/object/internal_methods/mod.rs
This Pull Request reduces the repetition on constructors when obtaining the default prototype of an object.
Extracted the pattern from #1552, thanks to @Razican :)
- Implements the abstract operation `GetPrototypeFromConstructor`
- Replaces the pattern:
```Rust
let proto = new_target
.as_object()
.and_then(|obj| {
obj.__get__(&PROTOTYPE.into(), obj.clone().into(), context)
.map(|o| o.as_object())
.transpose()
})
.transpose()?
.unwrap_or_else(default_proto);
```
with
```Rust
let proto = get_prototype_from_constructor(
new_target,
|intrinsics| intrinsics.object_object().prototype(),
context,
)?;
```
This also allows for an easy replacement of  `intrinsics` with the intrinsic objects of a `realm` when we eventually implement multiple realms.
> Implement abstract operation `GetPrototypeFromConstructor`

- boa/src/context.rs
- boa/src/syntax/ast/node/declaration/arrow_function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/function_expr/mod.rs
- boa/src/syntax/ast/node/operator/unary_op/mod.rs
- boa/src/syntax/ast/node/statement_list/mod.rs
- boa/src/syntax/ast/node/statement_list/tests.rs
- boa/src/syntax/parser/function/mod.rs
- boa/src/syntax/parser/mod.rs
- boa_tester/src/exec/mod.rs
This Pull Request fixes/closes #1504.
- Add strict mode flag to `Context`
- Add strict mode detection to `StatementList` parsing
- Add strict mode handling of `delete`
> Add strict mode flag to `Context`

- boa/src/value/operations.rs
- Negation of integer now return integer.
- Fix the `%` operator to return a number with the sign of its lhs.
> Optimize integer negation

- Cargo.lock
- boa_tester/Cargo.toml
- boa_wasm/Cargo.toml
- yarn.lock
This just updates the Test262 submodule with the latest tests for the ongoing ECMAScript draft, and updates both JS and Rust dependencies.
> Upgraded dependencies and Test262 submodule

- boa/src/builtins/map/mod.rs
- boa/src/builtins/map/ordered_map.rs
Improves conformance but avoids following spec directly for performance implications.
> improve map conformance without losing perf

- boa/src/builtins/array/array_iterator.rs
- boa/src/builtins/array/mod.rs
- boa/src/builtins/iterable/mod.rs
- boa/src/builtins/map/map_iterator.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/map/ordered_map.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/for_in_iterator.rs
- boa/src/builtins/regexp/regexp_string_iterator.rs
- boa/src/builtins/set/mod.rs
- boa/src/builtins/set/set_iterator.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/string/string_iterator.rs
- boa/src/object/mod.rs
- boa/src/syntax/ast/node/array/mod.rs
- boa/src/syntax/ast/node/call/mod.rs
- boa/src/syntax/ast/node/declaration/mod.rs
- boa/src/syntax/ast/node/iteration/for_in_loop/mod.rs
- boa/src/syntax/ast/node/iteration/for_of_loop/mod.rs
- boa/src/syntax/ast/node/new/mod.rs
- boa/src/value/mod.rs
Changes:
- Change `OrderedMap` to reset its `empty_count` on `clear`.
- Document many methods of the `Map` object.
- Refactor some patterns to be more idiomatic.
- Implement `AddEntriesFromIterable`.
- Modify the API of `IteratorResult`.
- Move `Context` to the end of all related `Iterator` methods.
> Refactor builtin `Map` intrinsics to follow more closely the spec

- boa/src/syntax/ast/node/mod.rs
- boa/src/syntax/ast/node/object/mod.rs
- boa/src/syntax/parser/expression/primary/object_initializer/mod.rs
Follow up to #1514.
- Implement `ComputedPropertyName` for accessor properties in `ObjectLiteral`
> Implement `ComputedPropertyName` for accessor properties in `ObjectLiteral`

- boa/src/builtins/function/mod.rs
- boa/src/environment/declarative_environment_record.rs
- boa/src/environment/environment_record_trait.rs
- boa/src/environment/function_environment_record.rs
- boa/src/environment/global_environment_record.rs
- boa/src/environment/lexical_environment.rs
- boa/src/environment/object_environment_record.rs
- boa/src/object/gcobject.rs
- boa/src/syntax/ast/node/declaration/function_decl/mod.rs
- boa/src/syntax/ast/node/declaration/mod.rs
- boa/src/syntax/ast/node/iteration/for_in_loop/mod.rs
- boa/src/syntax/ast/node/iteration/for_of_loop/mod.rs
- boa/src/syntax/ast/node/operator/assign/mod.rs
- boa/src/syntax/ast/node/operator/bin_op/mod.rs
- boa/src/syntax/ast/node/try_node/mod.rs
- boa/src/value/mod.rs
- boa/src/vm/mod.rs
- Refactor some `EnvironmentRecordTrait` function implementations for spec compliance.
- Change some `EnvironmentRecordTrait` functions to take `&str` instead of `String` to avoid allocations.
- Change some `EnvironmentRecordTrait` functions to use accept `Context` and return `JsResult` for some spec compliant error handling.
- Add documentation for `EnvironmentRecordTrait` function implementations.
- Change `ObjectEnvironmentRecord.bindings` from `Jsvalue` to `JsObject`
- Remove now unused `JsValue.is_extensible` and `JsValue.has_field` functions.
- Replace the static `strict = true` in some `Context.set_mutable_binding` calls with the current strict value of `Context`.
> Refactor `EnvironmentRecordTrait` functions

- boa/src/builtins/json/mod.rs
- boa/src/object/gcobject.rs
- boa/src/value/mod.rs
Fixes the new test failure from #1528.
- Refactor `JSON.parse`
> Refactor `JSON.parse`

- boa/src/builtins/map/mod.rs
related to: #1445
- Adds normalisation check for has
> missing normalization improvement for has

- boa/examples/closures.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/function/tests.rs
- boa/src/context.rs
- boa/src/object/gcobject.rs
- boa/src/object/mod.rs
This Pull Request follows from #1518.
- Allows moving any `NativeObject + Clone` type as a parameter into any closure
- Adds test for the new feature
This unblocks the implementation of arguments exotic objects.
The new test is a good example of how this new feature works:
```Rust
let js_function = FunctionBuilder::closure_with_captures(
&mut context,
|_, _, context, captures| {
println!("Called `createMessage`");
// We obtain the `name` property of `captures.object`
let name = captures.object.get("name", context)?;
// We create a new message from our captured variable.
let message = JsString::concat_array(&[
"message from `",
name.to_string(context)?.as_str(),
"`: ",
captures.greeting.as_str(),
]);
println!("{}", message);
// We convert `message` into `Jsvalue` …
```
> Allow moving `NativeObject` variables into closures as external captures

- Cargo.lock
- boa/Cargo.toml
- boa/src/builtins/array/tests.rs
- boa/src/lib.rs
- boa_tester/src/main.rs
- yarn.lock
This Pull Request fixes/closes #1475.
- When building for wasm-pack, this adds the "js" feature to the `getrandom` dependency, to be able to build it.
- Updated dependencies
- Fixed a small clippy error
Interestingly, our build check didn't see this issue. Maybe we should check if it's a cache issue.
We are also getting this warning we should somehow fix (but I don't know how):
```
WARNING in ./boa_wasm/pkg/index_bg.js 195:14-60
Critical dependency: the request of a dependency is an expression
at CommonJsRequireContextDependency.getWarnings (./node_modules/webpack/lib/dependencies/ContextDependency.js:82:18)
at Compilation.reportDependencyErrorsAndWarnings (./node_modules/webpack/lib/Compilation.js:2586:24)
at ./node_modules/webpack/lib/Compilation.js:2204:10
at …
```
> Added "js" feature for getrandom for WebAssembly builds

- CHANGELOG.md
- Cargo.lock
- boa/Cargo.toml
- boa_cli/Cargo.toml
- boa_tester/Cargo.toml
- boa_unicode/Cargo.toml
- boa_wasm/Cargo.toml
in progress
Blog post:
https://github.com/boa-dev/boa-dev.github.io/pull/14
* Special thanks @neeldug for keeping on top of our CI! Making sure our Github actions and testing were working properly.
* We also had some Rust updates that needed us to [refactor some parts of our code](https://github.com/boa-dev/boa/pull/1352)
* There has been more work on the VM, in fact it has been [re-designed](https://github.com/boa-dev/boa/pull/1361) to be more efficient
* Worked on some builtins being more [spec compliant](https://github.com/boa-dev/boa/pull/1422)
* A [better design](https://github.com/boa-dev/boa/pull/1432) of property descriptors that follow the spec more closely
> changelog v0.13

- boa/src/syntax/lexer/mod.rs
- boa/src/syntax/lexer/token.rs
Found some broken links to some structures when perusing the documentation of Lexer and Parser.
> Fix broken structure links in documentation

- boa/src/builtins/object/mod.rs
- boa/src/builtins/object/tests.rs
This Pull Request *partially* fixes/closes #1580.
In this PR, I implemented `Object.getOwnPropertyNames` and `Object.getOwnPropertySymbols`. Originally I planned to open separate PRs for each of the missing method listed in #1580, but ended up implementing these two methods in one PR since they are very much alike.
I still plan to work on `Object.fromEntries` and `Object.hasOwn` in separate PRs, though. Please let me know in case it's preferred to have the implementation of these four methods in this PR instead!
There are several failing conformance tests, which are due to the following:
- `Proxy` not defined (I'm guessing it's not implemented yet?)
- `Object.getOwnPropertyNames(this)` returning slightly different set of properties from expected:
- Expected: …
> Implement Object.getOwnPropertyNames and Object.getOwnPropertySymbols

- boa/src/builtins/array/mod.rs
- boa/src/builtins/bigint/mod.rs
- boa/src/builtins/boolean/mod.rs
- boa/src/builtins/console/mod.rs
- boa/src/builtins/date/mod.rs
- boa/src/builtins/error/eval.rs
- boa/src/builtins/error/mod.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/error/uri.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/global_this/mod.rs
- boa/src/builtins/infinity/mod.rs
- boa/src/builtins/json/mod.rs
- boa/src/builtins/map/mod.rs
- boa/src/builtins/math/mod.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/nan/mod.rs
- boa/src/builtins/number/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/reflect/mod.rs
- boa/src/builtins/regexp/mod.rs
- boa/src/builtins/set/mod.rs
- boa/src/builtins/string/mod.rs
- boa/src/builtins/symbol/mod.rs
- boa/src/builtins/undefined/mod.rs
- boa/src/property/attribute/mod.rs
We currently aren't using the `BuiltIn` trait to check the initialization of builtins, meaning any struct that implements a `init` function that returns a `(&str, Value, Attribute)` tuple can be used to initialize a global builtin.
- Refactors `BuiltIn::init` to return only a `JsValue` and converts `BuiltIn::attribute` into a constant.
- Refactors the initialization of all builtins to check for an implementation of the `BuiltIn` trait.
- Creates a `globals!` macro to avoid the boilerplate.
- Refactors all builtins to conform to the new trait.
> Rewrite initialization of builtins to use the `BuiltIn` trait

- boa/src/syntax/lexer/number.rs
This Pull Request makes it possible to continue with #1602 and also fixes some errors with parsing integers.
- Instead of manually parsing and adding each character I use i128::from_str_radix, which is then converted to f64
~~Unanswered questions:~~
~~- What does the spec say about even larger numbers? I've tested NodeJS and Firefox and you can more or less get unlimited range, albeit anything that's larger than `Number.MAX_SAFE_INTEGER` is not represented exactly. With this solution, however, numbers get clamped to -1.7e+38 and 1.7e+38. I'm assuming fixing this would most likely require an overhaul of the number representation and parsing code.~~
> Fix integer parsing

- boa/src/builtins/symbol/mod.rs
Signed-off-by: hle0 <91701075+hle0@users.noreply.github.com>
This Pull Request fixes/closes #1617 .
- `valueOf` is defined differently for `Symbol` so that `Symbol('s').valueOf() == Symbol('s')`, as per the spec.
> Implement `Symbol.prototype.valueOf`

- boa/src/builtins/string/mod.rs
Signed-off-by: hle0 <91701075+hle0@users.noreply.github.com>
This pull request changes the following:
- Add `String.fromCharCode(...)` per the [ECMAScript spec](https://tc39.es/ecma262/multipage/text-processing.html#sec-string.fromcharcode)
> Implement String.fromCharCode

- boa/src/builtins/array/mod.rs
- boa/src/builtins/function/arguments.rs
- boa/src/builtins/function/mod.rs
- boa/src/builtins/intrinsics.rs
- boa/src/builtins/mod.rs
- boa/src/builtins/object/mod.rs
- boa/src/context.rs
- boa/src/object/internal_methods/arguments.rs
- boa/src/object/internal_methods/mod.rs
- boa/src/object/jsobject.rs
- boa/src/object/mod.rs
This Pull Request builds from #1354 and #1518 to implement arguments exotic objects.
- Implements argument exotic objects
- Refactors `ClosureFunction` to hold external context as a `NativeObject`
- Adds a new `FunctionBuilder::closure_with_captures` function
Should I extract the last two changes as their own PR?.
Drafting this because right now we don't have a way to know if we are `call_construct`ing in strict mode, so a lot of tests fail because they expect an unmapped argument ordinary object in strict mode and a mapped argument exotic object in non-strict mode.
> Implement arguments exotic objects

- boa/src/syntax/ast/node/block/mod.rs
- boa/src/syntax/ast/node/try_node/mod.rs
- boa/src/syntax/ast/node/try_node/tests.rs
- boa/src/syntax/parser/statement/try_stm/catch.rs
- boa/src/syntax/parser/statement/try_stm/tests.rs
This Pull Request closes #1600.
- Allows `ObjectBindingPattern`s and `ArrayBindingPattern`s as `CatchParameter`
- Checks early errors for Catch production as defined in [14.15.1](https://tc39.es/ecma262/#sec-try-statement-static-semantics-early-errors)
- If this is out of scope of the issue and should be in separate PR, let me know.
Some design decisions that may need revised:
- I used `node::Declaration` as `CatchParameter` ([code](https://github.com/boa-dev/boa/commit/acb7c766dd3a15f80bc49374d19ee5ecb14bc297#diff-657e67b4643202187d8f6e2ff6783a4ce07c5ea20e2836ccfd3d06a1a6f1e01bL150-R170)) since they are almost identical, the only difference being that `CatchParameter` won't have initialization. Should I define distinct struct for `CatchParameter`?
- I adopted …
> Allow destructuring in catch parameter

- boa/src/builtins/symbol/mod.rs
- boa/src/object/mod.rs
This Pull Request fixes/closes #1233 .
It adds `Symbol.prototype[ @@toPrimitive ]`
> Implement `Symbol.prototype[ @@toPrimitive ]`

- .vscode/launch.json
- boa/src/bytecompiler.rs
- boa/src/vm/call_frame.rs
- boa/src/vm/code_block.rs
- boa/src/vm/mod.rs
- comment out `pushUndefined` and `Return` https://github.com/boa-dev/boa/discussions/1607#discussioncomment-1416211
- Move call frame to its own file (we may end up adding more code here later)
- heading for code blocks needed to be on its own line
- Show the difference between the VM starting up and a new Call frame being ran
- add trace to VSCode launch
> VM Tidy Up

- boa/src/builtins/number/mod.rs
This Pull Request closes #1602.
It makes `toExponential` and `toFixed` methods on `Number` compliant with the specification.
One of the tests in `toExponential` currently fails. This is something that's blocked by https://github.com/rust-lang/rust/issues/89493, unless we were to implement the exponential string algorithm ourselves.
> Fix `Number.toExponential` and `Number.toFixed`
