- boa/src/builtins/array_buffer/mod.rs
- boa/src/builtins/boolean/tests.rs
- boa/src/builtins/console/mod.rs
- boa/src/builtins/error/eval.rs
- boa/src/builtins/error/range.rs
- boa/src/builtins/error/reference.rs
- boa/src/builtins/error/syntax.rs
- boa/src/builtins/error/type.rs
- boa/src/builtins/error/uri.rs
- boa/src/builtins/json/tests.rs
- boa/src/builtins/object/for_in_iterator.rs
- boa/src/builtins/object/mod.rs
- boa/src/builtins/reflect/mod.rs
- boa/src/builtins/typed_array/integer_indexed_object.rs
- boa/src/builtins/typed_array/mod.rs
- boa/src/environment/function_environment_record.rs
- boa/src/exec/tests.rs
- boa/src/object/internal_methods/mod.rs
- boa/src/object/jsobject.rs
- boa/src/object/mod.rs
- boa/src/value/display.rs
- boa/src/value/mod.rs
The objective of this PR is to try to make use of the [null pointer optimization](https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#discriminant-elision-on-option-like-enums) of the [`Option`](https://doc.rust-lang.org/std/option/#representation) type, theoretically optimizing the access of the prototype of an object.
- Changes the type of prototype of objects from `JsValue` to `JsObject`
- Creates a new type alias `ObjectPrototype` to avoid having to read `Option<Option<JsObject>>` in some places.  (name subject to change, maybe? I was thinking of using plain `Prototype` but there's already a `PROTOTYPE` constant, and `ObjectPrototype` doesn't sound as good because it could be confused with the intrinsic prototypes of constructor objects. I'd …
> Change type of prototypes of objects to `Option<JsObject>`

- boa/src/vm/code_block.rs
This Pull Request fixes/closes #1609.
- Adds CodeBlock docs
> Document CodeBlock

- dev/bench/index.html
- dev/process.py
This Pull Request does some clean-up in the benchmarks:
- Updates the Chart.js dependency
- Removes benchmark data older than 1 year
- Adds a Python script to automatically remove this data (if executed)
- Minimised the benchmark data
This is a short term solution while we improve our benchmarking.
> Cleaning-up benchmarks

- .github/workflows/master.yml
This Pull Request stops using our GitHub action fork, and starts using the upstream GitHub action for benchmarks. This follows this example:
https://github.com/benchmark-action/github-action-benchmark/tree/master/examples/criterion-rs
This is blocked, though, until https://github.com/benchmark-action/github-action-benchmark/pull/94 gets merged, since our benchmarks have spaces in their names.
> Using upstream benchmark action

- dev/README.md
- dev/bench/data.js
- dev/bench/index.html
- dev/process.py
It turns out that we were still having empty benchmarks and using the upstream action changed the benchmarks format, so it was breaking out benchmarks page. This fixes both issues and also updates the JavaScript dependencies of the benchmarks page.
> Benchmarks page adapted to the upstream format.

- test262/results.js
This Pull Request fixes/closes #1949
- Replace the testCard `<div />` with a `<a />`
- Replace `.click()` callback with an `href` attribute, and specify `target="_blank"` so that the link opens in a new tab by default
> tests web view: Change individual test links to be <a> instead of <div>, for better accessibility

- dev/process.py
This runs the benchmark cleanup script, and removes some outliers that were polluting the benchmark views.
> Removed benchmark outliers

- test262/results.js
The accordions for suite tests on our conformance page currently breaks when the suite name has a `.`. This change makes the accordion show and hide work as expected by replacing the `.` in the relevant identifiers.
> Fix conformance page accordion with `.` in suite name

- test262/index.html
- test262/results.js
This Pull Request  changes the following:
- Add a switch to hide passing test suites on the conformance page
> Add a switch to hide passing test suites

- boa_engine/src/builtins/generator/mod.rs
- boa_engine/src/builtins/json/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/expression/assign.rs
- boa_engine/src/bytecompiler/expression/update.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/block.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/bytecompiler/statement/try.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/environments/compile.rs
- boa_engine/src/environments/runtime.rs
- boa_engine/src/vm/call_frame/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/get/name.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/set/name.rs
This Pull Request fixes update operations by reusing the lvalue accessed by the update.
- Creates ops `GetNameAndLocator` and `SetNameByLocator`.
- Use new ops on update operations (`++`, `+=`, `&&=`, etc.) only when the binding is not lexical.
> Make update operations reuse the last found binding locator

- boa_engine/src/lib.rs
- boa_runtime/src/lib.rs
Hi all!
This PR is to update the docs to ease any confusion regarding adding console to a project (RE: the discussion on discord). Feel free to let me know if there are any changes you'd like to see or if a more in depth example is needed.
I can't remember if this had been decided yet, but were we publishing `boa_runtime`? I'm wondering if it would be better to link to `boajs.dev`'s docs for `boa_runtime` ~~vs. the rustdoc intra-doc link~~.
- Updates the primary example in **boa_engine** to account for console being moved to **boa_runtime**
- Builds out the docs on **boa_runtime**
> Docs update for boa_runtime and console documentation

- boa_engine/src/builtins/array_buffer/tests.rs
- boa_engine/src/builtins/regexp/tests.rs
- boa_engine/src/builtins/uri/mod.rs
- boa_engine/src/tests/control_flow/loops.rs
- boa_engine/src/tests/control_flow/mod.rs
- boa_engine/src/tests/function.rs
- boa_engine/src/tests/mod.rs
- boa_engine/src/tests/operators.rs
- boa_engine/src/value/conversions/serde_json.rs
- boa_parser/src/error/mod.rs
- boa_parser/src/error/tests.rs
- boa_parser/src/lexer/error.rs
- boa_parser/src/parser/expression/assignment/arrow_function.rs
- boa_parser/src/parser/expression/assignment/async_arrow_function.rs
- boa_parser/src/source.rs
- boa_parser/test.js
- boa_unicode/src/lib.rs
- boa_unicode/src/tests.rs
As a follow up of #2883 and #2884, this PR changes the following:
- Changed the `boa_parser::error::ErrorContext` trait, to now have a `set_context()` and `context()` setter and getters for context.
- Added unit tests for parser and lexer errors.
- Added 100% testing coverage to `boa_unicode`
- Added tests for `Source`
- Unified output for parser and lexer errors
> Added a bunch more tests

- boa_ast/src/keyword/mod.rs
- boa_ast/src/keyword/tests.rs
We have a very low code coverage in our tests, and, while we have a great end-to-end testing framework setup (test262), this doesn't run unit tests for our Rust implementation.
This is the first of a series of PRs that will try to increase our code coverage so that it reaches reasonable levels.
> Added unit tests for `boa_ast::Keyword`

- boa_engine/src/builtins/date/mod.rs
- boa_engine/src/builtins/date/tests.rs
- boa_engine/src/builtins/date/utils.rs
- boa_engine/src/context/hooks.rs
This Pull Request fixes #2874.
- Changes our `HostHooks` API to correctly handle dynamic timezones.
> Fix `Date` for dynamic timezones

- boa_ast/src/punctuator/mod.rs
- boa_ast/src/punctuator/tests.rs
This is a follow up of #2883, which adds more tests for `boa_ast::Punctuator`.
> Added unit tests for `boa_ast::Punctuator`

- boa_engine/src/builtins/array/mod.rs
- boa_engine/src/object/operations.rs
- boa_engine/src/object/shape/shared_shape/template.rs
Depends on #2723 
This PR utilizes the change done in #2723 on how we store properties on a continues indexed array, this makes the positions of properties such as `"length"` predefined on an array, because it is constructed from an `ObjectTemplate`.
This can make access on such properties just an index lookup into an array, speeding up execution of common operations like `LengthOfArrayLike`.
Pointing to #2723 for easier review, once #2723 is merged I will rebase and point to main :)
> Direct array length access

- boa_engine/src/vm/opcode/get/name.rs
- Make `typeof` throw when accessing uninitialized variables
Currently `typeof` returns `undefined` when accessing uninitialized bindings like `const`, `let`, `class`.
> Make `typeof` throw when accessing uninitialized variables

- boa_cli/src/debug/limits.rs
- boa_engine/src/vm/opcode/call/mod.rs
- boa_engine/src/vm/opcode/iteration/loop_ops.rs
- boa_engine/src/vm/opcode/new/mod.rs
- boa_engine/src/vm/runtime_limits.rs
- boa_engine/src/vm/tests.rs
- boa_examples/src/bin/runtime_limits.rs
- docs/boa_object.md
- test_ignore.toml
This Pull Request fixes/closes #809 and related to #2350 .
Like #2857 the recursion limit can be controlled through the `.runtime_limits()`:
```rust
context.runtime_limits_mut().set_recursion_limit(123); // Set to an arbitrary number
```
Or using the `$boa` object for debugging:
```js
$boa.limits.recursion = 123
function x() {
x()
}
x() // RuntimeLimit: maximum recursion limit 123 exceeded
```
Tried different values `400` seemed to not cause a stack-overflow, while `500` did, so I set it to `400`. This is in debug mode, In release we could probably set it to a higher value.
Removed `"tail-call-optimization"` feature from test262 ignore list, because it no longer causes a stack-overflow :)
Currently the way we do calls requires us to recurse in rust, this is not …
> Implement runtime limits for recursion

- boa_engine/src/builtins/function/mod.rs
- Fix wrong name of `Function.prototype[Symbol.hasInstance]`
> Fix wrong name of `Function.prototype[Symbol.hasInstance]`

- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/mod.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/expression/object_literal.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/get/generator.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_parser/src/parser/expression/assignment/yield.rs
- boa_parser/src/parser/expression/primary/object_initializer/mod.rs
- Fix object literal methods to not be constructors and not contain a prototype property.
- Refactor creation of constructor functions.
- Remove unused parameters from `create_function_object`.
- Fix generator function creation to always create a prototype property.
- Fix parsing `super` after a `yield`.
- Fix `+In` in computed property names.
> Fix remaining object literal tests

- boa_engine/src/builtins/string/tests.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/tests/operators.rs
- boa_tester/src/exec/mod.rs
- boa_tester/src/main.rs
This Pull Request  changes the following:
- Add SyntaxErrors in GlobalDeclarationInstantiation.
- Remove the unused `Early` phase in `boa_tester`.
- Move the compilation from the `parse` to the `runtime` phase in `boa_tester`.
> Add SyntaxErrors in GlobalDeclarationInstantiation

- boa_ast/src/statement/switch.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_parser/src/parser/statement/switch/mod.rs
- boa_parser/src/parser/statement/switch/tests.rs
Fixes switch `default` case execution, when a default case has regular switch cases below it (as in this test262 [test](https://github.com/tc39/test262/blob/72c0c5e16350a76bd41f7a1ceb7702588a2a39c6/test/language/statements/switch/S12.11_A1_T2.js) ) we execute the default case body at the end, we should execute the cases in order.
> Fix switch `default` execution

- boa_ast/src/operations.rs
- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/builtins/json/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/module.rs
- boa_engine/src/bytecompiler/statement/block.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/environments/compile.rs
- boa_engine/src/environments/runtime.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/define/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- Implement annexB Block-Level Function Declarations
- Remove unused opcode `DefInitArg`
- Combine the similar opcodes `DefLet`, `DefInitLet` and `DefInitConst`
There are only two tests in the `annexB/language/eval-code` and `annexB/language/function-code` suites failing. I will look at fixing them after this.
> Implement annexB Block-Level Function Declarations

- boa_ast/src/statement/mod.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/if.rs
- boa_engine/src/bytecompiler/statement/labelled.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/bytecompiler/statement/mod.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/bytecompiler/statement/try.rs
- boa_engine/src/bytecompiler/statement/with.rs
- boa_engine/src/vm/call_frame/env_stack.rs
- boa_engine/src/vm/call_frame/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/control_flow/break.rs
- boa_engine/src/vm/opcode/control_flow/continue.rs
- boa_engine/src/vm/opcode/iteration/loop_ops.rs
- boa_engine/src/vm/opcode/mod.rs
- Return values for all loops and switch statements.
- Explicitly capture and update loop return values on the `env_stack` of the `CallFrames`.
- Update loop return values on `break` and `continue`.
- Adjust bytecode to handle statements that do not return any values.
> Add loop and switch return values

- boa_parser/src/parser/statement/expression/mod.rs
- boa_parser/src/parser/statement/mod.rs
Fixes: https://github.com/tc39/test262/blob/72c0c5e16350a76bd41f7a1ceb7702588a2a39c6/test/language/statements/let/syntax/escaped-let.js
> Allow escaped `let` as expression

- boa_parser/src/parser/statement/iteration/for_statement.rs
Allow `let` variable name in `for-in` loop in non-strict mode.
Fixes: https://github.com/tc39/test262/blob/72c0c5e16350a76bd41f7a1ceb7702588a2a39c6/test/language/statements/for-in/identifier-let-allowed-as-lefthandside-expression-not-strict.js
> Allow `let` name in for-in loop in non-strict mode

- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/expression/object_literal.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/try.rs
- Remove some unused code / arguments for method compilation functions.
- Only push `PushUndefined` + `Return` at the end of a function if needed.
- Remove an `expect` in `try...catch` compilation.
> Cleanup some bytecompiler code

- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/builtins/function/arguments.rs
- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/generator/mod.rs
- boa_engine/src/environments/mod.rs
- boa_engine/src/environments/runtime/declarative/function.rs
- boa_engine/src/environments/runtime/declarative/global.rs
- boa_engine/src/environments/runtime/declarative/lexical.rs
- boa_engine/src/environments/runtime/declarative/mod.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/realm.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/environment/mod.rs
- boa_engine/src/vm/opcode/push/environment.rs
- boa_engine/src/vm/opcode/push/new_target.rs
This Pull Request separates declarative environments into kinds, which makes it easier to add more kinds in the future (spoiler: module environments).
> Separate declarative environment kinds

- boa_ast/src/declaration/variable.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/vm/call_frame/env_stack.rs
- Only push a new environment in for loops when the initializer is a `LexicalDeclaration`.
- Push a new environment for every iteration when `let` bindings are used in the initializer.
> Fix lexical environments in for loops

- boa_tester/src/edition.rs
This Pull Request fixes/closes #2886.
Previously, the code defaulted to ES5 without checking for es6id and esid. This PR selects ES6 if esid or es6id is found. 
Reference: [doc](https://chromium.googlesource.com/external/github.com/tc39/test262/+/HEAD/CONTRIBUTING.md#es6id).
> Fix ES5 selector

- boa_engine/src/builtins/regexp/mod.rs
- boa_engine/src/builtins/string/mod.rs
Fixes `GetSubstitution` which is used in by `RegExp.prototype[@@replace]` and `String.prototype.replace()` calls `RegExp.prototype[@@replace]`.
Fixes the remaining ES5 tests on `buil-ins/String` test suite.
Because of the [bug](https://github.com/tc39/ecma262/issues/1426) in the [spec about `GetSubstitution`](https://tc39.es/ecma262/#sec-getsubstitution). I had to deviate from the spec, added a comment clarifying the deviation.
> Fix `GetSubstitution`

- boa_parser/src/parser/expression/assignment/mod.rs
- boa_parser/src/parser/expression/primary/mod.rs
- boa_parser/src/parser/statement/expression/mod.rs
- boa_parser/src/parser/statement/iteration/for_statement.rs
- boa_parser/src/parser/statement/mod.rs
Just a small change in the parser to fix a couple of tests related to `async` as an identifier name.
> Allow `async` as identifier name in certain contexts

- boa_ast/src/expression/tagged_template.rs
- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/bytecompiler/expression/mod.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/realm.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/templates/mod.rs
- boa_parser/src/parser/cursor/mod.rs
- boa_parser/src/parser/expression/left_hand_side/template.rs
- boa_parser/src/parser/mod.rs
- Refactor the creation of tagged templates.
- Add a unique identifier to tagged template parse nodes that is used at runtime to cache them.
- Add an identifier to the parser that is incemented when `eval` code is parsed. This is needed because tagged templates parsed by different `eval` calls are unique.
> Fix tagged template creation

- boa_ast/src/function/class.rs
- boa_ast/src/operations.rs
- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/environments/mod.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/environments/runtime/private.rs
- boa_engine/src/object/jsobject.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/object/operations.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/binary_ops/mod.rs
- boa_engine/src/vm/opcode/get/private.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/class/field.rs
- boa_engine/src/vm/opcode/push/class/private.rs
- boa_engine/src/vm/opcode/push/environment.rs
- boa_engine/src/vm/opcode/set/private.rs
- boa_parser/src/parser/cursor/mod.rs
- boa_parser/src/parser/expression/left_hand_side/call.rs
- boa_parser/src/parser/expression/left_hand_side/member.rs
- boa_parser/src/parser/expression/left_hand_side/optional/mod.rs
- boa_parser/src/parser/expression/mod.rs
- boa_parser/src/parser/mod.rs
- boa_parser/src/parser/statement/declaration/hoistable/class_decl/mod.rs
- boa_parser/src/parser/statement/mod.rs
- Implement runtime private environments and private names conforming with the spec.
- Remove parse-time distinction and mutation of private names.
- Adjust early error handling for private names to conform with the spec.
> Implement Runtime Private Environments

- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/intl/segmenter/mod.rs
- boa_engine/src/builtins/intl/segmenter/options.rs
- boa_engine/src/builtins/intl/segmenter/segments.rs
- boa_engine/src/builtins/mod.rs
- boa_engine/src/builtins/promise/mod.rs
- boa_engine/src/environments/runtime/declarative/function.rs
- boa_engine/src/environments/runtime/declarative/mod.rs
- boa_engine/src/error.rs
- boa_engine/src/lib.rs
- boa_engine/src/module/mod.rs
- boa_engine/src/module/source.rs
- boa_engine/src/object/builtins/jspromise.rs
- boa_engine/src/object/shape/mod.rs
- boa_engine/src/object/shape/shared_shape/mod.rs
- boa_engine/src/object/shape/slot.rs
- boa_engine/src/string/mod.rs
- boa_engine/src/tagged.rs
- boa_engine/src/vm/completion_record.rs
- boa_gc/src/pointers/gc.rs
- Remove allows for `use_self` lint
- Fix all remaining `use_self` lints
> Fix `use_self` lints

- boa_engine/benches/full.rs
- boa_engine/src/builtins/weak/weak_ref.rs
- boa_engine/src/builtins/weak_map/mod.rs
- boa_engine/src/builtins/weak_set/mod.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/object/jsobject.rs
- boa_engine/src/object/property_map.rs
- boa_engine/src/object/shape/mod.rs
- boa_engine/src/object/shape/root_shape.rs
- boa_engine/src/object/shape/shared_shape/mod.rs
- boa_engine/src/object/shape/shared_shape/template.rs
- boa_engine/src/object/shape/unique_shape.rs
- boa_engine/src/realm.rs
Currently when we construct a `Realm` we take a `SharedShape` as the root, since users can create realms to ensure that the passed shape is the root shape (otherwise if a non-root shape is passed, will at best cause a panic and at worse will give unexpected behaviour), added the `RootShape` that ensures that only a root shape is passed, this is applied to many other places where a root shape is required.
- Add `RootShape` wrapper around `SharedShape`
- Implement `From<UniqueShape>` for `Shape`
- Implement `From<SharedShape>` for `Shape`
> Type safe root shape

- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/builtins/function/arguments.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/block.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/bytecompiler/statement/try.rs
- boa_engine/src/environments/compile.rs
- boa_engine/src/environments/runtime/declarative/function.rs
- boa_engine/src/environments/runtime/declarative/global.rs
- boa_engine/src/environments/runtime/declarative/lexical.rs
- boa_engine/src/environments/runtime/declarative/mod.rs
- boa_engine/src/environments/runtime/declarative/module.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/object/internal_methods/arguments.rs
- boa_engine/src/realm.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/opcode/push/environment.rs
Shrinks environments binding locators (which we were already doing when we truncate it to environment bytecode operands).
> Shrink environment binding locators

- boa_engine/src/builtins/regexp/mod.rs
- Fix remaining ES5 `built-ins/RegExp` tests
- Don't allocate on every match check
> Fix remaining ES5 `built-ins/RegExp` tests

- .vscode/launch.json
- Cargo.lock
- boa_ast/Cargo.toml
- boa_ast/src/declaration/export.rs
- boa_ast/src/module_item_list/mod.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/expression/mod.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/module.rs
- boa_engine/src/bytecompiler/statement/labelled.rs
- boa_engine/src/module/source.rs
- boa_engine/src/object/internal_methods/module_namespace.rs
- boa_engine/src/tests/mod.rs
- boa_parser/src/parser/expression/identifiers.rs
- boa_parser/src/parser/statement/declaration/export.rs
- boa_parser/src/parser/statement/declaration/import.rs
- test_ignore.toml
This Pull Request fixes our remaining module bugs in the `test/language/module-code` suite.
This leaves us with:
```bash
Results (ECMAScript Next):
Total tests: 581
Passed tests: 551
Ignored tests: 13
Failed tests: 17 (0 panics)
Conformance: 94.84%
```
16 tests are being fixed because they have an incorrect phase tag (https://github.com/tc39/test262/pull/3832), and the 13 ignored tests are import assertions, which are still stage 3. Our true conformance status would be:
```bash
Results (ECMAScript Next):
Total tests: 581
Passed tests: 567
Ignored tests: 13
Failed tests: 1 (0 panics)
Conformance: 97.59%
```
The last failing test (test/language/module-code/eval-export-dflt-expr-cls-name-meth.js) seems to be a spec bug, but I'll investigate further.
> Fix remaining static module bugs

- boa_engine/src/vm/call_frame/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/binary_ops/logical.rs
- boa_engine/src/vm/opcode/control_flow/break.rs
- boa_engine/src/vm/opcode/control_flow/catch.rs
- boa_engine/src/vm/opcode/control_flow/continue.rs
- boa_engine/src/vm/opcode/control_flow/finally.rs
- boa_engine/src/vm/opcode/control_flow/labelled.rs
- boa_engine/src/vm/opcode/control_flow/return.rs
- boa_engine/src/vm/opcode/control_flow/throw.rs
- boa_engine/src/vm/opcode/environment/mod.rs
- boa_engine/src/vm/opcode/generator/mod.rs
- boa_engine/src/vm/opcode/iteration/iterator.rs
- boa_engine/src/vm/opcode/jump/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/rest_parameter/mod.rs
- boa_engine/src/vm/opcode/switch/mod.rs
- boa_engine/src/vm/opcode/templates/mod.rs
Hopefully this is will be a PR in a series of PRs to refactor the way we call functions and in general and making it easier to implement some optimizations, breaking it down into smaller parts for easier review :)
- Remove redundant `param_count` field from `CallFrame`
- Make `pc`, `fp`,, etc a `u32`.
> Remove redundant `param_count` field from `CallFrame`

- boa_engine/src/builtins/boolean/tests.rs
- boa_engine/src/builtins/map/ordered_map.rs
- boa_engine/src/builtins/number/tests.rs
- boa_engine/src/builtins/string/mod.rs
- boa_engine/src/builtins/string/tests.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/object/builtins/jspromise.rs
- boa_engine/src/object/internal_methods/string.rs
- boa_engine/src/realm.rs
- boa_engine/src/string/mod.rs
- boa_engine/src/value/tests.rs
- boa_parser/src/lexer/cursor.rs
- boa_parser/src/lexer/tests.rs
- boa_parser/src/parser/cursor/mod.rs
- boa_parser/src/parser/mod.rs
- boa_parser/src/parser/tests/mod.rs
- boa_profiler/src/lib.rs
- boa_runtime/src/console/mod.rs
- boa_tester/src/main.rs
- boa_tester/src/read.rs
- boa_tester/src/results.rs
- Remove some unused lint allows
- Move some lint allows to more specific items
> Remove unused lint allows

- boa_cli/src/debug/function.rs
- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/block.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/bytecompiler/statement/try.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/call/mod.rs
- boa_engine/src/vm/opcode/define/mod.rs
- boa_engine/src/vm/opcode/delete/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/environment.rs
- boa_engine/src/vm/opcode/set/name.rs
- boa_engine/src/vm/opcode/set/property.rs
Since the number of bindings is stored in the compiled envionments and when we create the environment we pass it, there is no need to store the num_bindings for the environments
- Remove unneeded `function_environment_push_location` field on `CodeBlock`
- Remove unneeded `num_bindings` field on `CodeBlock`
- Remove unneeded `num_bindings` operand from `PushDeclarativeEnvironment` opcode
- Remove unneeded `num_bindings` operand from `PushFunctionEnvironment` opcode
- Make `ByteCompiler::push_compile_environment()` return only the index.
- Remove `num_bindings` field from environment stack methods that push environments.
- Move `CodeBlock` flags to `bitflags` field.
> Remove unneded `num_bindings` in `Opcode`s and `CodeBlock`

- boa_engine/src/object/shape/shared_shape/forward_transition.rs
- boa_engine/src/object/shape/shared_shape/mod.rs
- boa_engine/src/object/shape/shared_shape/tests.rs
- boa_gc/src/pointers/ephemeron.rs
- boa_gc/src/pointers/weak.rs
This PR prunes all transitions in a `SharedShape` when a transition's `WeakGc` has been garbage collected and when we insert `255` properties/prototypes.
Example with debug print on prune:
```js
>> ({a: 1})
{
a: 1
}
>> ({a: 1, b: 2})
{
a: 1,
b: 2
}
>> $boa.gc.collect() // Trigger a garbage collection.
undefined
>> ({a: 1})
DEBUG PRINT - Pruning property transitions
{
a: 1
}
>>
```
> Prune collected shared shapes

- boa_engine/src/builtins/function/arguments.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/vm/code_block.rs
This PR reorders a spec step to ensure that the `"arguments"` binding is always in the `0` position. This allows us to remove the `arguments_binding` field completely since we know in which environment it is (last pushed) and what index it has (`0`).
Removes `24` bytes from `CodeBlock` (from `184` bytes to `160` bytes)
> Remove `arguments_binding` field from `CodeBlock`

- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/nop/mod.rs
Optimizes opcode fetching by removing the checks that validate if it's a correct opcode. every `u8` combination matches to a valid `Opcode` variant (even if it's reserved).
**Main:**
```
Richards: 20.5
DeltaBlue: 24.8
RayTrace: 81.0
----
Score (version 7): 34.5
undefined
```
**PR:**
```
Richards: 20.6
DeltaBlue: 24.8
RayTrace: 82.1
----
Score (version 7): 34.8
undefined
```
There is a small improvement in performance.
> Direct conversion from `u8` to `Opcode`

- boa_parser/src/lexer/identifier.rs
- boa_parser/src/lexer/tests.rs
- boa_parser/src/lexer/token.rs
- boa_parser/src/parser/expression/assignment/yield.rs
- boa_parser/src/parser/expression/left_hand_side/call.rs
- boa_parser/src/parser/expression/left_hand_side/member.rs
- boa_parser/src/parser/expression/left_hand_side/optional/mod.rs
- boa_parser/src/parser/expression/primary/mod.rs
- boa_parser/src/parser/expression/primary/object_initializer/mod.rs
- boa_parser/src/parser/statement/declaration/hoistable/class_decl/mod.rs
- boa_parser/src/parser/tests/mod.rs
This Pull Request fixes/closes #2771.
This PR keeps track of `ContainsEscapeSequence` in all `TokenKind::BooleanLiteral` and `TokenKind::NullLiteral` and throws an error when it gets parsed as an expression.
Opening a different PR for this since I messed up the commit history of the previous PR.
> Deny Unicode Escapes in boolean and null expressions

- boa_engine/src/bytecompiler/statement/continue.rs
- boa_engine/src/string/mod.rs
- boa_engine/src/value/tests.rs
- boa_engine/src/vm/opcode/rest_parameter/mod.rs
This Pull Request fixes rust 1.70 lints.
> Fix rust 1.70 lints

- .github/workflows/rust.yml
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/bytecompiler-implied.rs
- fuzz/fuzz_targets/common.rs
- fuzz/fuzz_targets/parser-idempotency.rs
- fuzz/fuzz_targets/vm-implied.rs
This PR updates the fuzzers to the latest version of the code and adds them to the CI. It does _not_ perform the fuzz run.
Both `parser-idempotency` and `vm-implied` find crashes pretty quickly. Maybe would be worthwhile to have another round of testing with this. :)
> Update fuzzers and add building them to CI

- Cargo.lock
- boa_engine/src/context/mod.rs
- boa_engine/src/module/mod.rs
- boa_wasm/Cargo.toml
- boa_wasm/src/lib.rs
This Pull Request fixes #2991.
- Creates a new `IdleModuleLoader` that rejects all load requests.
- Makes `IdleModuleLoader` the default loader if `SimpleModuleLoader` returns a creation error.
> Fix WASM playground

- boa_ast/src/operations.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/module/source.rs
Small fix that ensures bindings inside functions are correctly resolved to outer functions.
> Correctly initialize functions inside modules

- boa_engine/src/object/jsobject.rs
This should implement Debug a bit better for objects, previously they recursed a lot and spewed out a lot of garbage. This shows the kind, name and address for each object, which should be enough when investigating issues.
Before:
<hot mess>
After:
`&func = (Function) "fib" 0x7F9A67F17218`
> show object kind, name and address when using dbg!

- boa_engine/src/tests/mod.rs
- boa_parser/src/parser/statement/mod.rs
This Pull Request allows using certain valid keywords inside patterns.
> Allow `true`, `false` and `null` in object patterns

- boa_ast/src/operations.rs
- boa_parser/src/parser/expression/left_hand_side/optional/tests.rs
- Fix panic in optional expressions with private identifiers
Credit to @addisoncrump and their work on our fuzzers which found this panic :)
> Fix panic in optional expressions with private identifiers

- boa_cli/src/helper.rs
- boa_cli/src/main.rs
- boa_engine/src/optimizer/mod.rs
- Moves prompt highlighting to the helper class
- Fixes prompt width calculation on windows
In rustyline, there are two implementations of `calculate_position`, one for [windows](https://github.com/kkawakam/rustyline/blob/master/src/tty/windows.rs#L469) and one for [unix](https://github.com/kkawakam/rustyline/blob/master/src/tty/unix.rs#L1020). The one for unix support ignoring ANSI escape sequences when calculating width, but the one on windows does not, [by design](https://github.com/kkawakam/rustyline/pull/215#issuecomment-491945339).
This caused an issue where the cursor would be placed 12 columns in, instead of 3.
> Fix prompt on windows

- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/tests.rs
- Fix a bug in the constructor execution that leads to a panic when an arguments object is needed. In contrast to the call execution the wrong environment is being pushed.
> Fix panic in constructor call

- boa_parser/src/parser/expression/assignment/yield.rs
Very small change that allows `yield import(..)` expressions.
> Correctly parse `yield import(..)` expressions

- boa_engine/src/bytecompiler/statement/break.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/control_flow/break.rs
- boa_engine/src/vm/opcode/mod.rs
- Return the correct value during a labelled break
> Return the correct value during a labelled break

- boa_ast/src/operations.rs
- boa_ast/src/statement/mod.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/break.rs
- boa_engine/src/bytecompiler/statement/if.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/bytecompiler/statement/try.rs
- boa_engine/src/bytecompiler/statement/with.rs
- boa_engine/src/vm/tests.rs
This adds and fixes some tests that caused panics on `main` and during the development of the fixes. All where found with the fuzzer. After running the fuzzer for some time I did not encounter any similar panics anymore.
> Fix panics on empty return values

- boa_parser/src/parser/statement/declaration/hoistable/class_decl/mod.rs
- Add early error for `await` in class static blocks
> Add early error for `await` in class static blocks

- boa_engine/src/module/mod.rs
- boa_examples/src/bin/modules.rs
While implementing an example of async module fetching, I realized it would be useful to have a way to insert a module through a `&dyn ModuleLoader`. This PR provides that API.
~~Drafting because I'm still experimenting with the final design of the API.~~
> Add convenience methods to `ModuleLoader`

- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/environments/runtime/private.rs
- boa_engine/src/object/jsobject.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/object/operations.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/opcode/binary_ops/mod.rs
- boa_engine/src/vm/opcode/get/private.rs
- boa_engine/src/vm/opcode/push/class/field.rs
- boa_engine/src/vm/opcode/push/class/private.rs
- boa_engine/src/vm/opcode/push/environment.rs
- boa_engine/src/vm/opcode/set/private.rs
- Merges `private_names` into `names` constant pool.
- Make private names use `JsString` instead of `Sym`
> Merge `private_names` into `names` constant pool

- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/vm/code_block.rs
In the entire spec the `[[ClassFieldInitializerName]]` field is only used to check that it's not empty (in `PerformEval`), so removed it and added a bitflag for it.
- Remove `[[ClassFieldInitializerName]]` from `CodeBlock`
- Add `IN_CLASS_FIELD_INITIALIZER` bitflag
> Remove `[[ClassFieldInitializerName]]` from `CodeBlock`

- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/expression/assign.rs
- boa_engine/src/bytecompiler/expression/update.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/environments/compile.rs
- boa_engine/src/environments/mod.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/define/mod.rs
- boa_engine/src/vm/opcode/delete/mod.rs
- boa_engine/src/vm/opcode/get/name.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/set/name.rs
The `mutate_immutable` and `silent` checks are known at compile time and we can generate more specialized opcodes for them.
- Add `ThrowMutateImmutable` opcode.
- Generate more optimized opcode.
> Remove `mutate_immutable` and `silent` checks from Opcodes 

- boa_engine/src/vm/opcode/swap/mod.rs
Instead of using `Vec::pop` and `Vec::push` two times, we can use `slice::swap`. The explicit assert allows the compiler to reduce the panic logic further.
> Optimize `Swap` opcode

- boa_engine/src/context/mod.rs
- boa_engine/src/job.rs
This change allows implementors of `JobQueue` to concurrently run the pending jobs with some other runtime logic they're running in their app.
Will also become useful to add features to `boa_runtime`.
> Allow `JobQueue` to concurrently run jobs

- boa_engine/src/builtins/typed_array/integer_indexed_object.rs
This allows querying the full range of the `TypedArray` in the underlying `ArrayBuffer`.
> Make `IntegerIndexed::byte_offset` public

- Cargo.lock
- boa_engine/Cargo.toml
- boa_engine/src/builtins/promise/mod.rs
- boa_engine/src/native_function.rs
- boa_engine/src/object/builtins/jspromise.rs
- boa_gc/src/trace.rs
- boa_icu_provider/src/lib.rs
Should be mostly useful for consumers of the `JobQueue::enqueue_future_job` API, since they can now await for certain promises inside `async` blocks and functions.
Changes:
- Adds a new `JsFuture` type that implements `Future`.
- Adds a new `JsPromise::into_js_future` method.
- Rewrites the caveats section of `NativeFunction::from_async_fn`, since the old explanation was wrong.
- Adds a new `JsPromise::from_future` constructor.
- Improves some promise code.
> Allow awaiting `JsPromise` from Rust code

- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/declaration/declaration_pattern.rs
- boa_engine/src/bytecompiler/expression/assign.rs
- boa_engine/src/bytecompiler/expression/mod.rs
- boa_engine/src/bytecompiler/expression/object_literal.rs
- boa_engine/src/bytecompiler/expression/update.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/get/property.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/set/home_object.rs
- boa_engine/src/vm/opcode/set/property.rs
This fixes some cases where property access via `super` was returning wrong values.
- Add correct receiver values for object set and get opcodes.
- Set the `[[HomeObject]]` field for methods in object literals.
> Fix super property access

- boa_tester/src/edition.rs
- test_ignore.toml
Superseeds #3048.
At TC62's meeting last month, some new features were promoted to stage 4. This PR cleans up our test262 feature tracking to reflect this, which will make our lives easier when ES14 releases.
> Cleanup test262 features and bump submodule

- boa_engine/src/vm/opcode/environment/mod.rs
- boa_engine/src/vm/opcode/mod.rs
This Pull Request fixes some failing test262 tests depending on a derived super call.
- It removes reversing arguments passed to the derived super call. `code_block::construct_internal` already reverses the arguments into `argument_n ... argument_1` on to the stack, since normal constructor parameters are resolved in order.
> Skip reversing arguments in SuperCallDerived

- boa_gc/src/internals/ephemeron_box.rs
- boa_gc/src/lib.rs
- boa_gc/src/test/weak.rs
A very subtle bug that was discovered by @tunz. Also added additional checks on the test to make sure the ephemerons are correctly cleaned up.
> Mark header of rooted ephemerons when tracing

- .github/workflows/rust.yml
- boa_wasm/src/lib.rs
Testing if this change improves CI times for the codecov check.
Had to use another `cargo-install` action because the original `actions-rs/cargo-install` is apparently unmaintained, and users were reporting problems with the cache (https://github.com/actions-rs/install/issues/12)
> Cache `cargo-tarpaulin` binary

- boa_ast/ABOUT.md
- boa_ast/src/lib.rs
- boa_cli/ABOUT.md
- boa_cli/src/main.rs
- boa_engine/ABOUT.md
- boa_engine/src/lib.rs
- boa_gc/ABOUT.md
- boa_gc/src/lib.rs
- boa_icu_provider/ABOUT.md
- boa_icu_provider/src/lib.rs
- boa_interner/ABOUT.md
- boa_interner/src/lib.rs
- boa_macros/ABOUT.md
- boa_macros/src/lib.rs
- boa_parser/ABOUT.md
- boa_parser/src/lib.rs
- boa_profiler/ABOUT.md
- boa_profiler/src/lib.rs
- boa_runtime/ABOUT.md
- boa_runtime/src/lib.rs
- boa_tester/ABOUT.md
- boa_tester/src/main.rs
- boa_wasm/ABOUT.md
- boa_wasm/src/lib.rs
Unfortunately, `cargo publish` cannot handle having relative paths to files outside of the published crate, which is why we need to undo the change. Left the individual files though, since it makes it easier to check for diffs at least.
Thought about using symlinks instead, but it seems that support for symlinks in git on windows [is still suboptimal](https://stackoverflow.com/a/59761201).
> Copy `ABOUT.md` file to all published crates

- boa_engine/src/tests/control_flow/mod.rs
- boa_engine/src/vm/opcode/control_flow/finally.rs
The match was too greedy, being executed for 'break' abrupt completions as well.
Closes #3054
> Correctly handle finally..loop..break

- .github/workflows/release.yml
- .prettierignore
This would resolve https://github.com/boa-dev/boa/issues/3035
> create binaries for the releases

- boa_parser/src/parser/statement/mod.rs
- Allow escaped yield and await in labelled statement
> Allow escaped yield and await in labelled statement

- boa_cli/src/debug/function.rs
- boa_cli/src/debug/limits.rs
- boa_cli/src/debug/object.rs
- boa_cli/src/debug/shape.rs
- boa_engine/src/builtins/date/mod.rs
- boa_engine/src/builtins/escape/mod.rs
- boa_engine/src/builtins/generator/mod.rs
- boa_engine/src/builtins/intl/list_format/mod.rs
- boa_engine/src/builtins/intl/segmenter/iterator.rs
- boa_engine/src/builtins/intl/segmenter/segments.rs
- boa_engine/src/builtins/object/mod.rs
- boa_engine/src/builtins/promise/mod.rs
- boa_engine/src/builtins/set/mod.rs
- boa_engine/src/class.rs
- boa_engine/src/lib.rs
- boa_engine/src/module/source.rs
- boa_engine/src/object/internal_methods/module_namespace.rs
- boa_engine/src/object/shape/slot.rs
- boa_engine/src/string/mod.rs
- boa_engine/src/vm/opcode/iteration/iterator.rs
- boa_macros/src/lib.rs
- boa_parser/src/lexer/mod.rs
- boa_parser/src/parser/expression/primary/object_initializer/mod.rs
- boa_parser/src/parser/function/mod.rs
- boa_parser/src/parser/statement/declaration/mod.rs
- boa_runtime/src/lib.rs
- boa_tester/src/exec/mod.rs
This PR runs `cargo +nightly fmt` to format all our let-else expressions with the newest rustfmt binary, which now supports let-else.
> Format let-else expressions

- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/expression/assign.rs
- boa_engine/src/bytecompiler/expression/update.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/environments/compile.rs
- boa_engine/src/environments/runtime/declarative/mod.rs
- boa_engine/src/environments/runtime/declarative/module.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/module/source.rs
- boa_engine/src/object/internal_methods/module_namespace.rs
- boa_engine/src/realm.rs
- boa_engine/src/vm/code_block.rs
All fields except the `bindings` field are not mutated after `CompileTimeEnvironment` creation. It moves the `RefCell` to `bindings` field, this cleans the methods callsites.
> Move `RefCell` of `CompileTimeEnvironment`s to field `bindings`

- boa_engine/src/builtins/typed_array/mod.rs
Make `TypedArray.prototype.values()` and `TypedArray.prototype[@@iterator] share the same function object.
> `TypedArray.prototype.values()` and `TypedArray.prototype[@@iterator]` should be equal

- Cargo.lock
- boa_ast/Cargo.toml
- boa_cli/Cargo.toml
- boa_engine/Cargo.toml
- boa_interner/Cargo.toml
- boa_macros/Cargo.toml
- boa_tester/Cargo.toml
- boa_wasm/Cargo.toml
- package-lock.json
- Removes the `time` dependency from `boa-wasm`, which was a leftover (we didn't remove default features), and was causing a security warning in the repo. We no longer have time 0.1 in our dependency tree.
- Updated dependencies.
I also went through all the duplicate / outdated dependencies in the tree and I opened / subscribed to these dependency updates:
- https://github.com/unicode-org/icu4x/pull/3655
- https://github.com/xacrimon/dashmap/pull/270 (https://github.com/xacrimon/dashmap/pull/250 would already help)
- https://github.com/axelf4/unicode-linebreak/pull/9
- https://github.com/bheisler/criterion.rs/pull/695
- https://github.com/unicode-org/icu4x/pull/3367
We are also waiting for new releases of the following crates / crate groups:
- icu4x after …
> Removed time 0.1 dependency, updated dependencies

- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_runtime/src/console/mod.rs
> Change `name`  field type in `CodeBlock` to `JsString`

- boa_engine/src/builtins/regexp/mod.rs
This Pull Request closes #3086
- Implements `re.exec().indices` & `re.exec().indices.groups`
- Fixes ordering of `re.exec().groups` to pass strict test262 tests
- Updates related comments to be inline with the [spec](https://tc39.es/ecma262/multipage/text-processing.html#sec-regexpbuiltinexec)
- Skipped the two unicode related tests in the `test/built-ins/RegExp/match-indices` suite. Which seems to be a separate task in itself across the Regex implementation.
I'm a bit unsure about the following:
- [`GetMatchIndexPair`](https://tc39.es/ecma262/multipage/text-processing.html#sec-getmatchindexpair) and [`MakeMatchIndicesIndexPairArray`](https://tc39.es/ecma262/multipage/text-processing.html#sec-makematchindicesindexpairarray) are currently done inline. This …
> Add regexp indices (`d` flag) support

- boa_engine/src/builtins/array/mod.rs
This also includes the variants for `toSorted`, `toSpliced` and `toReversed` even though they are not implemented yet. This doesn't have any effect on the runtime since `with` is not implemented to use `Symbol.unscopables`.
> Add missing 'unscopables' to `Array.prototype[@@unscopables]`

- README.md
This PR adds the new CLI options included in Boa 0.17 in the README.
I guess we can leave it for 0.18, but we could in theory release a 0.17.1 version, which would also include the removal of time 0.1 from the dependency tree.
> Add new CLI options to usage in README

- boa_engine/src/builtins/array/mod.rs
- boa_engine/src/builtins/typed_array/mod.rs
This Pull Request references #3100 
- It aligns the implementations of `Array.prototype.find{Index,Last,LastIndex}` and the existing TypedArray variants to use [`FindViaPredicate ( O, len, direction, predicate, thisArg )`](https://tc39.es/ecma262/#sec-findviapredicate)
> Refactor `Array.prototype.find*` and TypedArray variants to use `FindViaPredicate`

- boa_engine/src/context/mod.rs
- boa_engine/src/module/mod.rs
- boa_engine/src/object/builtins/jsdataview.rs
- boa_examples/src/bin/modulehandler.rs
This Pull Request fixes the lints from Rust 1.71.0
> Fix 1.71.0 lints

- boa_engine/src/builtins/typed_array/mod.rs
This Pull Request closes #3100 
Depends on #3134 (iirc putting my fork as the base would not automatically switch the base of this PR to `main` once the other one is merged..)
- Implements [`%TypedArray%.prototype.findLast ( predicate [ , thisArg ] )`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.findlast) and [`%TypedArray%.prototype.findLastIndex ( predicate [ , thisArg ] )`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.findlastindex)
> Implement `findLast` and `findLastIndex` on TypedArray

- boa_engine/src/bigint.rs
- boa_engine/src/value/mod.rs
This commit implements trait conversions to JsValue for i128/u128. This addresses #1970
This Pull Request fixes/closes #{1970}.
- Adds trait conversions for the missing i128 and u128 rust types to JsValue
-
-
> Implement i128/u128 to JsBigInt conversions

- boa_engine/src/builtins/array_buffer/mod.rs
- boa_engine/src/builtins/typed_array/mod.rs
- boa_engine/src/object/internal_methods/integer_indexed.rs
This Pull Request fixes all remaining `TypedArrayConstructors` tests.
- Fix typo in TypedArray constructor.
- Update the spec and code for some TypedArray and ArrayBuffer creation functions.
- Add explicit early `drop`s to burrowed `Gc`s in TypedArray methods where needed.
- Fix logic errors in integer-indexed exotic object methods.
> Fix TypedArrayConstructors tests

- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/iterable/mod.rs
- boa_engine/src/builtins/map/ordered_map.rs
- boa_engine/src/builtins/promise/mod.rs
- boa_engine/src/builtins/set/ordered_set.rs
- boa_engine/src/builtins/typed_array/integer_indexed_object.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/error.rs
- boa_engine/src/job.rs
- boa_engine/src/lib.rs
- boa_engine/src/module/mod.rs
- boa_engine/src/object/builtins/jsfunction.rs
- boa_engine/src/object/jsobject.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/object/shape/mod.rs
- boa_engine/src/object/shape/root_shape.rs
- boa_engine/src/object/shape/shared_shape/mod.rs
- boa_engine/src/property/mod.rs
- boa_engine/src/realm.rs
- boa_engine/src/script.rs
- boa_engine/src/value/display.rs
- boa_engine/src/value/equality.rs
- boa_engine/src/value/mod.rs
- boa_engine/src/value/type.rs
- boa_engine/src/vm/call_frame/mod.rs
Following up to re-enable `must_use` clippy rule for boa_engine which was disabled in #3109.
I gave an exception to `set_prototype` because it returns false when it's not extensible but there are some code already checking if it's extensible, so they don't need to check the return value, and it looks like that's a common pattern.
> Re-enable must_use clippy rule

- boa_engine/src/bytecompiler/declaration/declaration_pattern.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/control_flow/throw.rs
- boa_engine/src/vm/opcode/mod.rs
Depends on #3059, which makes it much easier to implement this :)
This was causing some tests to fail in array destructuring assignment.
~~Blocked until #3059 is merged!~~
> Close iterator after generator return call while array destructuring assignment

- boa_engine/src/builtins/string/mod.rs
- test_ignore.toml
- Implement `String.prototype.isWellFormed` and `String.prototype.toWellFormed`
> Implement `String.prototype.isWellFormed` and `String.prototype.toWellFormed`

- README.md
There were certain installation steps missing in the ReadMe file, which I added in order to get it corrected.
> Clarify usage section in `README.md`

- boa_engine/src/builtins/array/mod.rs
- boa_engine/src/builtins/typed_array/mod.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/object/internal_methods/integer_indexed.rs
- boa_engine/src/object/internal_methods/mod.rs
This Pull Request fixes the remaining TypedArray bugs.
- Use the same object for `Array.prototype.toString` and `TypedArray.prototype.toString`.
- Refactor `SetTypedArrayFromArrayLike` to conform to the spec.
- Refactor `TypedArray.prototype.sort` to conform to the spec.
- Add a `U64OrPositiveInfinity` enum to remove some unreachable branches in `TypedArray.prototype.set`.
- Implement `TypedArray.prototype.toLocaleString`.
> Fix remaining TypedArray bugs

- boa_runtime/src/console/mod.rs
This Pull Request fixes boa_runtime console.trace not printing the trace if no argument is given.
- Change the if statement scope in the trace function of Console
> Log traces even without message (boa_runtime)

- Cargo.lock
- boa_engine/src/builtins/weak_set/mod.rs
- boa_gc/Cargo.toml
- boa_gc/src/internals/ephemeron_box.rs
- boa_gc/src/internals/weak_map_box.rs
- boa_gc/src/lib.rs
- boa_gc/src/pointers/ephemeron.rs
- boa_gc/src/pointers/mod.rs
- boa_gc/src/pointers/weak.rs
- boa_gc/src/pointers/weak_map.rs
- boa_gc/src/test/mod.rs
- boa_gc/src/test/weak.rs
This Pull Request fixes #2596 and fixes #2732.
- Implements an ephemeron-based weak map using the `hashbrown` raw API.
I only exposed `WeakMap` as public, but it would be good to decide in the future if we want to expose the full `RawWeakMap` to our users.
~Marking as draft since this just needs documentation and a clippy run, but it's feature complete.~
> Implement ephemeron-based weak map

- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/declaration/declaration_pattern.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/expression/assign.rs
- boa_engine/src/bytecompiler/expression/binary.rs
- boa_engine/src/bytecompiler/expression/mod.rs
- boa_engine/src/bytecompiler/expression/object_literal.rs
- boa_engine/src/bytecompiler/expression/unary.rs
- boa_engine/src/bytecompiler/expression/update.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/module.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/bytecompiler/utils.rs
- boa_engine/src/module/source.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/numbers.rs
This PR adds the `Operand` enum (which represents an instruction operand), and makes `ByteCompiler::emit` take an array of `Operand`s instead of `u32` which allows to emit varying length operands more easily.
> Improve bytecompiler bytecode generation.

- boa_interner/src/tests.rs
This Pull Request fixes/closes #2337 
Added two new functions to test `Interner::default();` & `Interner::with_capacity;`
Requesting for review
> Added examples

- boa_parser/src/parser/statement/declaration/lexical.rs
- boa_parser/src/parser/statement/declaration/tests.rs
This Pull Request fixes/closes #3206.
- Add early errors for `LexicalDeclaration`
> Add early errors for `LexicalDeclaration`

- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/statement/try.rs
This Pull Request fixes the remaining "language/statements/switch" tests with exception of the tco tests.
This removes the current behaviour of setting the return value to `undefined` whenever there is a  `break` or `continue` statement at the start of a block. This was causing the return value to be unexpectedly overwritten in switch statements.
Instead this is now only implemented for `catch` and `finally` blocks where this behaviour mirrors the `UpdateEmpty` statements in the spec.
> Fix switch statement `break` and `continue` return values

- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/vm/call_frame/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/control_flow/jump.rs
- boa_engine/src/vm/opcode/mod.rs
This PR adds a fat enum that represents a full instruction (opcode + operands) and an iterator that takes bytecode and produces instructions.
I implemented something like this in #3037, this PR just extracts and refines it.
Why is this useful/needed?
- It allows us to iterate over instructions without worrying, whether we are reading the operands correctly. Currently we do the same thing in `instruction_operands()` and flowgraph generation, this is duplicate code and can easily lead to mistakes (also doing it in #3037 )
- Extracting the operands is harder when manually accessing bytecode.
- If we have a list of instructions it's easier to do changes in it.
Note: This is not intended to replace the compact bytecode representation, that is optimized for execution and storage.
... This also …
> Add `Instruction` and `InstructionIterator`

- test262/index.html
- test262/results.js
Related to #3273.
This PR adds a new `ES14` option to our version selector.
Had to also update the versions of the ESNext tests from 14 to 255, since ESNext is represented by `u8::MAX`. This is the cause of the big diffs on `main/latest.json` and `v0.17/latest.json`.
Since this'll probably break CI until #3273 is merged, we should wait until that PR is approved so that we can merge both consecutively.
> Update conformance page to ES14

- boa_tester/src/edition.rs
- boa_tester/src/main.rs
Depends on #3274.
This needs to be merged after the conformance webpage PR is merged, ~which I'll link here when I finish it~ which is linked above.
> Add ECMAScript 14 to `boa_tester`

- boa_engine/src/builtins/array/mod.rs
- boa_engine/src/builtins/async_function/mod.rs
- boa_engine/src/builtins/async_generator_function/mod.rs
- boa_engine/src/builtins/error/aggregate.rs
- boa_engine/src/builtins/error/eval.rs
- boa_engine/src/builtins/error/mod.rs
- boa_engine/src/builtins/error/range.rs
- boa_engine/src/builtins/error/reference.rs
- boa_engine/src/builtins/error/syntax.rs
- boa_engine/src/builtins/error/type.rs
- boa_engine/src/builtins/error/uri.rs
- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/generator/mod.rs
- boa_engine/src/builtins/generator_function/mod.rs
- boa_engine/src/builtins/intl/collator/mod.rs
- boa_engine/src/builtins/intl/date_time_format.rs
- boa_engine/src/builtins/json/mod.rs
- boa_engine/src/builtins/object/mod.rs
- boa_engine/src/builtins/regexp/mod.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/job.rs
- boa_engine/src/module/source.rs
- boa_engine/src/script.rs
- boa_engine/src/vm/call_frame/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/call/mod.rs
- boa_engine/src/vm/opcode/generator/mod.rs
- boa_engine/src/vm/opcode/meta/mod.rs
~~Depends on #3185~~
Part of refactoring calling in VM. In this PR active runnable and active function are moved in the `CallFrame`, this allows us to untangle some of the function calling.
It may seem like we are using more memory per ordinary function call, because of CallFrame size increase, but it actuality it's the same, before instead of storing it in the call frame we would spill it on the native rust stack which was filling the stack, contributing to smaller recursion limits.
@nekevss As I see it we already have the execution context stack, that being the `CallFrame`s (just a different name), we just have some work moving some fields that are supposed to be in  an execution context like `[[ScriptOrModule]]` which this PR does, realm needs to be moved too.
> Store active runnable and active function in `CallFrame`

- Cargo.toml
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/opcode/mod.rs
Just to ensure our repo correctly reports our MSRV for users that want to use the `main` branch.
> Bump `rust-version` to 1.71

- .gitignore
- .gitmodules
- boa_tester/src/main.rs
- boa_tester/src/results.rs
- test262_config.toml
This Pull Request fixes/closes #3095 .
This PR makes the downloads the `test262` repository, if we run the `boa_tester` with `run` command and we do not specify the test262 directory.
There is a con with this approach, dependabot can't suggest a updates. We could implement our own checker though.
TODO:
> Lazily download `test262`  repository

- boa_gc/src/internals/ephemeron_box.rs
- boa_gc/src/pointers/ephemeron.rs
- boa_gc/src/pointers/gc.rs
- boa_gc/src/pointers/weak.rs
This is just the corresponding replacement for the [`Rc::new_cyclic`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.new_cyclic) method, which showed to be useful while I was trying to improve some patterns in our modules implementation.
> Implement `Gc::new_cyclic`

- .github/workflows/rust.yml
- Cargo.toml
This Pull Request is a follow-up of #3290.
It adds a test for the MSRV to the CI, so that we don't get similar issues in the future.
> Added MSRV check

- Cargo.lock
- boa_engine/Cargo.toml
- boa_engine/src/builtins/intl/collator/mod.rs
- boa_engine/src/builtins/intl/collator/options.rs
- boa_engine/src/builtins/intl/date_time_format.rs
- boa_engine/src/builtins/intl/list_format/mod.rs
- boa_engine/src/builtins/intl/list_format/options.rs
- boa_engine/src/builtins/intl/locale/mod.rs
- boa_engine/src/builtins/intl/locale/options.rs
- boa_engine/src/builtins/intl/locale/utils.rs
- boa_engine/src/builtins/intl/mod.rs
- boa_engine/src/builtins/intl/number_format/mod.rs
- boa_engine/src/builtins/intl/number_format/options.rs
- boa_engine/src/builtins/intl/number_format/utils.rs
- boa_engine/src/builtins/intl/options.rs
- boa_engine/src/builtins/intl/plural_rules/mod.rs
- boa_engine/src/builtins/intl/plural_rules/options.rs
- boa_engine/src/builtins/intl/segmenter/mod.rs
- boa_engine/src/builtins/intl/segmenter/options.rs
- boa_engine/src/builtins/mod.rs
- boa_engine/src/builtins/options.rs
- boa_engine/src/context/icu.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/object/mod.rs
- test262_config.toml
This Pull Request implements the [`Intl.PluralRules`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules) service. It also implements some number formatting tools that will be useful when we eventually implement `Intl.NumberFormat`.
[`Intl.PluralRules.prototype.selectRange`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/selectRange) needs support from ICU4X first, but I'm in charge of it and I'll try to finish it soon™. You can track its progress on https://github.com/unicode-org/icu4x/issues/3012.
> Implement `Intl.PluralRules`

- boa_engine/src/bytecompiler/expression/mod.rs
- boa_engine/src/bytecompiler/mod.rs
In strict mode `this` should be undefined.
Causing test262 test to fail: [`test/language/expressions/tagged-template/call-expression-context-strict.js`](https://github.com/tc39/test262/blob/main/test/language/expressions/tagged-template/call-expression-context-strict.js)
Additionally this remove the unneeded `swap` opcode when calling functions.
> Fix tagged template `this` in strict mode

- boa_engine/src/builtins/generator/mod.rs
- compile error:
```text
error: `&` without an explicit lifetime name cannot be used here
   --> boa_engine/src/builtins/generator/mod.rs:175:17
    |
175 |     const NAME: &str = "Generator";
    |                 ^
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
note: the lint level is defined here
   --> boa_engine/src/lib.rs:59:5
    |
59  |     future_incompatible,
    |     ^^^^^^^^^^^^^^^^^^^
    = note: `#[deny(elided_lifetimes_in_associated_constant)]` implied by `#[deny(future_incompatible)]`
help: use the `'static` …
```
> fix: add 'static lifetime

- .github/workflows/rust.yml
- .github/workflows/webassembly.yml
- boa_ast/src/lib.rs
- boa_cli/src/main.rs
- boa_engine/src/lib.rs
- boa_gc/src/lib.rs
- boa_icu_provider/src/lib.rs
- boa_interner/src/lib.rs
- boa_macros/src/lib.rs
- boa_parser/src/lib.rs
- boa_profiler/src/lib.rs
- boa_runtime/src/lib.rs
- boa_tester/src/main.rs
- boa_wasm/src/lib.rs
See https://rust-unofficial.github.io/patterns/anti_patterns/deny-warnings.html for context.
This also improves a bit the prototyping experience, since now we can compile and run with warnings even if there are missing docs or suboptimal code patterns.
> Replace #[deny] with #[warn]

- .github/workflows/release.yml
This Pull Request adds back the publish action deleted on #3118/#3119.
> Reintroduce publish CI job

- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/class/mod.rs
- boa_engine/src/vm/opcode/set/class_prototype.rs
Fixes class inheritance from `null`, which was causing this test262 test to fail: [test/language/statements/class/subclass/class-definition-null-proto-this.js](https://github.com/tc39/test262/blob/main/test/language/statements/class/subclass/class-definition-null-proto-this.js)
> Fix class inherit from `null`

- Cargo.lock
- Cargo.toml
- boa_ast/Cargo.toml
- boa_cli/Cargo.toml
- boa_engine/Cargo.toml
- boa_gc/Cargo.toml
- boa_icu_provider/Cargo.toml
- boa_interner/Cargo.toml
- boa_parser/Cargo.toml
- boa_profiler/Cargo.toml
- boa_runtime/Cargo.toml
- boa_tester/Cargo.toml
- boa_tester/src/exec/mod.rs
- boa_tester/src/main.rs
- boa_tester/src/read.rs
- boa_tester/src/results.rs
- boa_wasm/Cargo.toml
Since we have so many duplicate dependencies between crates, we can use workspace dependencies to sync versions between them.
> Migrate to workspace deps

- boa_cli/src/debug/limits.rs
- boa_cli/src/debug/optimizer.rs
- boa_engine/src/builtins/async_generator/mod.rs
- boa_engine/src/builtins/function/tests.rs
- boa_engine/src/builtins/intl/collator/mod.rs
- boa_engine/src/builtins/iterable/async_from_sync_iterator.rs
- boa_engine/src/builtins/object/mod.rs
- boa_engine/src/builtins/promise/mod.rs
- boa_engine/src/builtins/proxy/mod.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/host_defined.rs
- boa_engine/src/job.rs
- boa_engine/src/lib.rs
- boa_engine/src/module/mod.rs
- boa_engine/src/module/source.rs
- boa_engine/src/object/builtins/jspromise.rs
- boa_engine/src/object/builtins/jsproxy.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/realm.rs
- boa_engine/src/value/conversions/try_from_js.rs
- boa_engine/src/vm/opcode/await/mod.rs
- boa_engine/src/vm/opcode/call/mod.rs
- boa_examples/src/bin/closures.rs
- boa_examples/src/bin/host_defined.rs
- boa_examples/src/bin/jsarray.rs
- boa_examples/src/bin/jstypedarray.rs
- boa_examples/src/bin/modules.rs
- boa_gc/src/trace.rs
- boa_tester/src/exec/mod.rs
- Add `[[HostDefined]]` field to `Realm`s
- Add example.
- Make `FunctionObjectBuilder` take a `Realm` instead of `Context`
> Implement `[[HostDefined]]` field on `Realm`s

- boa_ast/src/statement/switch.rs
- boa_cli/src/main.rs
- boa_engine/src/context/hooks.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/error.rs
- boa_engine/src/job.rs
- boa_engine/src/lib.rs
- boa_engine/src/module/mod.rs
- boa_engine/src/object/builtins/jsdataview.rs
- boa_engine/src/object/builtins/jsdate.rs
- boa_engine/src/object/builtins/jspromise.rs
- boa_engine/src/object/builtins/jsregexp.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/string/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_gc/src/lib.rs
- boa_interner/src/lib.rs
- boa_macros/src/lib.rs
- boa_parser/src/lib.rs
- boa_parser/src/parser/cursor/buffered_lexer/tests.rs
- boa_profiler/src/lib.rs
- boa_runtime/src/lib.rs
- boa_tester/src/main.rs
- boa_wasm/src/lib.rs
Uses `cargo +nightly fmt -- --config=format_code_in_doc_comments=true --config=doc_comment_code_block_width=80` to format all docs with code blocks.
> Format code snippets in docs

- .github/workflows/rust.yml
- boa_cli/Cargo.toml
- boa_engine/Cargo.toml
- boa_engine/src/builtins/promise/mod.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/vm/code_block.rs
- boa_tester/Cargo.toml
- boa_wasm/Cargo.toml
- test262_config.toml
Related to #3277
Since the Temporal PR is as big as it gets, I thought it would be good to introduce the experimental flag in a separate PR, which should reduce the review work a bit.
This also introduces the [`Promise.withResolvers`](https://github.com/tc39/proposal-promise-with-resolvers) method, just so that there's at least some feature using the flag.
> Introduce experimental features

- .github/workflows/rust.yml
- Cargo.toml
Currently there are errors when trying to run compile or run tests in `boa_parser` without the `compiled_data` feature. So just enabling the feature flag.
> `icu_properties` default features to true

- boa_parser/src/parser/expression/assignment/mod.rs
- Fix anonymous function name in cover assignment
> Fix anonymous function name in cover assignment

- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/object/for_in_iterator.rs
- boa_engine/src/builtins/object/mod.rs
- boa_engine/src/object/internal_methods/arguments.rs
- boa_engine/src/object/internal_methods/array.rs
- boa_engine/src/object/internal_methods/integer_indexed.rs
- boa_engine/src/object/internal_methods/module_namespace.rs
- boa_engine/src/object/internal_methods/string.rs
- boa_engine/src/object/operations.rs
- boa_engine/src/object/property_map.rs
- boa_engine/src/property/mod.rs
- boa_engine/src/property/nonmaxu32.rs
- boa_engine/src/value/conversions/serde_json.rs
- boa_engine/src/value/display.rs
- boa_engine/src/vm/opcode/get/property.rs
- boa_engine/src/vm/opcode/set/property.rs
This Pull Request supersedes #2131
- Add a `NonMaxU32` that is used as the integer variant for `PropertyKey`.
> Add `NonMaxU32` as integer variant for `PropertyKey`

- boa_engine/src/bytecompiler/class.rs
This Pull Request  changes the following:
- Add missing class name binding
> Add missing class name binding

- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/tests.rs
When an native error is thrown and not caught it only truncates the value stack, the environment stack is not changed this causes panics if we run code than access the environment.
For example
```js
with (new Proxy({}, {has: p => false})) {a}
```
Running this code twice causes a panic (`boa file.js file.js`).
```
panicked at 'environment must be declarative', boa_engine/src/vm/opcode/define/mod.rs:114:33
```
> Truncate environment stack on non-caught native error

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- boa_ast/Cargo.toml
- boa_cli/src/main.rs
- boa_engine/Cargo.toml
- boa_engine/src/vm/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_examples/Cargo.toml
- boa_examples/src/bin/commuter_visitor.rs
- boa_examples/src/bin/jsdate.rs
- boa_examples/src/bin/loadfile.rs
- boa_examples/src/bin/modulehandler.rs
- boa_examples/src/bin/modules.rs
- boa_examples/src/bin/runtime_limits.rs
- boa_examples/src/bin/symbol_visitor.rs
- boa_interner/Cargo.toml
- boa_runtime/src/console/mod.rs
- fuzz/Cargo.lock
Just some small improvements in our CI to ensure we're testing everything.
One unfortunate thing I realized is that `cargo clippy -- -D warnings` apparently doesn't work with our current setup, somehow. I _think_ clippy is interpreting our crate global warns as overriding the command argument `-D warnings`, but it seems that this was fixed on https://github.com/rust-lang/rust-clippy/issues/5749. Maybe the bug reappeared for workspaces?
Anyways, I confirmed that the warnings do error with the [new `[lints]` section for `Cargo.toml`](https://github.com/rust-lang/rfcs/pull/3389), so this should be fixed when Rustc 1.74 releases. I'll probably open a new draft PR for that, just to have a reminder to merge the changes at that time. In the meantime, let's just ensure we check the actions for …
> Improve CI testing

- boa_ast/src/expression/mod.rs
- boa_ast/src/expression/regexp.rs
- boa_ast/src/visitor.rs
- boa_engine/src/builtins/regexp/tests.rs
- boa_engine/src/bytecompiler/expression/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/literal.rs
- boa_parser/src/parser/expression/primary/mod.rs
- boa_parser/src/parser/expression/tests.rs
The previous implementation used the global `RegExp`, which caused errors when the `RegExp` was overwritten.
> Fix regular expression construction

- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/environments/compile.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/environment.rs
- boa_engine/src/vm/tests.rs
Fixes the class `super()` construction error thrown when the derived class has default parameters.
For example (used as a test case):
```JavaScript
class Person {
constructor(name) {
this.name = name;
}
}
class Student extends Person {
constructor(name = 'unknown') {
super(name);
}
}
new Student() // Throws an error that this is not initialized.
```
This PR breaks two test262 tests:
```
test/language/eval-code/direct/arrow-fn-body-cntns-arguments-func-decl-arrow-func-declare-arguments-assign-incl-def-param-arrow-arguments.js
test/language/eval-code/direct/arrow-fn-body-cntns-arguments-var-bind-arrow-func-declare-arguments-assign-incl-def-param-arrow-arguments.js
```
But I _think_ this is due to the following steps that we haven't implement in …
> Fix `super()` construction with default parameters

- boa_cli/src/debug/function.rs
- boa_engine/src/builtins/error/type.rs
- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/mod.rs
- boa_engine/src/builtins/regexp/tests.rs
- boa_engine/src/object/builtins/jsfunction.rs
- boa_engine/src/object/internal_methods/bound_function.rs
- boa_engine/src/object/internal_methods/function.rs
- boa_engine/src/object/internal_methods/mod.rs
- boa_engine/src/object/internal_methods/proxy.rs
- boa_engine/src/object/jsobject.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/object/operations.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/opcode/call/mod.rs
This PR separates the native function from JavaScript function, their internal methods and their storage.
This allows us to remove some unneeded check as well as makes #3295 easier to implement.
> Refactor function internal methods

- boa_engine/src/bytecompiler/class.rs
- Fix the evaluation oder of static class fields and static class blocks.
> Fix static class element evaluation order

- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/define/class/getter.rs
- boa_engine/src/vm/opcode/define/class/method.rs
- boa_engine/src/vm/opcode/define/class/setter.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/class/field.rs
- boa_engine/src/vm/opcode/push/class/private.rs
- boa_engine/src/vm/opcode/set/home_object.rs
- boa_engine/src/vm/opcode/set/private.rs
Building on #3328 this removes a bunch of unneeded class environments that where more of a hack to get the class name binding in some places. This also enables removing the `class_object` from `FunctionKind`.
> Remove unused class environments

- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/statement/block.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/bytecompiler/statement/try.rs
- boa_engine/src/bytecompiler/statement/with.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/push/environment.rs
Depends on #3332 
Makes environment push opcodes that take index use varying operands, this required a bit of a refactor so we store environments pushed starting at zero, not in reversed order.
> Make environments opcodes use varying operands

- boa_engine/src/builtins/intl/collator/mod.rs
- boa_engine/src/builtins/intl/list_format/mod.rs
- boa_engine/src/builtins/intl/locale/mod.rs
- boa_engine/src/builtins/intl/locale/options.rs
- boa_engine/src/builtins/intl/locale/utils.rs
- boa_engine/src/builtins/intl/number_format/utils.rs
- boa_engine/src/builtins/intl/plural_rules/mod.rs
- boa_engine/src/builtins/intl/segmenter/mod.rs
- boa_engine/src/builtins/options.rs
I saw that #3277 provided better error messages when an option is required, instead of our current method of returning a generic error when `required == true`. Seeing this, I think it's just better to move that check to the caller and handle the `None` case by either throwing or setting a default.
This also removes some type annotations that aren't required.
> Cleanup `get_option` and calls to the function

- Cargo.lock
- boa_engine/Cargo.toml
- boa_engine/src/builtins/number/mod.rs
- boa_engine/src/builtins/number/tests.rs
This Pull Request fixes/closes #2609 .
This depends on the implementation of `Number.prototype.toFixed()` on https://github.com/boa-dev/ryu-js/pull/35.
Added the tests about the rounding (which test262 does not check) on `ryu-js` and here just in case :)
> Fix `Number.prototype.toFixed()`

- boa_ast/src/lib.rs
- boa_cli/src/main.rs
- boa_engine/src/builtins/string/mod.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/lib.rs
- boa_engine/src/string/mod.rs
- boa_engine/src/symbol.rs
- boa_engine/src/value/conversions/mod.rs
- boa_engine/src/value/operations.rs
- boa_gc/src/lib.rs
- boa_icu_provider/src/lib.rs
- boa_interner/src/lib.rs
- boa_macros/src/lib.rs
- boa_parser/src/error/mod.rs
- boa_parser/src/lib.rs
- boa_parser/src/parser/expression/left_hand_side/optional/mod.rs
- boa_profiler/src/lib.rs
- boa_runtime/src/lib.rs
- boa_tester/src/exec/mod.rs
- boa_tester/src/main.rs
- boa_wasm/src/lib.rs
This also removes the `clippy::nursery` lint level because it's filled with experimental lints that most of the time show warnings on false-positives.
> Fix new lints for Rust 1.73

- boa_engine/src/builtins/eval/mod.rs
- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/builtins/json/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/env.rs
- boa_engine/src/bytecompiler/expression/assign.rs
- boa_engine/src/bytecompiler/expression/unary.rs
- boa_engine/src/bytecompiler/expression/update.rs
- boa_engine/src/bytecompiler/function.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/bytecompiler/module.rs
- boa_engine/src/bytecompiler/statement/block.rs
- boa_engine/src/bytecompiler/statement/loop.rs
- boa_engine/src/bytecompiler/statement/switch.rs
- boa_engine/src/bytecompiler/statement/try.rs
- boa_engine/src/bytecompiler/statement/with.rs
- boa_engine/src/environments/compile.rs
- boa_engine/src/environments/runtime/declarative/mod.rs
- boa_engine/src/environments/runtime/mod.rs
- boa_engine/src/module/source.rs
- boa_engine/src/script.rs
- boa_engine/src/vm/opcode/define/mod.rs
- boa_engine/src/vm/opcode/mod.rs
- Refactor compile time environment handling.
- Align compile time environment handling with the spec.
- Remove useless modifications to `ByteCompiler` before the `ByteCompiler::finish()`.
- Simplify compile time environment methods and remove duplicates.
- Fix some bugs with declarations in `eval` calls.
> Refactor compile time environment handling

- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/object/mod.rs
The remaining failing test262 test [`test/built-ins/Function/prototype/toString/method-computed-property-name.js`][test] is failing due to step 2 not being implemented. We fallback to native function to string representation.
[test]: https://github.com/tc39/test262/blob/f0c16faee2afe3cfe4d6e42aff743964e4ea9122/test/built-ins/Function/prototype/toString/method-computed-property-name.js
> Fix `Function.prototype.toString()`

- boa_engine/src/vm/opcode/call/mod.rs
Fixes failing test262 test [`test/language/expressions/call/eval-realm-indirect.js`](https://github.com/tc39/test262/blob/f0c16faee2afe3cfe4d6e42aff743964e4ea9122/test/language/expressions/call/eval-realm-indirect.js)
> Check `eval` realm before call

- boa_ast/Cargo.toml
- boa_ast/src/lib.rs
- boa_engine/Cargo.toml
- boa_engine/src/bigint.rs
- boa_engine/src/builtins/mod.rs
- boa_engine/src/builtins/temporal/mod.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/object/jsobject.rs
- boa_engine/src/object/mod.rs
- boa_parser/Cargo.toml
- boa_parser/src/lib.rs
This Pull Request addresses the feature flag discussion from #3277. 
- Adds a `temporal` and `promise-resolvers` feature flag
- Sets experimental to be dependent on the feature flags
> Update feature flags to specific feature flag

- boa_engine/src/bytecompiler/class.rs
[11.2.2 Strict Mode Code](https://tc39.es/ecma262/#sec-strict-mode-code)
- All parts of a `ClassDeclaration` or a `ClassExpression` are strict mode code.
> Evaluate all parts of `class` in strict mode

- boa_engine/src/module/mod.rs
- boa_engine/src/script.rs
This Pull Request closes #3379.
- Implements the `[[HostDefined]]` field for `Module` and `Script`
> Implement `[[HostDefined]]` for `Module` and `Script`

- boa_engine/src/lib.rs
- boa_engine/src/module/loader.rs
- boa_engine/src/module/mod.rs
- boa_engine/src/module/source.rs
- boa_engine/src/module/synthetic.rs
- boa_examples/src/bin/modules.rs
- boa_examples/src/bin/synthetic.rs
Depends on #3292.
This Pull Request closes #3224.
- Implements [Synthetic Modules](https://tc39.es/proposal-json-modules/#sec-synthetic-module-records) per the JSON modules proposal.
- Improves some patterns by using `Gc::new_cyclic`.
@HalidOdat I had to do a weird hack to be able to push the `ActiveRunnable` without a `CodeBlock` available to create a `CallFrame`. Since you're currently refactoring the VM, I didn't want to modify the definition of `CallFrame` to accommodate this special case. I could leave it as it is, of course, but would there be another way to store the `ActiveRunnable` inside the callstack without having to create a dummy `CodeBlock` in the process?
> Implement synthetic modules

- test262_config.toml
~Should probably be merged after we merge #3348.~ Not required anymore.
> Bump test262

- CONTRIBUTING.md
- boa_tester/src/main.rs
The previous implementation of `clone_test262()` was fetching the test262 repository on every run even if the commit did not change.
This also removes documentation section about `test262` submodule.
> Prevent `test262` repository update if not needed

- Cargo.lock
- boa_engine/Cargo.toml
- boa_engine/src/builtins/array_buffer/mod.rs
- boa_engine/src/builtins/array_buffer/shared.rs
- boa_engine/src/builtins/array_buffer/tests.rs
- boa_engine/src/builtins/array_buffer/utils.rs
- boa_engine/src/builtins/dataview/mod.rs
- boa_engine/src/builtins/mod.rs
- boa_engine/src/builtins/temporal/fields.rs
- boa_engine/src/builtins/typed_array/builtin.rs
- boa_engine/src/builtins/typed_array/element.rs
- boa_engine/src/builtins/typed_array/integer_indexed_object.rs
- boa_engine/src/builtins/typed_array/mod.rs
- boa_engine/src/context/hooks.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/object/builtins/jsarraybuffer.rs
- boa_engine/src/object/builtins/jsdataview.rs
- boa_engine/src/object/builtins/jssharedarraybuffer.rs
- boa_engine/src/object/builtins/jstypedarray.rs
- boa_engine/src/object/builtins/mod.rs
- boa_engine/src/object/internal_methods/function.rs
- boa_engine/src/object/internal_methods/integer_indexed.rs
- boa_engine/src/object/jsobject.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/string/common.rs
- boa_engine/src/value/mod.rs
- boa_examples/src/bin/jsarraybuffer.rs
- boa_tester/src/exec/js262.rs
- test262_config.toml
I'll follow up this PR with some others implementing Atomics, adding the missing example/example docs and adding the missing `agent` object.
> Implement `SharedArrayBuffer`

- boa_engine/src/bytecompiler/mod.rs
- Fix var declaration for deleted binding locator
> Fix var declaration for deleted binding locator

- boa_parser/src/parser/statement/declaration/hoistable/class_decl/mod.rs
- Fix await flag in class constructor
> Fix await flag in class constructor

- boa_engine/src/context/mod.rs
This Pull Request fixes/closes issue described in this [discord thread](https://discord.com/channels/595323158140158003/1152240246474412052).
- Provides a function for creating Realms with the default global bindings.
> Add `Context::create_realm`

- boa_engine/src/vm/opcode/mod.rs
- boa_engine/src/vm/opcode/modifier.rs
This reduces the `SPEND_FNS` from `6144 bytes` to `2048` + `256` for `COSTS` table. In total `2304` bytes.
> Reduce spend budget execution table size

- boa_engine/src/context/mod.rs
- boa_engine/src/error.rs
This should make it easier to interface with `anyhow` and `eyre`.
> Introduce a thread safe version of `JsError`

- boa_engine/src/lib.rs
- boa_engine/src/symbol.rs
- boa_gc/src/trace.rs
Closes #2599 
Also addresses the clippy lint that we had disabled temporarily.
> Fix compilation for targets without `AtomicU64`

- boa_engine/src/builtins/array/mod.rs
- boa_engine/src/object/property_map.rs
fixes #3402.
This optimizes it for the common case. It would be cool to see if we can somehow change the definition of `IndexedProperties` to also allow these optimizations when arrays have empty slots.
> Optimize `shift` for dense arrays

- boa_engine/src/builtins/array/mod.rs
- boa_engine/src/builtins/array/tests.rs
The documentation doesn't specify how the join function should handle cases where the array contains itself, but other engines treat it as an empty string.
```
let b = []
b[0] = b;
b[1] = b;
b[2] = b;
// expect output: ",,"
console.log(b.join(','))
```
> Fix Array.join when the array contains itself

- boa_cli/src/debug/limits.rs
- boa_engine/src/vm/runtime_limits.rs
- docs/boa_object.md
> Feature `get/set $boa.limits.stack`

- boa_engine/src/builtins/array/mod.rs
- boa_engine/src/builtins/array/tests.rs
- boa_engine/src/builtins/typed_array/builtin.rs
- boa_engine/src/builtins/typed_array/mod.rs
- boa_engine/src/object/builtins/jsarray.rs
- boa_engine/src/object/builtins/jstypedarray.rs
- boa_engine/src/object/internal_methods/integer_indexed.rs
- test262_config.toml
This pull request implements our missing `Array` and `TypedArray` methods from ES14. Specifically:
- `Array.prototype.toReversed`
- `Array.prototype.toSorted`
- `Array.prototype.toSpliced`
- `Array.prototype.with`
- `TypedArray.prototype.toReversed`
- `TypedArray.prototype.toSorted`
- `TypedArray.prototype.with`
> Implement `change-array-by-copy` methods

- .github/workflows/test262.yml
We had a couple of comments that were trying to take information from the old VM/non-VM Test262 comparisons.
One of them doesn't exist, so it was giving a warning. I renamed the other one, since we no longer have 2 implementations.
> Cleaned up a couple of Github action warnings

- dev/process.py
This removes old benchmarks (> 1 year old), and a few outliers. Should make the page load faster. I noticed some benchmarks are showing odd "21" or "17" ns results, which seems incorrect. We saw something similar in the past.
This is now updated with gh-pages, but we should update it if any further PR gets merged.
> Removed old benchmarks

- boa_engine/src/builtins/map/mod.rs
- boa_engine/src/builtins/object/mod.rs
- test262_config.toml
Two simple additions to the builtins: `Object.groupBy` and `Map.groupBy`.
> Implement the `array-grouping` proposal

- boa_ast/src/expression/regexp.rs
- boa_cli/src/main.rs
- boa_engine/src/builtins/error/type.rs
- boa_engine/src/builtins/mod.rs
- boa_engine/src/builtins/regexp/mod.rs
- boa_engine/src/context/intrinsics.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/module/mod.rs
- boa_engine/src/module/synthetic.rs
- boa_engine/src/native_function.rs
- boa_engine/src/object/builtins/jsfunction.rs
- boa_engine/src/object/builtins/jspromise.rs
- boa_engine/src/object/builtins/jsregexp.rs
- boa_engine/src/object/internal_methods/function.rs
- boa_engine/src/object/mod.rs
- boa_engine/src/object/operations.rs
- boa_examples/src/bin/modules.rs
- boa_examples/src/bin/synthetic.rs
- boa_tester/src/exec/mod.rs
This allows us to cleanup some of our `Js` method wrappers for built-ins, like `JsPromise` which I've already cleaned up in this PR.
> Disallow changing type of already created objects

- boa_engine/src/builtins/function/mod.rs
- boa_engine/src/bytecompiler/class.rs
- boa_engine/src/object/internal_methods/function.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/opcode/push/class/mod.rs
Since the `[[ConstructorKind]]` is known at compile time and it doesn't change, this moves it to `CodeBlock` in the `CodeBlockFlags` bitflags.
> Move ordinary function `[[ConstructorKind]]` to `CodeBlock`

- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/bytecompiler/mod.rs
- boa_engine/src/context/mod.rs
- boa_engine/src/object/internal_methods/function.rs
- boa_engine/src/vm/code_block.rs
- boa_engine/src/vm/flowgraph/mod.rs
- boa_engine/src/vm/opcode/arguments.rs
- boa_engine/src/vm/opcode/define/mod.rs
- boa_engine/src/vm/opcode/mod.rs
Moves creation of `arguments` object creation from function internal methods, this allows us to remove the checks for `arguments` object creation for functions that don't create it and would make #3194 easier since we can have `arguments` be moves into the stack and accessed as a fast local, instead of accessing it through environments.
While doing this I discovered a bug that happens when we create a function in `eval`, which was creating the functions and initializing the function, before the `eval` environment's `PushDeclarativeEnvironment` is executed. Fixed by delaying creation of function by adding the `CreateGlobalFunctionBinding` opcode.
> Move `arguments` object creation to bytecode

- boa_engine/src/bytecompiler/declarations.rs
- boa_engine/src/object/internal_methods/function.rs
- boa_engine/src/vm/code_block.rs
Depends on #3432 
Moves parameters environments creation to bytecode, removes checks for functions that don't need it.
> Move parameter environment creation to bytecode

- boa_engine/src/builtins/temporal/calendar/iso.rs
- boa_engine/src/builtins/temporal/calendar/mod.rs
- boa_engine/src/builtins/temporal/duration/mod.rs
- boa_engine/src/builtins/temporal/duration/record.rs
- boa_engine/src/builtins/temporal/fields.rs
- boa_engine/src/builtins/temporal/instant/mod.rs
- boa_engine/src/builtins/temporal/mod.rs
- boa_engine/src/builtins/temporal/plain_date/iso.rs
- boa_engine/src/builtins/temporal/plain_date/mod.rs
Some more work on `temporal`, in a little bit of a smaller PR 😉 
Mostly just trying to do a bit of cleanup and small cleanups/refactors with the idea of beginning to migrate some of the temporal methods and structures into their own crates.
- Updates and/or begins to update a couple of `Temporal.Duration`'s methods and abstracts to relatively recent changes to the specification.
- General nitpicky cleanups to begin isolating some Temporal APIs from Boa specifics (calendar impl's needing context)
Aside: are smaller PRs a bit more similar to this one going to be easier to manage even if they are relatively more unfinished? I'm trying to avoid the monstrosity that was the last PR.
> Temporal duration update and cleanup

- Cargo.lock
- boa_engine/Cargo.toml
- boa_engine/src/host_defined.rs
- boa_engine/src/realm.rs
- boa_examples/src/bin/host_defined.rs
- boa_gc/src/trace.rs
**Related PRs**: #3370 
Currently `HostDefined` doesn't permit you to mutably borrow two objects from the `[[HostDefined]]` field since the `FxHashMap` is wrapped under a `GcRefCell`.
This PR implements a `get_mut_many` (from `hashbrown`'s `HashMap`) method to permit accessing several `NativeObject`s using a `NativeTuple`.
Additionally, this commit takes the opportunity to provide automatic downcasting on the `insert` and `remove` methods for `[[HostDefined]]`.
> `[[HostDefined]]` Improvements

- boa_engine/src/symbol.rs
This Pull Request makes the `well_known_symbols` functions -- `boa_engine::symbol::JsSymbol::iterator() -> JsSymbol` etc -- `pub` instead of `pub(crate)`.
This is supposed to allow embedders to get hold of well-known symbols in Rust code, e.g. to implement iterable native objects, etc.
(Have I missed some better way to do this?)
> Make well_known_symbols functions pub

- boa_engine/src/builtins/regexp/mod.rs
- Update `regex.match` spec and code.
> Update `regex.match` spec and code

- boa_engine/src/class.rs
Related issue: #3314 
This PR simply fixes the currently incorrect documentation for `make_data` taking a parent constructor (`new_target`) in the `this` position _instead_ of the constructed object
> Class: Switch `make_data` parameter from `this` to `new_target`

- boa_engine/src/class.rs
- boa_engine/src/context/hooks.rs
- boa_engine/src/job.rs
- boa_engine/src/object/mod.rs
- boa_examples/src/bin/classes.rs
- boa_runtime/src/console/mod.rs
Adds some requested utilities for our `Class` trait.
> Add utility methods to the `Class` trait

- Cargo.lock
- boa_engine/Cargo.toml
- boa_engine/src/builtins/intl/collator/mod.rs
- boa_engine/src/builtins/intl/date_time_format.rs
- boa_engine/src/builtins/intl/list_format/mod.rs
- boa_engine/src/builtins/intl/locale/mod.rs
- boa_engine/src/builtins/intl/locale/utils.rs
- boa_engine/src/builtins/intl/plural_rules/mod.rs
- boa_engine/src/builtins/intl/segmenter/iterator.rs
- boa_engine/src/builtins/intl/segmenter/mod.rs
- boa_engine/src/builtins/intl/segmenter/segments.rs
- boa_engine/src/builtins/string/mod.rs
- boa_engine/src/object/mod.rs
- boa_gc/Cargo.toml
- boa_gc/src/trace.rs
Related to #3487.
This makes our `Object` implementation a lot simpler (saves us a lot of feature gates), so we should see if we can move other non-perf related objects to this.
> Transition `Intl` types to `NativeObject` API

- core/engine/src/builtins/intl/collator/mod.rs
- core/engine/src/builtins/intl/list_format/mod.rs
- core/engine/src/builtins/intl/locale/mod.rs
- core/engine/src/builtins/intl/locale/tests.rs
- core/engine/src/builtins/intl/locale/utils.rs
- core/engine/src/builtins/intl/mod.rs
- core/engine/src/builtins/intl/plural_rules/mod.rs
- core/engine/src/builtins/intl/segmenter/mod.rs
- core/engine/src/builtins/string/mod.rs
- core/engine/src/context/icu.rs
- core/engine/src/context/mod.rs
Hides `BoaProvider` to be crate-private, which makes the overall API easier for users.
> Simplify `Icu` API

- core/engine/src/builtins/function/mod.rs
- core/engine/src/builtins/generator/mod.rs
- core/engine/src/bytecompiler/mod.rs
- core/engine/src/module/synthetic.rs
- core/engine/src/vm/call_frame/mod.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/mod.rs
- core/engine/src/vm/opcode/arguments.rs
- core/engine/src/vm/opcode/await/mod.rs
- core/engine/src/vm/opcode/generator/mod.rs
- core/engine/src/vm/opcode/generator/yield_stm.rs
- core/engine/src/vm/opcode/get/argument.rs
- core/engine/src/vm/opcode/rest_parameter/mod.rs
This PR makes storing locals after `fp` much easier by moving the `fp` at the end of the stack that the caller sets up, making the frame pointer the in the middle, the locals start at fp and accessing the caller setup values we offset back instead.
This adds a local ( /register :wink: ) count variable to `CodeBlock`.
Checkout [`call_frame.rs`](https://github.com/boa-dev/boa/blob/93d7a48850cb6ffdeb8634e08f0e6fe88328141b/boa_engine/src/vm/call_frame/mod.rs#L84) for the new calling convention.
This makes #3194 easier and allows us to move stuff from the call frame that is only for a specific type of function (like `async` promise capability or generator function) reducing the size of the call frame and only paying for things the user uses.
Moves async generator object out of `CallFrame` to …
> Refactor vm calling convention to allow locals

- core/temporal/src/components/month_day.rs
- core/temporal/src/components/year_month.rs
- core/temporal/src/parser/annotations.rs
- core/temporal/src/parser/datetime.rs
- core/temporal/src/parser/duration.rs
- core/temporal/src/parser/mod.rs
- core/temporal/src/parser/tests.rs
- core/temporal/src/parser/time.rs
- core/temporal/src/parser/time_zone.rs
This PR addresses some of the issues that was causing the parser to panic when running the test suite, along with some general cleanup of the parser.
- Implements `FromStr` for `MonthDay` and `YearMonth` (also removes the ym and dm peeks)
- Attempts to clean up the general logic in the parser and adds some utility methods to the `Cursor`
- Adds a large amount of invalid `DateTime` parsing cases to the parser tests from `test262`.
> Temporal Parser Cleanup/Fixes

- core/engine/src/builtins/generator/mod.rs
- core/engine/src/builtins/promise/mod.rs
- core/engine/src/bytecompiler/mod.rs
- core/engine/src/module/source.rs
- core/engine/src/vm/call_frame/mod.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/mod.rs
- core/engine/src/vm/opcode/await/mod.rs
- core/engine/src/vm/opcode/generator/mod.rs
Depends on #3496 
Moves the promise capability to stack. Reduces call frame for non-async functions by 48 bytes.
> Move `PromiseCapability` to stack

- core/engine/src/builtins/temporal/time_zone/custom.rs
- core/engine/src/builtins/temporal/time_zone/mod.rs
- core/engine/src/builtins/temporal/zoned_date_time/mod.rs
- core/temporal/src/components/duration.rs
- core/temporal/src/components/tz.rs
- core/temporal/src/components/zoneddatetime.rs
The updates on this branch is to bring the time zone implementation in line with the design from #3522 and related to #1804.
- Changes `TimeZoneSlot` to the below
```rust
pub enum TimeZoneSlot<Z: TzProtocol> {
/// A native `TimeZone` representation.
Tz(TimeZone),
/// A Custom `TimeZone` that implements the `TzProtocol`.
Protocol(Z),
}
```
- Adds the custom time zone object (with a `Trace` impl).
Notably, as further context on the below, Time Zones right now is mostly the structure/scaffolding with limited functionality. We'll need to figure out a good way to handle tz system calls and IANA mapping (whether that be using some `icu4x` provider or baking something ourselves based from the IANA tz database) to really build this out functionality wise and test it, at …
> Update `boa_temporal` Time Zone design

- core/engine/src/vm/opcode/iteration/iterator.rs
- Fix invalid return value when closing an iterator
> Fix invalid return value when closing an iterator

- core/engine/src/builtins/date/mod.rs
- core/engine/src/builtins/date/utils.rs
This PR implements parsing in `Date()` and `Date.parse()` according to the spec.
Until now we only parsed the given string in the RFC 3339 format. The spec allows for [a more relaxed format](https://tc39.es/ecma262/#sec-date-time-string-format), for example partial formats are allowed (e.g. `2024`, `2024T00:00`, ...). While the spec allows for implementation specifc parsing it also specifies that the output of `Date.toString`, `Date.toUTCString` and `Date.toISOString` must be parsable into an equal `Date` object. These formats are now also parsed (the `Date.toISOString` format is the same that the spec defines itself).
> Implement Date parsing according to the spec

- core/temporal/src/components/date.rs
- core/temporal/src/components/duration.rs
- core/temporal/src/components/duration/date.rs
- core/temporal/src/components/duration/time.rs
- core/temporal/src/components/instant.rs
- core/temporal/src/components/mod.rs
- core/temporal/src/options.rs
This Pull Request is related to #1804.
This PR implements the abstract operation `DifferenceInstant` (`diff_instant`) on `Instant`. There was a refactor also made to `Duration` as a result.
- Separates `TimeDuration` and `DateDuration` from `Duration`.
- Adjustments to various `Duration` methods to account for the above (the most "radical" being to `round`)
> Implement `DifferenceInstant` and related refactor

- Cargo.lock
- Cargo.toml
- core/engine/Cargo.toml
- core/engine/src/builtins/date/mod.rs
- core/engine/src/builtins/date/tests.rs
- core/engine/src/builtins/date/utils.rs
- core/engine/src/context/hooks.rs
- core/engine/src/object/builtins/jsdate.rs
- core/engine/src/value/integer.rs
- core/engine/src/value/mod.rs
- examples/Cargo.toml
- examples/src/bin/jsdate.rs
- ffi/wasm/Cargo.toml
- ffi/wasm/src/lib.rs
- tests/tester/Cargo.toml
- tests/tester/src/main.rs
This pull request refactors the `Date` builtin to align it with the spec and enable all tests to pass.
The date operations by `chrono` are removed. This is necessary, because `chrono` only allows a limited date range from `Jan 1, 262145 BCE` to `Dec 31, 262143 CE`. The spec allows for dates from `-271821-04-20T00:00:00.000Z` to `+275760-09-13T00:00:00.000Z`. Instead most datetime specific operations are now performed by the functions that the spec specifies. The only thing that is done by the `time` create is the calculation of local timzone offsets. All other usages of `chrono` are also removed so we can remove the dependency.
> `Date` refactor

- core/engine/src/host_defined.rs
Small improvement to that method that avoids creating a `Vec` for indexing.
I also checked the generated assembly and it seems to skip some panics thanks to the const generic, so that's good.
> Remove allocations from `HostDefined::get_many_mut`

- core/engine/src/bigint.rs
- core/engine/src/builtins/options.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/options.rs
- core/temporal/src/components/duration.rs
- core/temporal/src/components/duration/time.rs
- core/temporal/src/components/instant.rs
- core/temporal/src/lib.rs
- core/temporal/src/options.rs
- core/temporal/src/utils.rs
This Pull Request related to ongoing work around #1804. This continues the work on migrating `Temporal` functionality in `boa_temporal`. 
- Migrates `Instant` methods `add`, `subtract`, `round`, `until`, and `since` to `boa_temporal`
- Removes and/or migrates some functions
> Temporal `Instant` migration cont. and related changes

- Cargo.lock
- core/engine/src/object/builtins/jsarraybuffer.rs
Implements `.data()` and `.data_mut()` for getting a reference to the internal byte data of `ArrayBuffer` without having to detach the buffer.
> Implement getter for `ArrayBuffer` data

- core/engine/src/builtins/regexp/mod.rs
This PR fixes the line terminator escaping in `RegExp.prototype.source`.
> Fix escaping in `RegExp.prototype.source`

- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/temporal/src/components/date.rs
- core/temporal/src/components/duration/date.rs
- core/temporal/src/iso.rs
- core/temporal/src/utils.rs
This Pull Request is related to #1804. This begins to add functionality in `boa_temporal` to the Temporal builtins (with hopefully more to come).
- Adds some methods to `Date` in `boa_temporal`.
- Implements some of the existing and pre-existing `Date` methods for the `PlainDate` builtin.
- There are some bug fixes for some tests in test262 also that were panicking.
> Temporal: Update `Date` builtin with `boa_temporal` and fixes

- core/temporal/src/components/duration.rs
- core/temporal/src/components/time.rs
- core/temporal/src/iso.rs
- core/temporal/src/options.rs
This Pull Request is related to the ongoing work on #1804. Mostly the work here is around building out more of the `Time` component and it's methods.
- Adds/fixes `Duration`'s `is_date_duration` and `is_time_duration` methods (exposes them as public too)
- Adds accessor methods to `Time` component
- Adds the `Add`, `Subtract`, and `Round` methods along with implementation details
- Some tests for the above
> Temporal: Build out `Time` and its methods

- core/engine/src/builtins/array_buffer/mod.rs
- core/engine/src/builtins/array_buffer/utils.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/object/builtins/jsarraybuffer.rs
- core/engine/src/object/builtins/jsdataview.rs
- core/engine/src/object/internal_methods/mod.rs
- core/engine/src/object/jsobject.rs
- core/engine/src/object/mod.rs
- core/gc/src/internals/ephemeron_box.rs
- core/gc/src/internals/gc_box.rs
- core/gc/src/pointers/ephemeron.rs
- core/gc/src/pointers/gc.rs
- core/gc/src/pointers/mod.rs
- examples/src/bin/jsarraybuffer.rs
This PR implements non-erased `JsObject`s aka `JsObject<T>`. This allows accessing the inner data of an object without having to call `downcast_ref/mut` every time, which is a big ergonomics win that should avoid calling `expect` a lot of times.
This is an MVP that doesn't support calling internal methods using a `JsObject<T>`; adding support for that would require a slight redesign on the API. However, the current MVP is enough to support most of the use cases of the API in our builtin wrappers.
This also uses the new API to improve the `JsArrayBuffer` wrapper on some parts, but it still needs some more work that can be done on subsequent PRs.
Thanks to @HalidOdat for [nerd-sniping me into implementing this](https://github.com/boa-dev/boa/pull/3610#discussion_r1465893269) 🤣
> Implement non-erased `JsObject`s

- core/engine/src/builtins/temporal/plain_date/mod.rs
- test262_config.toml
This PR is primarily to propose enabling the Temporal tests (with a quick fix to an error message mistake I noticed for `PlainDate`).
While there is still a decent amount of work to complete with the implementation in `boa_temporal`, everything seems to be mostly stable approach-wise at this point, I'm also hoping to start more widely plugging `boa_temporal` functionality into the engine's built-ins. Enabling the tests would ideally make reviewing easier and help to see the progress as more parts of temporal are completed and added in.
> Temporal: Enable temporal tests

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/regexp/mod.rs
- core/engine/src/builtins/regexp/tests.rs
- test262_config.toml
- Update regress to v0.8.0
- Use regress UTF16 / UCS2 matching
- Enable ignored regexp tests
> Update regress to v0.8.0 and use UTF16 / UCS2 matching

- core/engine/src/builtins/map/mod.rs
- core/engine/src/builtins/object/mod.rs
- core/engine/src/builtins/promise/mod.rs
- core/engine/src/context/intrinsics.rs
- test262_config.toml
- tests/tester/src/edition.rs
Bumps the test262 repo, cleans up our feature list and stabilizes the experimental features `promise-with-resolvers` and `array-grouping`.
> Cleanup 262 tester and stabilize some experimental features

- core/engine/src/builtins/array_buffer/mod.rs
- core/engine/src/builtins/array_buffer/shared.rs
- core/engine/src/builtins/array_buffer/utils.rs
- core/engine/src/builtins/atomics/mod.rs
- core/engine/src/builtins/dataview/mod.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/builtins/typed_array/element/mod.rs
- core/engine/src/builtins/typed_array/mod.rs
- core/engine/src/builtins/typed_array/object.rs
- core/engine/src/object/builtins/jsarraybuffer.rs
- core/engine/src/object/builtins/jsdataview.rs
- core/engine/src/object/builtins/jssharedarraybuffer.rs
- core/engine/src/object/jsobject.rs
- core/engine/src/object/mod.rs
Just a small QOL change for `DataView` using the new non-erased JsObjects.
> Improve typing of `DataView` and related objects

- .github/workflows/test262.yml
Since the 262 tests action now takes a bit longer we had multiple cases where the `git push` to the `gh-pages` branch on `main` did not work because the pulled `gh-pages` branch was outdated.
This PR attempts to solve this by moving the checkout action for the `gh-pages` branch after the running of the tests. In most cases this should solve the issue.
> Fix tests results upload

- core/engine/src/builtins/iterable/async_from_sync_iterator.rs
Implements the incoming changes of [`ecma262`'s PR #2600](https://github.com/tc39/ecma262/pull/2600)
> Close sync iterator when async wrapper yields rejection

- core/engine/src/builtins/temporal/calendar/object.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/temporal/src/components/calendar.rs
- core/temporal/src/components/date.rs
- core/temporal/src/components/datetime.rs
- core/temporal/src/components/month_day.rs
- core/temporal/src/components/year_month.rs
- core/temporal/src/components/zoneddatetime.rs
- core/temporal/src/iso.rs
- core/temporal/src/lib.rs
- core/temporal/src/parser/tests.rs
- core/temporal/src/utils.rs
This Pull Request is related to the ongoing work for #1804.
- Builds out some basic accessor functionality on `boa_temporal`'s `DateTime`.
- Implements `PlainDateTime`'s accessor properties, accounting for the above changes.
> Temporal: `DateTime` and `PlainDateTime` functionality

- core/engine/src/builtins/temporal/calendar/mod.rs
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/temporal/src/components/duration.rs
- core/temporal/src/components/duration/date.rs
- core/temporal/src/components/duration/time.rs
Primarily plugs some of the implemented `boa_temporal`'s `Time` into `PlainTime` in the 
- Adds `PlainTime` accessors and some methods
- Implements `to_temporal_duration_record`
> Temporal: Initial `PlainTime` build out

- core/engine/src/builtins/temporal/calendar/mod.rs
- core/engine/src/builtins/temporal/calendar/object.rs
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/time_zone/mod.rs
- core/engine/src/builtins/temporal/zoned_date_time/mod.rs
- core/temporal/src/components/date.rs
- core/temporal/src/components/datetime.rs
This Pull Request mainly contains some small fixes to the attribute and properties on the `Temporal` built-ins, and updates the `this` value on the custom calendar method calls.
> Temporal: attribute/property and custom calendar fixes

- core/parser/src/lexer/cursor.rs
- core/parser/src/lexer/template.rs
- core/parser/src/lexer/tests.rs
- core/parser/src/lexer/token.rs
- core/parser/src/parser/expression/left_hand_side/template.rs
- core/parser/src/parser/expression/primary/mod.rs
- core/parser/src/parser/expression/primary/template/mod.rs
This PR fixes some issues with different line terminators in templates strings.
The issues where caused by some unhandled line terminators in `raw` strings and double handling by `Cursor` of the string codepoints in the `cooked` strings.
> Fix line terminators in template strings

- core/engine/src/builtins/array/array_iterator.rs
- core/engine/src/builtins/array/mod.rs
- core/engine/src/builtins/array_buffer/mod.rs
- core/engine/src/builtins/array_buffer/shared.rs
- core/engine/src/builtins/array_buffer/tests.rs
- core/engine/src/builtins/array_buffer/utils.rs
- core/engine/src/builtins/atomics/futex.rs
- core/engine/src/builtins/atomics/mod.rs
- core/engine/src/builtins/dataview/mod.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/builtins/typed_array/mod.rs
- core/engine/src/builtins/typed_array/object.rs
- core/engine/src/context/hooks.rs
- core/engine/src/object/builtins/jsarraybuffer.rs
- core/engine/src/object/builtins/jsdataview.rs
- core/engine/src/object/builtins/jssharedarraybuffer.rs
- test262_config.toml
A bit of a complex implementation, but happy with the new design overall. Open for suggestions though!
This implements:
- Resizable array buffers.
- Allows `ArrayBuffer` to resize, but it's limited to a `maxByteLength` parameter passed at construction time.
- Allows `SharedArrayBuffer` to grow (shrinking is disallowed by the spec), also limited to a `maxByteLength` parameter.
It uses an `AtomicUsize` to track the current length, which should be enough to ensure thread-safety.
- Retrofits `Atomics`, `TypedArray` and `DataView` to use the new buffers.
- Makes `memmove`, `memcpy` and `copy_shared_to_shared` more low level, computing using pointers.
The previous design used slices to do debug assertions before copying memory, but this made the API a bit clunkier to use, and some of the …
> Implement resizable buffers

- core/engine/src/builtins/array_buffer/mod.rs
- test262_config.toml
This implements the stage 3 proposal [ArrayBuffer.prototype.transfer and friends](https://github.com/tc39/proposal-arraybuffer-transfer) behind our experimental flag. This also puts our `ArrayBuffer` suite at 100% conformance 🎉
> Implement stage 3 feature "arraybuffer-transfer"

- core/engine/src/error.rs
- core/engine/src/module/mod.rs
- core/engine/src/module/source.rs
- core/engine/src/module/synthetic.rs
- core/gc/src/trace.rs
Should improve cache locality + allows allocating the whole `Module` struct in a single Gc.
> Remove double indirection in module types

- README.md
This PR is to update the main `README.md` for `boa`.
Occasionally, we still receive issues from someone using the `Boa` crate, so this is mostly attempting to add some clarity to the main README for which crates `boa-dev` currently maintains as well as adding an initial walkthrough example for anyone who stops by the repo.
- Adds `Boa Crates` section
- Adds `Boa Engine Example`
- Adds `Documentation` section for links to both the latest release and `main`.
> Docs: Update boa's main README.md

- core/engine/src/builtins/temporal/calendar/mod.rs
- core/engine/src/builtins/temporal/calendar/object.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/tests.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoned_date_time/mod.rs
- core/temporal/src/components/calendar.rs
- core/temporal/src/components/date.rs
- core/temporal/src/components/datetime.rs
- core/temporal/src/components/month_day.rs
- core/temporal/src/components/year_month.rs
This Pull Request is related to ongoing #1804.
So a little background.
There was a [test](https://github.com/tc39/test262/blob/main/test/built-ins/Temporal/PlainDateTime/prototype/dayOfWeek/custom.js) I noticed that, in theory, we should have been passing, but weren't.
The reason we weren't was due to only passing the inner date representation through the library, and recreating the `PlainDate` once into the custom calendar impl. But this meant that we couldn't do the strict equality `compareArray` asserts.
So after some initial prototyping about an `AnyDateLike` trait. I had a sidebar with @jedel1043, and he had a good idea of using an associated trait. 😄
Let me know what you all think!
- Adds `DateLike` associated Type to `CalendarProtocol`
- Updates the API …
> Temporal: Refactor Calendar protocol for `JsObject`s

- core/engine/src/builtins/temporal/calendar/object.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/time_zone/custom.rs
- core/temporal/src/components/calendar.rs
- core/temporal/src/components/date.rs
- core/temporal/src/components/datetime.rs
- core/temporal/src/components/duration.rs
- core/temporal/src/components/duration/date.rs
- core/temporal/src/components/tz.rs
- core/temporal/src/components/zoneddatetime.rs
I'm aware that this mostly undoes some API design decisions @nekevss and I did, but I was experimenting with simplifying the API and I think I prefer the simplicity of having a single contextual low level call for all methods, instead of a contextual and a non-contextual variant. If we do want to offer a protocol free implementation, I think it would be better to just make simple wrappers around the low level types.
On the other hand, this also replaces the `Any`s with an associated type inside `CalendarProtocol` itself. This wasn't possible at the beginning because I'm pretty sure we hadn't introduced the trait when we decided to pass `Any` to all method calls.
@nekevss Let me know what you think of the changes!
> Simplify Temporal APIs

- core/engine/src/object/internal_methods/mod.rs
- core/engine/src/object/property_map.rs
- core/engine/src/object/shape/mod.rs
- core/engine/src/object/shape/shared_shape/mod.rs
- core/engine/src/object/shape/slot.rs
- core/engine/src/object/shape/unique_shape.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/inline_cache/mod.rs
- core/engine/src/vm/inline_cache/tests.rs
- core/engine/src/vm/mod.rs
- core/engine/src/vm/opcode/get/property.rs
- core/engine/src/vm/opcode/set/property.rs
- Implements some tests for internal method inline chaching
- Test object internal methods
- Test `Get` and `Set` inline caching opcodes
- Cleanup
> Implement inline caching tests and cleanup

- README.md
- cli/README.md
- cli/src/main.rs
Another small doc update with edits to `README.md` and creates a `README.md` for `boa_cli`
Changes are:
- Adds a README.md to `boa_cli` 
- Adds `boa_cli` to list of published crates in the README.md
- Wraps the example in a `main()` for consistency.
- Stacks the documentation links
I was going to try and make some gifs with `vhs`, but apparently it's bugged on Windows and WSL wasn't working either (Yet another just Windows issue 😭). Granted it could also be a good first issue for someone.
> Docs: Update README.md and add `boa_cli`'s README.md

- test262_config.toml
- tests/tester/src/exec/mod.rs
- tests/tester/src/main.rs
- tests/tester/src/results.rs
A simplified version of #3364 that only fixes the conformance representation without doing anything else. Thanks to this, it should be completely retrocompatible with previous runs.
> Consider strict + no-strict tests as a single test

- Cargo.lock
- examples/Cargo.toml
- examples/src/bin/module_fetch.rs
This should probably be adapted to offer a similar feature in our playground, but with more resilience against connection errors.
> Add example for async module fetches

- .github/workflows/release.yml
In the release workflow we did add the `.exe` suffix for Windows builds, since Windows primarily looks at the extension of the file to know what the file is.
> Preserve `.exe` suffix for Windows releases

- core/engine/src/builtins/eval/mod.rs
- core/engine/src/builtins/function/mod.rs
- core/engine/src/context/hooks.rs
- core/engine/src/object/builtins/jsarraybuffer.rs
- core/engine/src/vm/call_frame/mod.rs
PR https://github.com/tc39/ecma262/pull/3222 introduced a new `HostEnsureCanCompileStrings` that passes the body and parameters of the runtime-compiled function for additional checks.
The regressions are because the test repo hasn't been updated with the new behaviour; on the old spec,
the parameters were converted to strings before the body, which is the opposite of what the new spec states.
> Change `HostEnsureCanCompileStrings` to the new spec

- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/object/builtins/jstypedarray.rs
- examples/src/bin/jstypedarray.rs
This Pull Request pertains to issue #3252
It implements the following JsTypedArray methods:
- get buffer
- constructor
- copyWithin
- find_index
- find_last
- find_last_index
- foreach
- includes
- set
- subarray
- toLocaleString*
- toStringTag
Hi guys!
I'd like to create this draft pull request to share my work on the issue through examples and seek feedback. Is that alright with you? I'll gradually compile this post as I make progress on the issue.
> Js typed array methods

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/regexp/mod.rs
- core/parser/src/lexer/regex.rs
- test262_config.toml
This PR updates `regress` to `v0.9.0`, adding support for the `v` flag.
> Implement RegExp `v` flag

- .github/release.yml
Add a catch all for other categories not labelled
> Add a catch all for other categories not labelled

- core/engine/Cargo.toml
Fixes `temporal_rs` not being optional.
> Fix `temporal_rs` in Cargo.toml

- CHANGELOG.md
This is the PR change for the changelog for v0.18.
This was generate from the releases page which I think captures all commits which have been tagged
Rendered: https://github.com/boa-dev/boa/blob/1ef9012c8241a8be6013c61f90d4989a906b3003/CHANGELOG.md
> initial changelog for v0.18

- Cargo.toml
Our binaries are currently quite big by default. Most of it (around 65%) is due to ICU data. But there are things we can do. Before going for more drastic solutions, such as abort panic, striping the binaries helps slightly.
In this case, striping helps only slightly:
- `boa` binary: from 26 MB to 25 MB
- `boa_tester` binary: from 27 MB to 25 MB
I did some further tests by adding `panic = "abort"`, and this reduced sizes even further:
- `boa` binary: 23MB
- `boa_tester` binary: 24M
And we would lose panic unwinding, so I don't see too much benefit.
> Add release binary striping

- core/engine/src/bytecompiler/statement/loop.rs
- core/engine/src/bytecompiler/utils.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/flowgraph/mod.rs
- core/engine/src/vm/opcode/iteration/iterator.rs
- core/engine/src/vm/opcode/mod.rs
Currently the iterator used in a for-of loop is not closed when the loop body throws. This PR fixes that by widening the scope of an exception handler that was already in place for some of the for-of assignment code paths.
To make this work I had to adjust the iterator close opcodes somewhat. The reason is that we may run into a situation when we attempt to close an iterator two times. See the following example:
```javascript
var iterable = {};
iterable[Symbol.iterator] = function() {
return {
next: function() {
return { done: false, value: null };
},
return: function() {
throw "iter-close-error";
}
};
};
function f() {
for (var x of iterable) {
return;
}
}
f();
```
In this example we close the iterator when we `return` from `f` inside of the loop body. The iterator close code is injected …
> Close for-of iterator when the loop body throws

- core/ast/src/expression/literal/array.rs
- core/ast/src/pattern.rs
- core/engine/src/bytecompiler/declaration/declaration_pattern.rs
- Add default value handling for destructuring property access arrays
> Add default value handling for destructuring property access arrays

- .github/workflows/release.yml
This PR adds a release workflow to publish NPM packages on each release in an autonomous way.
> Added NPM publish workflow

- core/parser/src/parser/statement/declaration/lexical.rs
- core/parser/src/parser/statement/declaration/mod.rs
- core/parser/src/parser/statement/iteration/for_statement.rs
- core/parser/src/parser/statement/mod.rs
This allows `let` as a variable name in some more places.
> Fix invalid syntax errors for allowed `let` as variable names

- core/parser/src/parser/expression/assignment/mod.rs
- core/parser/src/parser/expression/tests.rs
- core/parser/src/parser/statement/iteration/for_statement.rs
This PR fixes a syntax error in for-of loops.
Currently the lookahead for the pattern `async of` in a for-of loop errors also in normal for loops. In a normal for loop this pattern might also be an async arrow function. To fix this I also had to fix the parsing of async arrow functions to allow `of` as a binding identifier. I added a test for that, since there seems to be no 262 test.
> Fix parsing of `async` in for-of loops

- core/parser/src/parser/statement/try_stm/catch.rs
- Fix parsing of binding identifier in try catch parameters
> Fix parsing of binding identifier in try catch parameters

- core/engine/src/value/conversions/try_from_js.rs
This PR adds an implementation of `TryFromJs` for `Vec<T: TryFromJs>` to create Rust vectors from Array-like JavaScript objects.
This is useful when using typed arguments to native functions with arrays.
> Add a try_from_js implementation for Vec<T> (accept any Array-like)

- cli/src/debug/object.rs
- core/engine/src/builtins/array/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/object/property_map.rs
- core/engine/src/object/shape/shared_shape/template.rs
- core/engine/src/value/mod.rs
- core/engine/src/vm/opcode/call/mod.rs
- core/engine/src/vm/opcode/environment/mod.rs
- core/engine/src/vm/opcode/get/property.rs
- core/engine/src/vm/opcode/new/mod.rs
- core/engine/src/vm/opcode/set/property.rs
- docs/boa_object.md
This PR adds dense variants for array storage (`i32` and `f64`) this is mostly a memory optimization, this optimization is also implemented by v8 (they have even more granular types like sparse `i32` and `f64` variants).
Storing number `i32` numbers in a dense array now takes `6x` less memory and `3x` less memory for `f64` (since `JsValue` is 24 bytes)
This PR also applies the changes in #3744 , because with this PR it complicates that fast path too much. Since the patch introduces a regression for setting new properties in arrays,  this PR amortizes the regression, it's pretty much the same with the current performance in quickjs benchmarks.
Even though I implemented that fast path, I was never happy with it :sweat_smile: (because it has too much duplicate logic), it was a quick way to …
> Dense array storage variants for `i32` and `f64`

- core/engine/src/builtins/array/mod.rs
- core/engine/src/builtins/builder.rs
- core/engine/src/builtins/error/type.rs
- core/engine/src/builtins/function/mod.rs
- core/engine/src/builtins/string/mod.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/object/mod.rs
- core/engine/src/object/operations.rs
- core/engine/src/property/mod.rs
- core/engine/src/string/common.rs
- core/engine/src/vm/opcode/push/array.rs
In previous implementation when converting a number to `PropertyKey`, we always converted it to string and only when the conversion to `PropertyKey::Index` was not possible we returned that string.
Instead of using `map_or` which expects a ready value we use the `_else` version that takes a function. Also took the oportunity to optimize the `i32` to `PropertyKey` conversion, since it's the one that's called when we convert from `JsValue::Integer`. Additionaly added a static string for `"length"` for internal array methods so we don't convert from `&[u16]` to `PropertyKey`.
Because the conversion happens very often this change resulted in big performance improvements :)
```
RESULT Richards 57.0
RESULT DeltaBlue 61.6 …
```
> Optimize number to `PropertyKey` conversion

- core/engine/src/builtins/function/mod.rs
- core/engine/src/vm/call_frame/mod.rs
- core/engine/src/vm/opcode/control_flow/return.rs
- core/engine/src/vm/opcode/environment/mod.rs
The value of `this` when `this` is used in a function does not change after the initial environment chain search, so now we cache this value. This prevents the `this` value from being searched in the environment chain on every `this` usage.
There is a small increase in performance, the functions that use `this` a lot are the ones that benefit from this optimization.
```
RESULT Richards 58.0
RESULT DeltaBlue 63.9
RESULT Crypto 69.9
PROGRESS RayTrace
RESULT RayTrace 198
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 181
PROGRESS Splay
RESULT Splay 192
PROGRESS NavierStokes
RESULT NavierStokes 150
SCORE 115
```
```
RESULT Richards 60.7
RESULT DeltaBlue 65.0
PROGRESS …
```
> Cache `this` value

- .github/workflows/test262.yml
- tests/tester/src/results.rs
This PR relies on https://github.com/boa-dev/boa-dev.github.io/pull/145 being merged first.
Essentially this stops adding test262 data to the gh-pages branch on each push to main.
Instead we will rely on the nightly which runs from the data repo instead, this will help remove a lot of data from this repository
> don't run test262 on push 

- core/engine/src/value/integer.rs
Fixes #3697.
We should assert that `min <= max` even if `self` is `PositiveInfinity` or `NegativeInfinity`.
> Check that `min <= max` in `clamp_finite`

- Cargo.lock
- core/gc/src/trace.rs
- core/interop/ABOUT.md
- core/interop/Cargo.toml
- core/interop/src/lib.rs
- core/interop/src/loaders.rs
- core/interop/src/loaders/hashmap.rs
This crate will contain types and functions to help integrating boa in Rust projects, making it easier to interop between the host and the JavaScript code.
See https://github.com/boa-dev/boa/discussions/3770
> Add a boa_interop crate

- core/engine/src/module/loader.rs
- core/engine/src/module/mod.rs
- core/engine/tests/assets/dir1/file1_1.js
- core/engine/tests/assets/dir1/file1_2.js
- core/engine/tests/assets/file1.js
- core/engine/tests/imports.rs
- core/interop/src/lib.rs
- core/parser/src/source/mod.rs
- examples/src/bin/synthetic.rs
This allows `SimpleModuleLoader` (and other loaders) to resolve relative to the current file (which this commit also does).
Fixes #3782
Closes #3781
> Add a path to Module (and expose it in Referrer)

- .vscode/launch.json
- .vscode/tasks.json
- Cargo.lock
- core/engine/Cargo.toml
- core/engine/src/context/mod.rs
- core/engine/src/module/loader.rs
- core/engine/src/script.rs
- core/engine/src/vm/mod.rs
- core/engine/tests/imports.rs
- tests/tester/src/main.rs
- tests/tester/src/read.rs
We do have the path in parsed `Script` (if the `Source` has it), so use that if we can.
Fixes #3790.
> Properly resolve paths in SimpleModuleLoader and add path to Referrer::Script

- Cargo.lock
- core/engine/src/lib.rs
- core/engine/src/module/loader.rs
- test262_config.toml
- tests/tester/Cargo.toml
- tests/tester/src/edition.rs
- tests/tester/src/exec/js262.rs
- tests/tester/src/exec/mod.rs
- tests/tester/src/main.rs
- tests/tester/src/read.rs
Just some refactorings to our tester. Also removes the `regex` and `once_cell` dependencies from it.
Additionally, this also reexports our most important crates from `boa_engine`, to avoid having to manually import the other crates if someone's already using `boa_engine`.
> Cleanup tester deps and patterns

- README.md
- Updates links in `README.md` to match paths on the new website
-  I noticed these were 404ing when I cloned down the project
> chore: Update README link to reflect new site paths

- cli/Cargo.toml
- core/ast/Cargo.toml
- core/engine/Cargo.toml
- core/gc/Cargo.toml
- core/icu_provider/Cargo.toml
- core/interner/Cargo.toml
- core/interop/Cargo.toml
- core/macros/Cargo.toml
- core/parser/Cargo.toml
- core/profiler/Cargo.toml
- core/runtime/Cargo.toml
- examples/Cargo.toml
- ffi/wasm/Cargo.toml
- tests/Cargo.toml
- tests/fuzz/Cargo.toml
- tests/macros/Cargo.toml
- tests/tester/Cargo.toml
- tools/gen-icu4x-data/Cargo.toml
- tools/scripts/Cargo.toml
Currently, the documentation of our crates on docs.rs doesn't show gated items. This PR solves that by adding the corresponding metadata on the Cargo.toml file.
> Build docs.rs docs with all features enabled

- core/engine/src/builtins/promise/mod.rs
Stage 2.7 as of yesterday. See: https://github.com/tc39/proposal-promise-try
> Implement Promise.try()

- core/engine/src/value/conversions/coerce.rs
- core/engine/src/value/conversions/convert.rs
- core/engine/src/value/conversions/mod.rs
- core/engine/src/value/conversions/try_from_js.rs
- core/engine/src/value/mod.rs
This can be used to transform values in to converted versions of Rust types by using the type system and `TryFromJs`.
Also added a JsString conversion for `TryFromJs`. These methods are going to be useful when #3773 goes in (but this PR nor that one depend on each others).
> Add a new type Convert<> to convert values 

- core/engine/src/object/operations.rs
- examples/src/bin/properties.rs
This Pull Request fixes/closes #3830 
Implements a wrapper around the already existing `[[OwnPropertyKeys]]` internal method.
> Implement object keys access

- examples/src/bin/classes.rs
- examples/src/bin/closures.rs
- examples/src/bin/futures.rs
- examples/src/bin/jsarray.rs
- examples/src/bin/jsarraybuffer.rs
- examples/src/bin/jstypedarray.rs
- examples/src/bin/module_fetch.rs
- examples/src/bin/modulehandler.rs
- examples/src/bin/modules.rs
- examples/src/bin/synthetic.rs
-  replace js_str with js_string in the example code
> Replace `js_str` with `js_string` in examples

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/test262.yml
- .github/workflows/webassembly.yml
> Switch from actions-rs/toolchain to dtolnay/rust-toolchain

- README.md
Closes #3811 
Per title, this adds a matrix badge with a link to Boa's matrix room and also adds the link to the communication section of the README
> Add matrix badge and update communication to include matrix

- core/runtime/src/console/mod.rs
This Pull Request fixes/closes #3805.
- Add group_collapsed function
- It's just an alias to call `console.group`
> Add groupCollapsed

- Cargo.lock
- Cargo.toml
- core/engine/Cargo.toml
- core/engine/src/builtins/intl/collator/mod.rs
- core/engine/src/builtins/intl/list_format/mod.rs
- core/engine/src/builtins/intl/locale/mod.rs
- core/engine/src/builtins/intl/locale/tests.rs
- core/engine/src/builtins/intl/locale/utils.rs
- core/engine/src/builtins/intl/mod.rs
- core/engine/src/builtins/intl/number_format/mod.rs
- core/engine/src/builtins/intl/plural_rules/mod.rs
- core/engine/src/builtins/intl/segmenter/mod.rs
- core/engine/src/builtins/string/mod.rs
- core/engine/src/context/mod.rs
- test262_config.toml
- tests/tester/src/edition.rs
- tools/gen-icu4x-data/Cargo.toml
- tools/gen-icu4x-data/src/main.rs
Some additional cleanups were made to the `Intl` services, since the ECMA-402 spec had editorial changes that hadn't been implemented.
Had to pin `temporal_rs` to the git repo until we publish a new version, but it would be better to fix the panics before doing so.
Removed some hacks that we had in place for locale resolution. We still have a small hack for `Segmenter`, but that will possibly be resolved in the future with locale-aware segmenters.
> Bump ICU4X to 1.5 and cleanup Intl

- Cargo.lock
- Cargo.toml
> Update regress to v0.10.0

- core/engine/src/builtins/eval/mod.rs
- core/engine/src/builtins/function/mod.rs
- core/engine/src/builtins/json/mod.rs
- core/engine/src/bytecompiler/class.rs
- core/engine/src/bytecompiler/declarations.rs
- core/engine/src/bytecompiler/function.rs
- core/engine/src/bytecompiler/mod.rs
- core/engine/src/bytecompiler/statement/with.rs
- core/engine/src/environments/runtime/mod.rs
- core/engine/src/module/source.rs
- core/engine/src/module/synthetic.rs
- core/engine/src/script.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/flowgraph/mod.rs
- core/engine/src/vm/opcode/environment/mod.rs
- core/engine/src/vm/opcode/mod.rs
- Fix base objects in `with` statements
> Fix base objects in `with` statements

- Cargo.lock
- cli/Cargo.toml
- tests/fuzz/fuzz_targets/common.rs
- Fix the history of the boa cli. We accidentally turned off the file history default feature in #3863
> Fix boa cli history

- core/parser/src/lexer/mod.rs
- core/parser/src/parser/mod.rs
- Add a lexer goal symbol for hashbang comments and regexes. This goal is only used for the first lexical token of a `Script` or `Module` parse goal.
> Fix hashbang comments by using proper goal symbols

- core/engine/src/builtins/function/arguments.rs
- core/engine/src/bytecompiler/declarations.rs
- core/engine/src/bytecompiler/mod.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/opcode/arguments.rs
- core/engine/src/vm/opcode/rest_parameter/mod.rs
This is a simple change that removes the formal parameter list from codeblock which was only needed in non-strict mode and compute the required binding indices when needed during compilation, instead of every function call. This also reduces the `CodeBlock` size by 16 bytes.
> Remove `FormalParameterList` from `CodeBlock`

- core/engine/src/builtins/array/mod.rs
- core/engine/src/builtins/error/mod.rs
- core/engine/src/builtins/function/arguments.rs
- core/engine/src/builtins/intl/locale/utils.rs
- core/engine/src/builtins/proxy/mod.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/builtins/typed_array/object.rs
- core/engine/src/environments/runtime/mod.rs
- core/engine/src/error.rs
- core/engine/src/module/namespace.rs
- core/engine/src/object/internal_methods/mod.rs
- core/engine/src/object/jsobject.rs
- core/engine/src/object/operations.rs
This PR creates a new object operation that combines the `HasProperty` and `Get` operations.
In some cases in the spec `HasProperty` and `Get` are called on an object, with the same arguments, directly following each other. Both operations boil down to (in most cases) `[[GetOwnProperty]]`, just that `HasProperty` does not return the value. To avoid duplicating the exact same operations we can combine both operations.
I have some Flame Graphs from a `GetName` operation to visualize the benefit:
Before:
After:
I also ran the benchmarks:
Before:
```txt
RESULT Richards 54.3
RESULT DeltaBlue 58.2
RESULT Crypto 68.4
RESULT RayTrace 186
RESULT EarleyBoyer 170
RESULT RegExp 58.6
RESULT Splay 195
RESULT NavierStokes 159
SCORE 103
```
After:
```txt
RESULT Richards 55.1
RESULT DeltaBlue 59.6
RESULT …
```
> Combine `HasProperty` and `Get` operations when possible

- core/engine/src/builtins/eval/mod.rs
- core/engine/src/builtins/function/arguments.rs
- core/engine/src/environments/runtime/mod.rs
- core/engine/src/module/source.rs
- core/engine/src/module/synthetic.rs
- core/engine/src/vm/opcode/arguments.rs
This PR removes some unnecessary clones in environment functions.
> Remove some environment clones

- core/engine/src/builtins/generator/mod.rs
- core/engine/src/context/mod.rs
- core/engine/src/module/source.rs
- core/engine/src/object/operations.rs
- core/engine/src/vm/mod.rs
- core/engine/src/vm/opcode/arguments.rs
- core/engine/src/vm/opcode/await/mod.rs
- core/engine/src/vm/opcode/control_flow/return.rs
- core/engine/src/vm/opcode/define/mod.rs
- core/engine/src/vm/opcode/delete/mod.rs
- core/engine/src/vm/opcode/iteration/loop_ops.rs
- core/engine/src/vm/opcode/push/literal.rs
- core/engine/src/vm/opcode/rest_parameter/mod.rs
- core/engine/src/vm/opcode/set/name.rs
This PR slightly changes how we store and access call frames in the vm. In addition to the `frames` stack, there is now a `frame` field that always holds the current call frame. The main reason for this is, so that we can avoid panic checks in critical paths.
I also removed some duplicate calls to `Vm::frame` and `Vm::fram_mut` and grouped them where possible. This should not be that relevant anymore, since now it's just a field access.
Here two graphs to visualize the change. These are running in `dev` profile so functions are visible. Here the bigger impact seems to actually be the deref of the `frames` vec, but I'm not sure if the actual cost in `release` looks different.
Before:
After:
And here some benchmarks. I did not run them multiple times, the impact seems a bit high to me: …
> Refactor call frame access to avoid panic checks

- core/engine/src/context/hooks.rs
- core/engine/src/context/mod.rs
- core/engine/src/error.rs
- core/engine/src/object/builtins/jsdataview.rs
- core/engine/src/object/builtins/jsdate.rs
- core/engine/src/object/builtins/jsmap.rs
- core/engine/src/object/builtins/jspromise.rs
- core/engine/src/object/datatypes.rs
- core/engine/src/value/conversions/convert.rs
- core/interop/src/lib.rs
- core/runtime/src/lib.rs
Running `cargo +nightly fmt -- --unstable-features --config format_code_in_doc_comments=true` from https://github.com/boa-dev/boa/issues/3889
> format code in comments

- core/engine/src/object/mod.rs
- core/interop/src/lib.rs
- core/interop/src/macros.rs
This also adds a JsInstance that verifies that `this` is of the proper class, and an `Ignore` that ignore arguments.
The syntax is a bit special because of limitations of macro_rules. For example, the way fields are defined. It was impossible to keep both assignments (e.g. `public field = 123;`) and dynamic fields.
This reduces significantly the boilerplate for declaring classes. The example in class.rs is more than twice as long (if you remove comments) than the macro is.
> Add a js_class to implement the Class trait without boilerplate

- core/engine/src/bytecompiler/class.rs
- core/engine/src/vm/opcode/mod.rs
- core/engine/src/vm/opcode/push/class/private.rs
- Fix HomeObject for private class methods
> Fix HomeObject for private class methods

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
This Pull Request is related to the ongoing work for temporal.
- Bumps `temporal_rs` to `0.0.3`
- Implements more of the functionality already implemented in `temporal_rs`
- Adds `to_temporal_time` and `to_temporal_datetime` abstract operations
> Updates to temporal_rs version and temporal methods

- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/options.rs
This fixes a regression on the tests from changes to the `to_relative_to_object` function.
The function was early returning an error on `relativeTo` being undefined, which is incorrect.
There's also a small update to the order that we fetch `DiffferenceSettings` to be more in line with the order in the specification.
> Patch regression from change to to-relative-to-object

- core/string/src/lib.rs
- core/string/src/str.rs
This adds `get_unchecked` method to `JsString` and `JsStr` for future possible optimization usage.
> Add `get_unchecked` method to `JsString` and `JsStr`

- core/gc/src/lib.rs
As mentioned in https://github.com/boa-dev/boa/issues/3896, Boa's GC threshold is set too low. This was causing too many GC collections before the interpreter even started running.
We see an improvement to the 2.
```
Benchmark main: ./target/release/boa
Time (mean ± σ): 2.2 ms ± 0.2 ms [User: 0.6 ms, System: 0.1 ms]
Range (min … max): 2.0 ms … 3.4 ms 827 runs
```
```
Benchmark PR: ./target/release/boa
Time (mean ± σ):       2.1 ms ±   0.1 ms    [User: 0.6 ms, System: 0.1 ms]
Range (min … max):     1.9 ms …   2.8 ms    924 runs
```
Looking at the traces:
Before:
After (there are no GC collections in this trace)
1MB seems like a good start, we can always bump it higher or adjust after this, V8's nursery size before GC kicks in seems to be between 1-8MB,
> bump gc threshold

- ABOUT.md
- Cargo.lock
- Cargo.toml
- cli/ABOUT.md
- core/ast/ABOUT.md
- core/engine/ABOUT.md
- core/gc/ABOUT.md
- core/icu_provider/ABOUT.md
- core/interner/ABOUT.md
- core/interop/ABOUT.md
- core/interop/Cargo.toml
- core/macros/ABOUT.md
- core/parser/ABOUT.md
- core/profiler/ABOUT.md
- core/runtime/ABOUT.md
- core/string/ABOUT.md
Bump versions to 0.19 and update ABOUT files with all the crates
> update versions and ABOUT files

- .github/ISSUE_TEMPLATE/config.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
Mainly replaced the Discord links with the new Matrix space, and set the new Boa version in the tutorial.
> Cleanup README.md and contributor documentation

- core/engine/src/builtins/eval/mod.rs
- core/engine/src/builtins/function/mod.rs
- core/engine/src/environments/mod.rs
- core/engine/src/environments/runtime/declarative/function.rs
- core/engine/src/environments/runtime/declarative/global.rs
- core/engine/src/environments/runtime/declarative/mod.rs
- core/engine/src/environments/runtime/declarative/module.rs
- core/engine/src/environments/runtime/mod.rs
- core/engine/src/module/source.rs
- core/engine/src/module/synthetic.rs
- core/engine/src/realm.rs
- core/engine/src/vm/opcode/arguments.rs
- core/engine/src/vm/opcode/control_flow/return.rs
- core/engine/src/vm/opcode/define/mod.rs
- core/engine/src/vm/opcode/environment/mod.rs
- core/engine/src/vm/opcode/set/name.rs
Thie PR refactors the environment stack to avoid panics. The main change is to put the global declarative environment in a separete field instead of on the stack itself. That way we can safeley avoid panics.
~~There was only a very slight difference in benchmarks, but I think reducing the panics is worth it either way.~~
After running the benchmarks a few times they look pretty good:
Before:
```txt
RESULT Richards 60.6
RESULT DeltaBlue 63.4
RESULT Crypto 74.4
RESULT RayTrace 202
RESULT EarleyBoyer 186
RESULT RegExp 61.1
RESULT Splay 199
RESULT NavierStokes 175
SCORE 111
```
After:
```txt
RESULT Richards 65.8
RESULT DeltaBlue 69.6
RESULT Crypto 77.1
RESULT RayTrace 201
RESULT EarleyBoyer 199
RESULT RegExp 59.9
RESULT Splay 226
RESULT NavierStokes 176
SCORE 116
```
> Refactor environment stack to remove some panics

- core/engine/src/value/conversions/try_from_js.rs
Implement conversion from floating point values that can be converted to integer values losslessly.
The spec does not distinguish between integer numbers and floating point, so I don't think `4` should succeed and `4.0` fail, according to the spec they have the same type and are equal.
> Implement lossless TryFromJs for integers from f64

- Cargo.lock
- core/string/Cargo.toml
- core/string/src/tests.rs
Should fix the publish action.
> Remove `boa_macros` from `boa_string`

- core/engine/src/error.rs
- core/engine/src/value/conversions/mod.rs
- core/string/src/lib.rs
- core/string/src/str.rs
And as a bonus since I needed it, simplify comparison of strings and add PartialEq<&str> for JsString.
> Add a js_error! macro to create opaque errors

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/instant/mod.rs
Continued work on Temporal :smile: 
- Adds static method implementations
- Bump `temporal_rs` rev
- implement `to_temporal_instant`
> Update `Instant` for new Temporal functionality

- core/interop/src/lib.rs
- core/interop/src/macros.rs
And update documentation for more explanation around the macro.
>  Add a way to add setters/getters in js_class! 

- core/engine/src/bytecompiler/declaration/declaration_pattern.rs
- core/engine/src/bytecompiler/declarations.rs
- core/engine/src/vm/opcode/iteration/iterator.rs
- Fix evaluation of computed property names in declaration patterns
- Fix invalid value getter in iterator opcode
- Fix invalid setting of function binding identifier in `global_declaration_instantiation`
> Fix destructuring assignment evaluation order

- core/parser/src/source/mod.rs
This should allow any path to be added to a Source, even when using `from_bytes` or `from_reader`.
> Add a Source::with_path method to set the path on a Source

- core/runtime/src/console/mod.rs
- core/runtime/src/lib.rs
There are some cleanup that could be done in the number of lines of codes, but this was the smallest change I could do to make the change.
This comes from a need to implement `Console` with using `tracing` as the backend. Please note that there is an issue here where multiple logs in the same function (e.g. `console.trace()`) would output into multiple log entries. This should probably be fixed in a following PR (as this one is already large enough).
> Allow a custom Logger to be used as the backend for boa_runtime::Console

- core/engine/src/module/mod.rs
- core/engine/src/object/builtins/jsfunction.rs
- core/engine/src/object/builtins/jspromise.rs
- core/engine/src/value/mod.rs
- core/engine/tests/assets/gcd.js
- core/engine/tests/gcd.rs
This allows to create a moderately simple example (see `tests/gcd.rs`) that can be used as a tutorial.
There are some typing issues, notably the `name` argument in `get_typed_fn`. Let's discuss.
> Add more utility functions around modules and exports

- core/engine/src/builtins/async_generator/mod.rs
- core/engine/src/vm/completion_record.rs
- core/engine/src/vm/opcode/await/mod.rs
- core/engine/src/vm/opcode/generator/mod.rs
- core/engine/src/vm/opcode/generator/yield_stm.rs
- test262_config.toml
- tests/tester/src/edition.rs
Essentially the same as #3879 but supported by the latest specification.
> Implement new spec changes for `AsyncGenerator`

- tests/tester/src/edition.rs
- tests/tester/src/main.rs
New edition, new variant on our enum.
> Add spec edition 15 to the tester

- core/macros/src/lib.rs
> Fix `js_str` macro to correctly handle latin1 strings

- core/interop/src/macros.rs
> Allow trailing commas in js_class functions

- Cargo.toml
- cli/src/main.rs
- clippy.toml
- core/engine/src/object/builtins/jspromise.rs
- core/engine/src/optimizer/mod.rs
- core/engine/src/vm/mod.rs
- core/runtime/src/console/mod.rs
- tests/tester/src/main.rs
And remove usage of println or allow them.
> Add clippy for denying print and eprints

- core/engine/src/builtins/promise/mod.rs
- core/engine/src/value/mod.rs
This aligns the API with other methods (e.g. `as_function()`) and makes it more intuitive.
This is a breaking change as the `JsValue::as_promise()` API returns a different value. It is now more align to the rest of the API though with `as_*` returning the expected type.
> Rename as_promise to as_promise_object and add as_promise -> JsPromise

- core/engine/src/builtins/atomics/mod.rs
- test262_config.toml
https://github.com/tc39/proposal-atomics-microwait
> Implement `Atomics.pause`

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/value/mod.rs
This PR is related to the ongoing work for temporal, specifically in relation to the `with` methods and partial records.
- Implements `map` on `JsValue`
- Implements `to_partial_date_record` and `to_partial_time_record`
- Builds out the `with` methods on `Time` and `Date` along with the property bags portions of `to_date` and `to_time` abstract methods
I totally blanked on making the fields of `PartialDateTime` public :sweat_smile: So that will hopefully still be coming after a patch I submitted is merged.
> Build out partial record functionality, property bag construction, and `with` methods

- core/engine/src/builtins/array/mod.rs
- core/engine/src/builtins/error/aggregate.rs
- core/engine/src/builtins/intl/list_format/mod.rs
- core/engine/src/builtins/iterable/async_from_sync_iterator.rs
- core/engine/src/builtins/iterable/mod.rs
- core/engine/src/builtins/map/mod.rs
- core/engine/src/builtins/object/mod.rs
- core/engine/src/builtins/promise/mod.rs
- core/engine/src/builtins/set/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/builtins/typed_array/mod.rs
- core/engine/src/builtins/weak_map/mod.rs
- core/engine/src/builtins/weak_set/mod.rs
- core/engine/src/object/builtins/jsmap.rs
- core/engine/src/object/builtins/jsset.rs
- core/engine/src/vm/opcode/iteration/get.rs
- core/engine/src/vm/opcode/push/array.rs
- test262_config.toml
Alternative name: The Great Refactoring Of Iterators
This pulls the latest changes from the spec around iterators, which both makes the code easier in some parts and also future-proofs for any new spec additions that use iterator APIs.
> Refactor iterator APIs to be on parity with the latest spec

- core/interop/src/lib.rs
The issue I'm looking to solve is that I'm passing back the same object into JavaScript (think callbacks). The object is reentrant safe, but I'm ending up doing a lot of `this.borrow().clone()`. This would make it a bit easier to manage.
The JS code looks like that:
```js
const someValue = new ApiClass();
someValue.doSomethingAndCallback(() => {
// Using a naive but straightforward borrow_mut(), Boa would fail here as
// the `doSomethingElse` method would need to borrow_mut() again.
someValue.doSomethingElse();
});
```
> Add a clone_inner method to allow cloning of inner data

- core/ast/src/expression/mod.rs
- core/engine/src/bytecompiler/expression/mod.rs
- core/parser/src/parser/expression/primary/mod.rs
Right now, if I try to run js code with a `debugger` statement in it, I got the error:
`SyntaxError: unexpected token 'debugger', primary expression at line 14, col 645`.
In this PR, I’m simply ignoring the `debugger` statement. I know it’s not a definitive solution, but at least it allows the code to run.
> fix: ignore `debugger` statement

- core/engine/src/builtins/atomics/futex.rs
- core/engine/src/builtins/builder.rs
It is unclear if it is actually unused (`ConstructorNoProto` seems like it is fully unused, but not `Constructor`). Trying to create an MRE for a rust-lang issue, but couldn't reproduce outside of this repro.
This at least temporarily to unblock CI.
Closes #3985.
> Allow dead code for code that is newly detected as unused

- .github/workflows/pull_request.yml
- .github/workflows/rust.yml
- .github/workflows/test262.yml
- .github/workflows/webassembly.yml
Just to have some checks in place before backporting fixes to old releases.
> Enable CI for release branches

- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/webassembly.yml
More fixes for the releases CI.
> Allow warnings when running CI on release branches

- core/engine/src/value/conversions/convert.rs
These should have been there from the start.
> Add support for Trace, Finalize and JsData for Convert<>

- core/engine/src/builtins/atomics/futex.rs
- core/engine/src/builtins/builder.rs
- core/engine/src/object/builtins/jstypedarray.rs
- core/engine/src/value/mod.rs
It might be optimizable, and in either case it should be but this at
least let people use an easy API and enjoy future improvements.
> Add an "iter()" method to Js*Array for convenience

- core/engine/src/error.rs
I assume this will have a fair bit of bikeshedding on the interface.
This only supports text errors since it only adds the message (which is text only). Supports syntax similar to `format!()`, e.g. `js_error!(TypeError: "the number {} should be even", odd_number)`.
I considered another option for the API: having a separate macro per type (like `js_typ_error!()`, `js_syntax_error!()`, etc). I decided to dismiss this and went the way of this PR instead as the code looks closer to what the message will be, since it's normally prefixed with the error. It also declutters the `use` statements as there's only one macro.
For example, the following code:
```rust
js_error!(TypeError: "not a day of the week")
```
would show the following message when printed on the console:
```text
TypeError: not a …
```
> Add a way for js_error! macro to create native errors with message

- core/engine/src/value/mod.rs
- core/runtime/src/console/mod.rs
- core/runtime/src/console/tests.rs
Also added `as_regexp()` in `JsValue` as I needed it for the `boa_wpt` branch. Merged that in this PR.
> Add tests from WPT and fix them in the Console

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/test262.yml
- .github/workflows/webassembly.yml
- Cargo.lock
- Cargo.toml
- README.md
- core/engine/src/builtins/async_generator/mod.rs
- core/engine/src/builtins/atomics/futex.rs
- core/engine/src/builtins/builder.rs
- core/engine/src/vm/completion_record.rs
- core/engine/src/vm/opcode/await/mod.rs
- core/engine/src/vm/opcode/generator/mod.rs
- core/engine/src/vm/opcode/generator/yield_stm.rs
- test262_config.toml
- tests/tester/src/edition.rs
- tests/tester/src/main.rs
Backports the build fixes for version 0.19 to prepare for an early release.
> Backport 0.19 fixes

- core/engine/src/builtins/array/mod.rs
- core/engine/src/builtins/eval/mod.rs
- core/engine/src/builtins/json/mod.rs
- core/engine/src/bytecompiler/class.rs
- core/engine/src/bytecompiler/function.rs
- core/engine/src/bytecompiler/mod.rs
- core/engine/src/bytecompiler/register.rs
- core/engine/src/module/source.rs
- core/engine/src/module/synthetic.rs
- core/engine/src/script.rs
- core/engine/src/vm/call_frame/mod.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/flowgraph/mod.rs
- core/engine/src/vm/opcode/control_flow/return.rs
- core/engine/src/vm/opcode/mod.rs
- core/engine/src/vm/opcode/rest_parameter/mod.rs
As discussed in #3194 this PR extracts the register allocation logic from #3798 which will be used by both PRs.
> Implement register allocation

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/test262.yml
- .github/workflows/webassembly.yml
Fixes the macos release binary action.
Also limits the amount of actions running per PR/protected branch to 1, to avoid running the actions multiple times when pushing multiple times to the same PR/branch.
> Limit actions runs to 1 per branch and fix macos release

- core/engine/src/object/builtins/jsfunction.rs
- core/engine/src/value/conversions/try_from_js.rs
- core/interop/src/lib.rs
- core/interop/tests/assets/fibonacci.js
- core/interop/tests/assets/gcd_callback.js
- core/interop/tests/fibonacci.rs
- core/interop/tests/gcd_callback.rs
Includes adding TryFromJs for "()".
> Add TryFromJs for TypedJsFunction and more tests

- core/runtime/src/console/mod.rs
- core/runtime/src/console/tests.rs
- core/runtime/src/lib.rs
This is not backward compatible but should have minimal impact. This is also more future proof by passing the ConsoleState which is more opaque and allows us to update the way the console object is constructed and passed.
> Add context to the console `Logger` trait

- core/engine/src/value/integer.rs
> `IntegerOrInfinity` `eq` bug fix

- core/engine/src/value/conversions/serde_json.rs
> `JsValue::to_json` fix integer property keys

- Cargo.lock
- cli/src/main.rs
- core/runtime/Cargo.toml
- core/runtime/src/console/mod.rs
- core/runtime/src/lib.rs
- core/runtime/src/url.rs
- core/runtime/src/url/tests.rs
- core/string/src/lib.rs
Some methods are NOT currently supported (some don't make sense outside of a browser context). They are still implemented but will throw a JavaScript Error.
Supported methods should follow the specification perfectly and are tested for it.
Notably missing is the `URLSearchParams` class which is complex with the current Boa API (making iterables is hard) and should be done in a separate PR.
> Add a URL class to boa_runtime

- core/string/src/display.rs
- core/string/src/lib.rs
- core/string/src/str.rs
This is faster when we don't need to keep the unpaired surrogates.
> Add a display_lossy() to write a JsString lossily

- core/engine/src/value/conversions/mod.rs
- core/engine/src/value/conversions/try_into_js.rs
- core/engine/src/value/mod.rs
- core/macros/src/lib.rs
- examples/src/bin/try_into_js_derive.rs
This Pull Request closes #3874 
**Notes**
* I don't sure about conversion of `HashMap` into `JsObject`.
Should it be converted into `JsMap` or  into ordinary object `{ k1: v1, ..., kN: vN }`?
Or maybe I need to add a macro attribute to allow choose a way of conversion of `Map` types?
> `TryIntoJs` trait and derive macro for it

- core/engine/src/builtins/map/mod.rs
- core/engine/src/object/builtins/jsmap.rs
- core/engine/src/value/conversions/try_from_js.rs
- core/engine/src/value/conversions/try_from_js/collections.rs
Seems like `TryFromJs` didn't convert correctly from `JsMap` into `HashMap` / `BtreeMap`
This PR fix it
**Example**  
Next code
```Rust
use boa_engine::{value::TryFromJs, Context, JsResult, Source};
use std::collections::HashMap;
fn main() -> JsResult<()> {
let js_code = "new Map([['a', 2], ['b', 3]])";
let mut context = Context::default();
let js_value = context.eval(Source::from_bytes(js_code))?;
println!("{}", js_value.display());
let map = HashMap::<String, i32>::try_from_js(&js_value, &mut context)?;
println!("{map:?}");
Ok(())
}
```
before this changes will return:
```
Map { "a" → 2, "b" → 3 }
{}
```
and after changes returns:
```
Map { "a" → 2, "b" → 3 }
{"a": 2, "b": 3}
```
**Notes**  
I don't find more fast way(than the one used in `for_each_elem_in_js_map`) to get `(key, …
> `TryFromJs` from `JsMap` for `HashMap` & `BtreeMap`

- core/engine/src/builtins/temporal/error.rs
- core/engine/src/error.rs
- core/gc/src/trace.rs
- core/parser/src/lexer/number.rs
This brings some optimizations:
- use constant to reduce binary size(https://godbolt.org/z/YEq4hW49n)
- change `message`'s type to `Cow<'static, str>` to reduce allocations
> Some optimizations on `Error`

- core/engine/src/value/conversions/try_into_js.rs
This PR also include removal of useless path JsResult:: for Ok and Err, which are preluded already.
> Option::None should try into Undefined, not Null

- .github/workflows/nightly_build.yml
So this should hopefully fix the nightly release. I've been playing around with a new release action in [practice repo](https://github.com/nekevss/dummy-release-test), and I've had some positive output so far (from what I can tell)! 😄
> Use upload-rust-binary-action for nightly release

- .github/workflows/nightly_build.yml
Apparently forgot how to properly spell, so this should fix the current error.
Reminds me that it may be worth looking into adding [Typos](https://github.com/crate-ci/typos) into our CI.
> Fix misspelled permissions in nightly build action

- .github/workflows/nightly_build.yml
This should hopefully be the final PR to get nightly working. I tested this workflow out [here](https://github.com/nekevss/dummy-release-test/actions/workflows/nightly.yml), and it does appear to be working fine.
`ref: refs/tags/nightly` fixes the current error and `target: ${{ matrix.target }}` addresses a warning that is given without the target field.
> Fix `ref` value in nightly and add target to nightly release

- CONTRIBUTING.md
- docs/debugging.md
This Pull Request fixes/closes #4016.
- CONTRIBUTING.md
- docs/debugging.md
By removing all references to a `Dockerfile` that no longer exists.
Edit 1: Fix typo
> Remove dockerfile from documentation

- CHANGELOG.md
This adds a changelog for v0.20.0. I'm sure we may have missed a few things, please take a look and review!
> update changelog for 0.20.0

- .github/workflows/test262_release.yml
This is a new action which should run on release, update test262 data and commit back to the data repo with the latest tag
> update the test262 data on release

- core/ast/src/expression/literal/object.rs
- core/ast/src/function/arrow_function.rs
- core/ast/src/function/async_arrow_function.rs
- core/ast/src/function/async_function.rs
- core/ast/src/function/async_generator.rs
- core/ast/src/function/class.rs
- core/ast/src/function/generator.rs
- core/ast/src/function/ordinary_function.rs
- core/ast/src/scope.rs
- core/ast/src/scope_analyzer.rs
- core/ast/src/source.rs
- core/engine/src/builtins/function/arguments.rs
- core/engine/src/builtins/function/mod.rs
- core/engine/src/bytecompiler/class.rs
- core/engine/src/bytecompiler/declarations.rs
- core/engine/src/bytecompiler/env.rs
- core/engine/src/bytecompiler/function.rs
- core/engine/src/bytecompiler/mod.rs
- core/engine/src/bytecompiler/statement/block.rs
- core/engine/src/bytecompiler/statement/loop.rs
- core/engine/src/bytecompiler/statement/switch.rs
- core/engine/src/bytecompiler/statement/try.rs
- core/engine/src/environments/runtime/mod.rs
- core/engine/src/module/synthetic.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/opcode/push/environment.rs
This PR builds on #3988 and removes runtime environment allocations when possible.
All three commits can be reviewd independently. I just put them all together here, because they depend on each other anyways.
Running the benchmarks did not show a big reduction in execution time, but this should reduce memory usage since we can skip and reduce size of allocations.
- Skip environment creation when all bindings in the scope are local
- Skip environment creation when possible for arrow functions
- Do not allocate space for local bindings in runtime environments
> Reduce environment allocations

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/calendar/mod.rs
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/options.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoned_date_time/mod.rs
- core/engine/src/try_into_js_result_impls.rs
This PR brings Boa inline with the latest changes in Temporal
> update Boa to be inline with Temporal

- core/engine/src/tests/class.rs
- core/engine/src/tests/operators.rs
- core/parser/src/lexer/mod.rs
- core/parser/src/lexer/regex.rs
- core/parser/src/parser/cursor/buffered_lexer/mod.rs
- core/parser/src/parser/cursor/mod.rs
- core/parser/src/parser/expression/primary/mod.rs
This Pull Request closes #3329
> Bug fix: regex started with `/=` parsed as `AssignDiv`

- core/parser/src/parser/expression/left_hand_side/arguments.rs
This Pull Request close #4051 .
> Fix #4051, parse Arguments should expect  `)` not `}`

- core/engine/src/tests/operators.rs
- core/parser/src/lexer/mod.rs
- core/parser/src/lexer/operator.rs
- core/parser/src/lexer/tests.rs
- core/parser/src/parser/cursor/mod.rs
- core/parser/src/parser/expression/assignment/mod.rs
This Pull Request closes #3330 
The reason of the bug was that lexer decides next Token sequence {`...`, `OP`, `EOF`} as invalid and return an error. Yes, it's invalid, but in the same time lexer cannot know that {`...`, `OP`, `SPACE`, `EOF`} is also invalid and therefore there was two different logic to catch first case.
So, for me it seems more logically correct to delegate the catching of invalid ops at the end to the parser
-----
Should I:
* remove all `Ok(...)` from `core/parser/src/lexer/operator.rs` (now there exist only pseudo `Err(..)` that needs only for type inference)?
* use strum::EnumIter to remove enumeration of almost all `Punctuator`  in `core/parser/src/lexer/tests.rs`?
-----
Hmm... now I understand that I don't know the place where errors from lexer don't propagate …
> bug fix: ops that stay strictly at the EOF after assigns ops are ignored

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/date/mod.rs
- core/engine/src/builtins/temporal/calendar/mod.rs
- core/engine/src/builtins/temporal/error.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date/tests.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoned_date_time/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
- core/engine/src/context/mod.rs
- test262_config.toml
- tests/tester/src/edition.rs
- tests/tester/src/read.rs
This Pull Request is related to the ongoing work for #1804
- Switches Boa to the most recent revision of `temporal_rs`
- Adds a `tz_provider` field to `Context` using `FsTzdbProvider` to provide initial time zone support
- Builds out the some of the initial accessor properties and some methods for `ZonedDateTime`
- Builds out a couple methods for `Now`
> Build out Temporal's `ZonedDateTime` and `Now`

- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/value/mod.rs
This Pull Request is related to ongoing work for #4070.
- Adds `JsValue::map_or` method
- Fixes handling of undefined arguments to both the `PlainTime` constructor and the `Duration` constructor
> Patch Temporal.PlainTime and Temporal.Duration constructors

- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to the general work on #1804
- Adds or adjusts the error message for the `prototype.valueOf` method implementation to the Temporal builtins
> Add valueOf methods to the Temporal builtins

- core/engine/src/builtins/number/conversions.rs
Closes https://github.com/boa-dev/boa/issues/4062.
> Add `fjcvtzs` instruction for `ARMv8.3` target

- core/parser/src/parser/tests/mod.rs
This should prevent regressions over parsing large expressions.
Closes #162.
> Add a stress test to the parser to parser multi-millions tokens

- core/ast/src/scope.rs
- core/engine/src/bytecompiler/mod.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/flowgraph/mod.rs
- core/engine/src/vm/opcode/get/name.rs
- core/engine/src/vm/opcode/mod.rs
- Add inline cache for getting bindings from the global object
I saw a small performance increase when running the benchmarks for this patch.
> Add inline cache for getting bindings from the global object

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
Posting this as a draft to hopefully get comments.
TLDR: I'm convinced the way we currently handle converting JsValue to integers in the Temporal implementation is wrong and this is a way to update it.
Currently, we are using `to_integer_with_truncation`, `to_positive_integer_with_truncation` and `to_integer_if_integral` to convert values into `i32`. These methods are still hold over from the initial prototype of Temporal prior to `temporal_rs` being split off. At the time, I think it was ultimately an optimistic approach, but I'm now fairly certain it's wrong long term and should probably addressed (hence the draft PR)  ASAP.
Also, every argument being truncated to `i32` negatively impacts `temporal_rs`'s API by forcing us to keep the values at `i32`. This change would allow us to change …
> Update Temporal ToIntegerIfIntegral, ToIntegerWithTruncation, and ToPositiveIntegerWithTruncation implementation 

- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to ongoing work for #4075.
It adds the below methods
- Temporal.ZonedDateTime.compare
- Temporal.prototype.withPlainTime
- Temporal.prototype.withTimeZone
- Temporal.prototype.withCalendar
- Temporal.prototype.equals
- Temporal.prototype.startOfDay
- Temporal.prototype.toInstant
- Temporal.prototype.toPlainDate
- Temporal.prototype.toPlainTime
- Temporal.prototype.toPlainDateTime
> Add more `ZonedDateTime` method implementations

- core/engine/src/builtins/temporal/plain_date_time/mod.rs
This Pull Request is related to #4072.
I was doing some bug searching / fixing and noticed that the wrong method was being called in since.
> Adjust call to correct method for `PlainDateTime.prototype.since`

- core/engine/src/object/builtins/jsarray.rs
This Pull Request fixes a very minor type in its rust jsArray api
- just rename shift into unshift in jsarray::unshfit
> fix very minor typo shift -> unshift

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to ongoing work for #1804 
This is a general bump in the `temporal_rs` version that implements `ZonedDateTime` for duration rounding, updates the general API, build out of the remaining `Now` methods, and a couple other fixes.
Some other changes made in this PR are:
- Updates to the Temporal object's `static_property` attribute flags
- Fixed misspelled property names `epochMilliseconds` and `epochNanoseconds`
- Removed some unused functions and variables in the `PlainDate` module
> Bump the `temporal_rs` version and related changes

- test262_config.toml
- tests/tester/src/edition.rs
- tests/tester/src/read.rs
This Pull Request bumps the test262 commit version.
There are also some changes made to support the new SpiderMonkey harness files and tests. Although, I did end up ignoring the SpiderMonkey tests in general as some of the tests seemed implementation specific. There were some tests that looked like they may not be engine specific, but maybe those will be moved out of the sm tests over time?
> Bump test262 commit and changes to `boa_tester` to support sm changes

- core/engine/src/object/internal_methods/mod.rs
- core/engine/src/property/mod.rs
- Avoid cloning values in `PropertyDescriptor` functions.
- Avoid some matches in `PropertyDescriptor` functions.
> Remove some clones and branches in hot `PropertyDescriptor` functions

- .vscode/launch.json
- core/engine/src/builtins/array_buffer/mod.rs
- core/engine/src/builtins/array_buffer/utils.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/environments/runtime/mod.rs
- core/gc/src/lib.rs
- core/gc/src/test/weak.rs
- core/gc/src/trace.rs
- test262_config.toml
- tests/tester/src/main.rs
- tests/tester/src/read.rs
This allows enabling the sm test suite which was throwing a SIGSEGV on memory usage.
Also, ignores a couple of tests that cause panics.
> Fix bugs on ephemeron and TypedArray.prototype.slice

- .vscode/launch.json
- Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
- core/parser/src/error/mod.rs
This should both make it easier to develop the CLI and also make it easier to add custom error messages in the future.
Closes #4085.
> Cleanup CLI to use eyre + refactor patterns

- core/string/src/lib.rs
- core/string/src/str.rs
- core/string/src/tests.rs
This just moves some methods from `JsString` to `JsStr`, since they're more general and should be useful when you have only a `JsStr`.
Also changes the debug implementation of `JsStr` to only print the underlying string.
> Move methods of `JsString` to `JsStr`

- core/engine/src/builtins/error/aggregate.rs
- core/engine/src/builtins/error/eval.rs
- core/engine/src/builtins/error/mod.rs
- core/engine/src/builtins/error/range.rs
- core/engine/src/builtins/error/reference.rs
- core/engine/src/builtins/error/syntax.rs
- core/engine/src/builtins/error/type.rs
- core/engine/src/builtins/error/uri.rs
- core/engine/src/builtins/object/mod.rs
- core/engine/src/error.rs
- core/engine/src/value/display.rs
- core/runtime/src/lib.rs
- test262_config.toml
Implements the [`Error.isError`](https://github.com/tc39/proposal-is-error) proposal, and unifies `Error` with `ErrorObject` into a single `Error` type.
> Implement `Error.isError`

- Cargo.toml
- core/ast/src/scope.rs
- core/engine/src/bigint.rs
- core/engine/src/builtins/array_buffer/shared.rs
- core/engine/src/builtins/array_buffer/utils.rs
- core/engine/src/builtins/atomics/futex.rs
- core/engine/src/builtins/boolean/mod.rs
- core/engine/src/builtins/intl/locale/utils.rs
- core/engine/src/builtins/number/mod.rs
- core/engine/src/builtins/promise/mod.rs
- core/engine/src/builtins/string/mod.rs
- core/engine/src/builtins/temporal/time_zone/mod.rs
- core/engine/src/object/shape/shared_shape/mod.rs
- core/engine/src/small_map/mod.rs
- core/engine/src/tagged.rs
- core/engine/src/value/equality.rs
- core/parser/src/lexer/mod.rs
- core/parser/src/parser/function/mod.rs
- core/runtime/src/console/mod.rs
- core/string/src/tagged.rs
To maintain backward compatibility, we had to move to using caller style calls (`sptr::Strict::addr(...)`) as clippy was erroneously triggering those as unused (and `.addr()` is not stabilized in 1.82).
> Fix CI with the latest linter errors introduced in 1.84

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/options.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date/tests.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
This Pull Request is related to ongoing work for #4071.
- Bumps "temporal_rs" to current main
- Adds `PlainDate::to_string` and `PlainDate::to_json`
- Adds handling for ZonedDateTime objects in `to_temporal_instant`
> Implement `PlainDate` string methods

- Cargo.lock
- cli/src/main.rs
- core/engine/src/builtins/promise/mod.rs
- core/engine/src/builtins/promise/tests.rs
- core/engine/src/context/mod.rs
- core/engine/src/job.rs
- core/engine/src/object/builtins/jspromise.rs
- core/engine/src/script.rs
- core/engine/src/tests/async_generator.rs
- core/engine/src/tests/iterators.rs
- core/engine/src/tests/promise.rs
- core/engine/tests/imports.rs
- core/engine/tests/module.rs
- core/interop/src/lib.rs
- core/interop/src/macros.rs
- core/interop/tests/embedded.rs
- examples/Cargo.toml
- examples/src/bin/module_fetch_async.rs
- examples/src/bin/modules.rs
- examples/src/bin/smol_event_loop.rs
- examples/src/bin/synthetic.rs
- examples/src/bin/tokio_event_loop.rs
- tests/tester/src/exec/mod.rs
This changes the API of `JobQueue` to take a non_exhaustive enum `Job`, which should avoid breaking changes in the future. Some other changes:
- Renames `JobQueue` to `JobExecutor`.
- Introduces `JobPromise`, which is a wrapper around `NativeJob` but clearly states that the job will push promises forward.
- Introduces `NativeAsyncJob`, an equivalent to `NativeJob` that is `Future`-compatible.
> Revamp `JobQueue` into `JobExecutor` and introduce `NativeAsyncJob` 

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to ongoing work for #1804
- Adds `toJSON` and toString for `PlainYearMonth`
- Adds `toJSON` and toString for `PlainMonthDay`
- Adds `toJSON` and toString for `Duration`
- Bumps `temporal_rs` to most recent git revision
- Reorders some of the impl blocks for `PlainMonthDay` to align with other temporal builtin ordering
> Implement `toString` and `toJSON` methods for the remaining builtins `Duration`, `PlainMonthDay`, and `PlainYearMonth`

- core/engine/src/builtins/array/mod.rs
This optimization is especially useful for array literal construction. Instead of calling `OrdinaryGetOwnProperty` and `OrdinaryDefineOwnProperty` on the array object while setting the "length" property, all of that can be skipped if the shape of the array has not changed.
> Set the array "length" property in `[[DefineOwnProperty]]` based on the array shape

- Cargo.lock
- Cargo.toml
- core/engine/src/bigint.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to ongoing progress for #4075.
- Implements `since` and `until` methods for `ZonedDateTime`
- Includes a few bug fixes to various parts in `temporal_rs`
- Adds a `to_i128` to `JsBigInt` to skip indirect casting via `to_f64`
> Implement since and until methods for ZonedDateTime

- core/engine/src/builtins/temporal/duration/mod.rs
This Pull Request is related to ongoing work for #1804 and #4070.
- Changes adjusts the integer type from i64 -> i128 as the max nanosecond value * 2 and the max microsecond value * 2 exceeds the range of i64.
[Relevant test](https://github.com/tc39/test262/blob/main/test/built-ins/Temporal/Instant/prototype/add/minimum-maximum-instant.js)
> Fix truncation on max microseconds and nanoseconds

- core/engine/src/builtins/date/mod.rs
- core/engine/src/context/hooks.rs
- core/engine/src/context/mod.rs
- core/engine/src/object/builtins/jsdate.rs
- examples/src/bin/jsdate.rs
Previously it was very difficult to keep a stateful `HostHooks`, since it needed to be a static reference. Now it can be shared. This is particularly useful for mocking hooks for testing.
This also follows the pattern for the job executor and the module loader.
I did not see any impact on performance.
> Make the HostHooks shareable between app and context

- core/engine/src/builtins/date/mod.rs
- core/engine/src/context/hooks.rs
- core/engine/src/context/mod.rs
- core/engine/src/context/time.rs
- core/engine/src/object/builtins/jsdate.rs
This will add the capacity for the entire engine to mock time during tests. No impact on performance should be noticeable.
Fixed #4144
> Implement an internal time type and Clock trait

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
- Fixes the returned value of `Instant::get_epoch_milliseconds`
- Bumps `temporal_rs` with some bug fixes
- Adjusts some method names due to `temporal_rs` changes
> Bump temporal_rs and fix instant return

- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to the ongoing work for temporal
It fixes a couple bugs
- Order of ops for accessing a time-like property bag 
- Uses the correct `from_partial` method from `temporal_rs`
- Properly handles an `undefined` arg provided to `withPlainTime`
> Fix issues with `to_temporal_time` and `ZonedDateTime.prototype.withPlainTime`

- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to the ongoing work for #1804 .
- Implements the baseline `toLocaleString` stub for all types (the non ECMA-402 implementation)
- Add the intl methods `era` and `eraYear` to `PlainDate` and `PlainDateTime`
- Adds some general cleanup to `PlainYearMonth` to better align it with other Temporal builtins
- Removes some dead code from `now.rs` and `mod.rs`
> Implement toLocaleString and some general cleanup

- core/engine/src/context/mod.rs
- core/runtime/src/console/mod.rs
- core/runtime/src/console/tests.rs
This Pull Request implements the discussion in Matrix about trace logging.
- Adds a `trace` function to the `Logger` trait.
- Calls that `trace` function  from `Console.trace`.
For such a small PR, I encountered a few niggles:
The `Logger` trait derives from the `Trace` trait, which already has a `trace` function, but is unrelated to trace logging. This meant I had to call the new trace function by doing:
```rust
Logger::trace(logger, formatter(args, context)?, &console.state, context)?;
```
rather than the following which is ambiguous to the compiler:
```rust
logger.trace(formatter(args, context)?, &console.state, context)?;
```
This is unsatisfactory, but I also felt that renaming the new `Logger.trace` function would make it inconsistent with the surrounding …
> Add trace function to Logger trait

- core/ast/src/position.rs
- core/ast/src/scope.rs
- core/ast/src/scope_analyzer.rs
- core/ast/tests/scope.rs
- Allow local parmeters if mapped arguments object is not used
- Add tests for scopes in `boa_ast`
> Allow local parameters if mapped arguments object is not used

- Cargo.lock
- Cargo.toml
- core/engine/Cargo.toml
- core/engine/src/builtins/temporal/now.rs
This Pull Request is related to the ongoing work for #1804
This most recent version includes some bug fixes along with some API changes to `Now` in `temporal_rs`. Changes were made to accommodate the `Now` changes.
> Bump temporal_rs to Feb. 15 version + adjustments

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request fixes/closes #1804 and #4072.
- Adds the `PlainDateTime::round` implementation from `temporal_rs`
- Bumps `temporal_rs` and related adjustments for time zone parsing
> Add `PlainDateTime.prototype.round` implementation from `temporal_rs`

- core/engine/src/builtins/date/tests.rs
- core/engine/src/builtins/date/utils.rs
- Avoid allocation if string is ascii
- Return early if string from utf16 encoded `JsString` is not ascii
- Replace `Char<'_>` with `slice::Iter<'_, u8>`
- Add `next_n_digits` helper method to save calls of `next_digit`
- Merge duplicate codes in matches
> Simplify date parser

- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
- core/engine/src/error.rs
- core/engine/src/module/namespace.rs
- core/engine/src/object/jsobject.rs
- core/engine/src/vm/opcode/concat/mod.rs
- core/parser/src/parser/expression/primary/object_initializer/mod.rs
- core/parser/src/parser/function/mod.rs
- core/parser/src/parser/statement/mod.rs
- core/parser/src/source/utf16.rs
- core/parser/src/source/utf8.rs
- core/string/src/lib.rs
> Apply rustc 1.85 lints

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to ongoing work for #1804
- Bumps `temporal_rs` version
- Adds stubs for all remaining methods except for `Duration.prototype.compare`, `PlainDate.prototype.toZonedDateTime` (these methods are)
The main goal here was to complete some of the remaining leg work for Temporal in Boa (outside of any remaining debugging).
> Build out remaining method stubs for temporal

- core/engine/src/value/inner/nan_boxed.rs
This is a small optimization on of the `drop` method on nan-boxed values, rearrange the checks so the common pointer types get checked first. Since this method is called so many times this leads to some performance improvements.
```
RESULT Richards 123
RESULT DeltaBlue 111
RESULT Crypto 142
PROGRESS RayTrace
RESULT RayTrace 290
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 356
PROGRESS RegExp
RESULT RegExp 70.2
PROGRESS Splay
RESULT Splay 474
PROGRESS NavierStokes
RESULT NavierStokes 335
SCORE 197
```
```
RESULT Richards 128
RESULT DeltaBlue 111
RESULT Crypto 149
PROGRESS RayTrace
RESULT RayTrace 292
PROGRESS Earley
PROGRESS Boyer
RESULT …
```
> Prioritize drop of common types for nan-boxed `JsValue`

- core/string/src/builder.rs
- core/string/src/lib.rs
- Simplify `JsString::as_str` (miri passed,  decrease the size of `cli` executable by ~5kb under release mode (28,680kb => 28,675kb) )
- Replace soft deprecated `addr_of*` macro with `& [const|mut] raw`
- Mark some `&mut self` tagged methods const
> Some string cleanups

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/options.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to ongoing work for #1804 and primarily #4077
- Includes `PlainYearMonth::from_str` fixes from `temporal_rs`
- Includes updates related to `MonthCode`
> Add changes from YearMonth parsing update and MonthCode addition

- core/engine/src/builtins/temporal/duration/mod.rs
Implemented the method ``Duration.compare`` in the engine from temporal.rs :)
Most of the tests on test262 are now passing for this function
-
-
-
> implementation of static method compare for duration from temporal.rs

- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request related to ongoing work for #1804.
- Fixes the order of operations for `to_partial_zdt`
- Removes some unused code
> Some cleanup + order of operations fixes

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/intl/number_format/options.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request related to ongoing work for #1804
- Bumps temporal_rs and related fixes
- Adds ZonedDateTime::round stub that was somehow missed.
- A couple fixes for PlainDate order of operations and instant
- A bump to `tinystr` that was causing package resolution issues.
> Temporal bump and fixes

- core/engine/src/value/conversions/serde_json.rs
This Pull Request fixes/closes #4175.
- The actual content of `to_json` is moved to a new internal method `to_json_inner`. This internal method takes one more argument `stack` that keeps track of objects seen so far. If the current object is in the stack, it means that there's a cycle and we return a TypeError.
- `to_json` calls the internal method and returns results as usual.
- A test case is added.
> Fix JsValue::to_json with cyclic values

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/plain_date/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- Bump temporal and adapt the corresponding function calls in the engine:)
- Implement functions ``PlainDate.prototype.toPlainMonthDay`` and ``PlainDate.prototype.toPlainYearMonth``
> Temporal bump and implementation of toPlainYearMonth and toPlainMonthDay

- cli/src/main.rs
- core/ast/src/lib.rs
- core/engine/src/lib.rs
- core/gc/src/lib.rs
- core/icu_provider/src/lib.rs
- core/interner/src/lib.rs
- core/macros/src/lib.rs
- core/parser/src/lib.rs
- core/profiler/src/lib.rs
- core/runtime/src/lib.rs
This Pull Request fixes the logo URL in the documentation. We no longer have a "generic" logo, but a black and a yellow ones. This fixes the link so that it's displayed properly.
> Fixed logo in documentation

- core/engine/src/value/conversions/serde_json.rs
- core/engine/tests/module.rs
This Pull Request fixes/closes #3842.
Personally I've found `JsValue::to_json` to be fairly useless in its current implementation, as it will panic if the data structure being converted contains undefined, and I often don't have control over this.
The PR changes the following:
The `JsValue::to_json` method no longer panics if the structure contains `undefined`.
If `undefined` is encountered it will:
- Omit the property if it is part of an object.
- Replace with `null` if `undefined` is an element of an array. I don't love this, but couldn't think of a better solution.
- Return None if `to_json` is being called on `JsValue::undefined()`.
Because of the last point there is a breaking change: `JsValue::to_json` now returns `JsResult<Option<Value>>` instead of `JsResult<Value>`.
To avoid a …
> Update JsValue::to_json to support undefined

- Cargo.toml
- core/engine/src/native_function/mod.rs
- examples/src/bin/smol_event_loop.rs
- examples/src/bin/tokio_event_loop.rs
This allows carrying the `context` through await points, making it much more ergonomic to use for big async functions.
> Change signature of `from_async_fn` to allow capturing the context

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/now.rs
- core/engine/src/builtins/temporal/options.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
- core/engine/src/builtins/temporal/plain_year_month/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
- Bump temoral.rs to latest version. Current commit hash is over a month old
- Was on this updated version to use the boa tester locally for a while, and decided to submit it :)
> Temporal bump

- core/engine/src/builtins/temporal/plain_date/mod.rs
This Pull Request is related to the ongoing work for #1804 and #4071.
Briefly looking over the test262 results locally, the remaining failing tests for this suite should be related to similar parsing bugs for other methods, and should be fixed with subsequent `temporal_rs` updates.
> Enable `PlainDate.prototype.toZonedDateTime` method

- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to #1804 and #4072.
These were missed with the change from yesterday. With these methods activated, I believe that there is only one last method `ZonedDateTime::round` to be implemented in Boa from `temporal_rs`.
> `PlainDateTime::toZonedDateTime` & `PlainDateTime::toPlainDate` implementations

- Cargo.lock
- Cargo.toml
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
Particularly exciting is that this PR removes the final "Not yet implemented" stub from Boa's side (I think `temporal_rs` still has 4-5 methods left, but majority have issues and/or PRs opened for them). 
- Bumps `temporal_rs`
- Adds ZonedDateTime.prototype.round impl
- Changes related to updates in `temporal_rs`, specifically `Duration`'s move away from `f64` internally
> Bump temporal_rs and add ZonedDateTime.prototype.round impl

- Cargo.lock
- README.md
- core/engine/Cargo.toml
- core/engine/src/sys/js/mod.rs
- ffi/wasm/Cargo.toml
- ffi/wasm/src/lib.rs
Related to #4211 
- Enables the `wasm_js` feature of getrandom for `wasm32-unknown-unknown` target in `boa_engine` crate
- Add some documentation to `README.md`
Rendered doc:
> Enable `wasm_js` feature of getrandom in boa_engine crate

- core/engine/src/value/inner/nan_boxed.rs
While profiling, I noticed, that especially in the `NavierStokes` benchmark, the `NanBoxedValue::as_variant` function was taking a lot of runtime. I think the range checks caused this. I refactored the nan-boxing a bit, so that the value kind is always encoded in bits 48-50. Because this only leaves space for 7 kinds, I encoded `null` and `undefined` into one kind.
Currently we use bit 51 for kind encoding, but as far as I understood the sources I looked at, if bit 51 is 0, the NaN value is a signaling NaN. But to be honest I have not found any real indicators, that using the bit, as long as you do not pass a signaling NaN back into a floating point algorithm, causes big issues.
When running the benchmarks, for most this change has no real impact. But in `NavierStokes` I get a slight …
> Avoid range checks in nan-boxing

- core/engine/src/builtins/set/mod.rs
- core/engine/src/builtins/set/tests.rs
- core/engine/src/value/mod.rs
- test262_config.toml
There are differences in the steps and the spec, and the 262 tests fail because they are very strict on the order of operations.
There are 3 tests in `test262/test/staging/sm/Set` that are failing (`is-subset-of`, `difference` and `intersection`). The three tests actual check that `delete()` replaces entries with `empty` (according to spec) and behave expectedly. Using the `OrderedSet` (which uses an internal map) it would be impossible without some extra logic in those methods. I did not implement that logic, as it would be outside the scope of this PR IMO.
> Fix the Set methods to pass the 262 tests

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- core/interop/Cargo.toml
- core/interop/src/loaders/embedded.rs
- core/interop/tests/embedded.rs
- core/macros/Cargo.toml
- core/macros/src/embedded_module_loader.rs
This results in much smaller binaries when embedding javascript. The compression is hidden behind a flag and by default will not compress, so there is no breaking change.
> Add support for LZ4 compression in embedded module loader

- .cargo/config.toml
- test262_config.toml
- tests/tester/src/edition.rs
Another day, another Test262 bump.
Had to cleanup a couple of feature names, because some of them were included into ES2025, and two new ones were added.
> Bump Test262 hash commit and cleanup test features

- core/engine/src/builtins/array_buffer/mod.rs
- core/engine/src/builtins/array_buffer/utils.rs
- core/engine/src/builtins/typed_array/builtin.rs
Follow up from #4288.
Fixes the two panics that occurred after bumping the Test262 commit hash.
> Fix panics on staging TypedArray.slice tests

- core/engine/src/spanned_source_text.rs
Small change that replaces the inner storage of `SourceText`, since no inner field requires tracing.
> Replace inner `Gc<T>` with `Rc<T>` for `SourceText`

- core/interop/tests/class.rs
- core/interop/tests/module.rs
- core/macros/src/class.rs
- core/macros/src/lib.rs
- core/macros/src/module.rs
- core/macros/src/utils.rs
- examples/src/bin/try_into_js_derive.rs
This should reduce the amount of rename on each fields.
> Add a #[boa(rename = ...)] attribute to TryFromJs and TryIntoJs derive macros

- core/engine/src/value/operations.rs
This PR fixes #4302, by adding an additional check to the `JsValue::mul` method.
> Fix `JsValue::mul` to handle zero times a negative integer

- core/ast/src/keyword/mod.rs
- core/parser/src/parser/statement/declaration/hoistable/class_decl/mod.rs
- core/parser/src/parser/statement/declaration/hoistable/class_decl/tests.rs
This Pull Request fixes/closes #4298.
- Added the `is_reserved_keyword` method to `Keyword` to determine if it is a reserved word.
- Added a check for non-reserved words when parsing class names.
- Added unit tests.
> Allow non-reserved keywords to be used as identifiers

- core/engine/src/vm/opcode/call/mod.rs
It will bring a slight performance improvement.
main:
```
RESULT Richards 105
RESULT DeltaBlue 108
RESULT Crypto 118
PROGRESS RayTrace
RESULT RayTrace 255
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 297
PROGRESS RegExp
RESULT RegExp 59.5
PROGRESS Splay
RESULT Splay 420
PROGRESS NavierStokes
RESULT NavierStokes 268
SCORE 169
undefined
```
PR:
```
RESULT Richards 109
RESULT DeltaBlue 114
RESULT Crypto 119
PROGRESS RayTrace
RESULT RayTrace 262
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 299
PROGRESS RegExp
RESULT RegExp 59.6
PROGRESS Splay
RESULT Splay 450
PROGRESS NavierStokes
RESULT NavierStokes 277
SCORE 175
undefined
```
> Mark the error path in `Call::operation` as cold.

- core/string/src/str.rs
This PR makes the `JsStr`'s len be encoded with `TaggedLen` reducing the size from `24` to `16` bytes, shaves `5464` bytes from the const `RAW_STRINGS` array.
The tests have been run under miri and it's happy with the change :partying_face: 
----
```
RESULT Richards 144
RESULT DeltaBlue 151
RESULT Crypto 144
PROGRESS RayTrace
RESULT RayTrace 333
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 385
PROGRESS RegExp
RESULT RegExp 72.1
PROGRESS Splay
RESULT Splay 527
PROGRESS NavierStokes
RESULT NavierStokes 334
SCORE 218
```
```
RESULT Richards 146
RESULT DeltaBlue 152
RESULT Crypto 146
PROGRESS RayTrace
RESULT RayTrace 344
PROGRESS Earley
PROGRESS …
```
> Shrink `JsStr` from 24 to 16 bytes

- Cargo.lock
- core/engine/src/string.rs
- core/string/Cargo.toml
- core/string/src/builder.rs
- core/string/src/common.rs
- core/string/src/lib.rs
- core/string/src/tests.rs
- Remove `usize` tagging for known-static strings (remove `tag_ptr` dependency)
- Instead of storing a `StaticJsString` which points to a `&'static JsStr<'static>`, we store the tagged `JsStr` static reference directly.
- Remove `StaticJsString` and `RefCount` union.
- Store `Cell<usize>` for refcount in `JsString`
- Change `RAW_STRING_CACHE` to store a `HashSet<&'static JsStr<'static>>` instead of `FxHashMap<JsStr<'static>, usize>` (reduce size of key-value pair by 16 bytes)
We tag the `&'static JsStr<'static>` pointer by using `byte_add()/byte_sub()`, this preserves the strict-provenance., when we check if we tag we use `addr()` discards the provenance for the tag check, but that's fine since we don't reconstruct a pointer from the addr. Tested with `miri` with …
> Refactor `JsString`'s static string tagging

- core/engine/src/object/mod.rs
Without `repr(C)`, the compiler may reorder fields, which can lead to undefined behavior during `Gc::cast`-ing.
> Add `repr(C)` on `Object` to prevent field reordering

- core/engine/src/native_function/mod.rs
Old documentation was still passing because the imports were missing a comma.
- Removed the caveats section because they don't apply anymore thanks to the new async closures.
- Slightly tweaked the signature of the function. We don't need to use `for<'a>` here because the compiler is smart enough to capture the lifetime of `&RefCell` without capturing the lifetime of `&mut Context`.
> Fix documentation for NativeFunction::from_async_fn

- core/macros/src/utils.rs
This fix adds a Middle state when the character is in the middle of the string, as camelCase should not lowercase those. This happens on short middle fragments of the string.
Add tests for it too.
> Fix a camel case bug

- core/engine/src/builtins/temporal/plain_date_time/mod.rs
- core/engine/src/builtins/temporal/plain_time/mod.rs
More updates to the temporal documentation started in #4353.
This PR contains the updates to PlainTime and PlainDateTime.
The major updates are made on the respective commits for the built-ins. There were a couple follow up commits to add some fixes.
> Temporal documentation update, part 2

- core/engine/src/builtins/array_buffer/mod.rs
- core/engine/src/builtins/array_buffer/shared.rs
- core/engine/src/builtins/array_buffer/utils.rs
- core/engine/src/builtins/async_generator/mod.rs
- core/engine/src/builtins/atomics/mod.rs
- core/engine/src/builtins/intl/number_format/mod.rs
- core/engine/src/builtins/map/mod.rs
- core/engine/src/builtins/regexp/mod.rs
- core/engine/src/builtins/temporal/duration/mod.rs
- core/engine/src/builtins/temporal/instant/mod.rs
- core/engine/src/builtins/temporal/mod.rs
- core/engine/src/builtins/temporal/zoneddatetime/mod.rs
- core/engine/src/builtins/typed_array/builtin.rs
- core/engine/src/builtins/typed_array/object.rs
- core/engine/src/object/builtins/jsarraybuffer.rs
- core/engine/src/object/builtins/jsdataview.rs
- core/engine/src/object/builtins/jssharedarraybuffer.rs
- core/engine/src/object/datatypes.rs
- core/engine/src/object/jsobject.rs
- core/engine/src/object/mod.rs
- core/engine/src/object/shape/shared_shape/template.rs
- core/engine/src/vm/opcode/generator/mod.rs
- core/engine/src/vm/opcode/generator/yield_stm.rs
This PR implements removes the `Box` from `Object`'s data member (by implementing this PR comment https://github.com/boa-dev/boa/pull/4287#issuecomment-2993682209).
The main idea is to limit the alignment, for the min we use a wrapper struct (`ObjectData<T>`) that has an minimum alignment using the `#[align(N)]`, and for the max alignment we use a constant assertion, preventing compilation with a message on how to workaround it.
> Remove `Box` from `Object`'s data member

- core/engine/src/vm/call_frame/mod.rs
- core/engine/src/vm/code_block.rs
- core/engine/src/vm/mod.rs
- core/engine/src/vm/source_info/mod.rs
- core/engine/src/vm/tests.rs
Prior to this, it was impossible for an application to know the origin of an API call.
My use case is that I want to enable back trace logging on `console.trace()` or when a CLI flag is used.
> Allow public access to the full position of a call frame

- core/engine/src/value/display.rs
- core/engine/src/value/mod.rs
- core/engine/src/value/tests.rs
- core/runtime/src/fetch/tests/response.rs
This fixes some visual issues like alignment of brackets, and also make it more consistent when keys are long (it does not take much, only need to be longer than ident which is 4).
Since most of our tests have single letter keys this never showed up as much of a problem, but in the real world it becomes annoying.
Before:
```
{
hello: "world",
z: {
a: 1
}
}
```
After:
```
{
hello: "world",
z: {
a: 1
}
}
```
> Remove alignment of property keys with identation

- core/engine/src/builtins/math/mod.rs
Follow up to #4383.
As noted, there may be further optimizations we could do in the future with Array's where the length is known and `XsumSmall` and `XsumLarge` are used directly vs. `XsumAuto`.
> Update `Math.sumPrecise` to remove `SummationState`

- Cargo.lock
- core/engine/src/value/display.rs
This code heavily relied on allocating strings and vectors of strings for each object properties. This new logic eliminates the allocations entirely, saving both memory and improving performance.
It also makes the logic easier to follow, which might be help with simplification later.
Tests should be unchanged.
> Replace the String producing Display logic to using a Formatter

- core/ast/src/function/ordinary_function.rs
- core/ast/src/scope_analyzer.rs
- core/ast/src/source.rs
- core/ast/tests/scope.rs
- core/engine/src/builtins/function/mod.rs
- core/parser/src/parser/mod.rs
- core/parser/src/parser/tests/mod.rs
This gives better error messages:
Prior to this PR, the message would simply say "invalid scope analysis" without any further reason.
> Propagate AST errors to the user

- cli/src/main.rs
- core/runtime/src/interval.rs
Allow an expression to be passed from the arguments (using -e). This makes it easier to just run a single expression and returning.
Additionally, if the value returned by a _file_ is undefined, don't show it. It gets confusing to see a list of "undefined" on the command line when running a bunch of modules in batch.
Another change is merging the error printing code so the output is more consistent. As well, I added distinction between an error thrown from a statement versus from a job, so the user can see where it's coming from.
Added support for timeout and generic jobs in the CLI. Now we can use setTimeout or any generic jobs. The CLI will always wait for all jobs to be completed before exiting, which makes setInterval a bit awkward if it has no end conditin.
Finally, fixed a bug in …
> Various quality of life improvements to the CLI

- core/engine/src/builtins/regexp/mod.rs
- core/engine/src/builtins/regexp/tests.rs
This Pull Request fixes #4399.
- Raise the limit to what the standard is requiring. It was too low and could be reach easily in real world cases before.
> fix(regexp): fix the capture group count assert to have the correct upper limit

- cli/src/logger.rs
- cli/src/main.rs
- core/engine/src/job.rs
- core/runtime/src/interval.rs
- core/runtime/src/interval/tests.rs
Prior to this PR, `run_jobs()` would block as long as there would be timeout jobs, even if they were in the future. A good example is using `setInterval` would run an infinite loop in `run_jobs()`.
This PR unblock `run_jobs()` when the jobs do not need to be run right now.
The new tests would infinite loop prior to this PR.
This PR also moved the code for the CLI prompt to a separate thread so the JavaScript code isn't waiting on prompts before executing tasks. This means that intervals/timeouts/promises/etc return immediately and will output their logs and move the prompt without interupting the user.
> Unblock Context::run_jobs when no timeouts need to be run

- cli/src/logger.rs
- cli/src/main.rs
This a simple fix when the CLI is not attached to a TTY. In those cases it would print an error `readline thread failed: ENOTTY: Not a typewriter`.
This fixes it by doing three things;
1. by default, if no printers has been set, use stdout normally. This makes sense as if any logging occurs before readline can be initialized, we still want to see it.
2. move back starting the readline loop after args files/expressions are handled.
3. if we cannot build a writer for some reason, don't stop the thread. `readline` still works, but printers won't, so we just show logs on stdout. This can happen if STDIN is a pipe.
> Fix the CLI when it is not attached to a TTY

- Cargo.lock
- Cargo.toml
- core/engine/Cargo.toml
- core/engine/src/builtins/array_buffer/mod.rs
- core/engine/src/builtins/array_buffer/shared.rs
- core/engine/src/builtins/array_buffer/tests.rs
- core/engine/src/builtins/atomics/tests.rs
- core/engine/src/builtins/temporal/plain_month_day/mod.rs
- core/engine/src/context/hooks.rs
- core/engine/src/context/mod.rs
- core/engine/src/error.rs
- core/engine/src/interop/into_js_arguments.rs
- core/engine/src/native_function/mod.rs
- core/engine/src/object/builtins/jsarraybuffer.rs
- core/engine/src/object/builtins/jsdataview.rs
- core/engine/src/object/builtins/jsdate.rs
- core/engine/src/object/builtins/jsmap.rs
- core/engine/src/object/builtins/jspromise.rs
- core/engine/src/object/builtins/jstypedarray.rs
- core/engine/src/object/datatypes.rs
- core/engine/src/value/conversions/convert.rs
- core/engine/src/value/conversions/nullable/mod.rs
- core/engine/src/value/mod.rs
- core/engine/src/vm/call_frame/mod.rs
- core/parser/src/source/mod.rs
- core/runtime/src/store/from.rs
- core/runtime/src/store/mod.rs
- core/runtime/src/store/to.rs
- core/string/src/builder.rs
- examples/src/bin/jsarraybuffer.rs
Our implementation of `ArrayBuffer` assumes all array allocations would be aligned to at least 64 bits. This works for amd64, but for other architectures it could be a wrong assumption to make, causing UB. This PR adds the `aligned-vec` crate to always allocate buffers at 64 bit boundaries, which solves the issue.
For an easy test, just run `cargo +nightly miri test array_buffer -p boa_engine`.
> Fix UB on unaligned ArrayBuffers

- .editorconfig
- .prettierignore
Before, the Makefile rule was overridden as rules are evaluated in order and merged in order. Also, if your editor is set to a different tab size/style, it wasn't correct for this project.
This will avoid changes like these in PRs: https://github.com/boa-dev/boa/pull/4436/files#diff-5f57f7d9e7e1a6c330e90b09112acd05a90d11afde996c58dd056f69e30fc4c1
> Editorconfig: specify indentation and dont overrule Makefile

- Makefile.toml
It makes it easier to run `test262` and JS benchmarks.
> Add a simple cargo-make to the project

- core/engine/src/builtins/map/mod.rs
- core/engine/src/builtins/map/tests.rs
- core/engine/src/builtins/mod.rs
- core/engine/src/builtins/set/mod.rs
- test262_config.toml
This Pull Request implements part of [the Upsert proposal](https://tc39.es/proposal-upsert/) for `Map`.
- Adds `Map.prototype.getOrInsert` method.
- Adds `Map.prototype.getOrInsertComputed` method.
- Implements canonicalization of keys (`-0` → `+0`) per the spec draft.
- Includes new tests for both methods to ensure correct behavior.
> Implement upsert methods for Map
