Cargo.toml, src/lib/js/console.rs, src/lib/lib.rs
This should have the same time formatting as before, let me know if you see anything that doesn't look quite right.
=> migrate from 'time' to 'chrono', fixes issue #3

Cargo.lock, Cargo.toml, benches/boa.rs, src/bin/bin.rs, src/lib/lib.rs, src/lib/syntax/lexer.rs, tests/js/test.js
=> better unicode escape support fixes #16

src/lib/exec.rs, src/lib/js/value.rs, src/lib/syntax/ast/expr.rs, src/lib/syntax/parser.rs
=> Change all 'r#try!' to '?'

.travis.yml, src/bin/bin.rs, src/lib/environment/declerative_environment_record.rs, src/lib/environment/environment_record_trait.rs, src/lib/environment/function_environment_record.rs, src/lib/environment/global_environment_record.rs, src/lib/environment/lexical_environment.rs, src/lib/environment/object_environment_record.rs, src/lib/exec.rs, src/lib/js/array.rs, src/lib/js/console.rs, src/lib/js/error.rs, src/lib/js/function.rs, src/lib/js/json.rs, src/lib/js/math.rs, src/lib/js/object.rs, src/lib/js/string.rs, src/lib/js/value.rs, src/lib/lib.rs, src/lib/syntax/ast/constant.rs, src/lib/syntax/ast/expr.rs, src/lib/syntax/ast/keyword.rs, src/lib/syntax/ast/pos.rs, src/lib/syntax/ast/punc.rs, src/lib/syntax/ast/token.rs, src/lib/syntax/lexer.rs, src/lib/syntax/parser.rs, tests/js/test.js
Hi!
I ran Clippy and I saw a lot of warnings and errors. I fixed many of them, but there are still some concerns, especially with casting and with some handling of `Value`, that being a Gc object poses some issues with clones.
This also fixes one bug, previously, this code would print "b5":
```javascript
let a = "b";
let c = 5;
c + a;
```
This has been fixed.
It also improves the performance by reducig the amount of heap used, and the many clones around.
=> Fixed a bunch of Clippy issues

src/lib/exec.rs, src/lib/syntax/ast/expr.rs, src/lib/syntax/parser.rs
This fixes #46. I just modified constant declarations so that it's impossible to have a constant without a value. I also uncommented the test that was failing.
=> Constants must have a value on declaration

.gitignore, LICENSE-MIT, LICENSE-UNLICENSE
I forgot to add the actual license files in #65. This just adds those files to the repo.
=> Added license files

src/lib/environment/declerative_environment_record.rs, src/lib/environment/function_environment_record.rs, src/lib/environment/global_environment_record.rs, src/lib/environment/object_environment_record.rs, src/lib/exec.rs, src/lib/js/array.rs, src/lib/js/console.rs, src/lib/js/error.rs, src/lib/js/function.rs, src/lib/js/json.rs, src/lib/js/math.rs, src/lib/js/object.rs, src/lib/js/string.rs, src/lib/js/value.rs, src/lib/lib.rs, src/lib/syntax/ast/constant.rs, src/lib/syntax/ast/expr.rs, src/lib/syntax/ast/op.rs, src/lib/syntax/lexer.rs
Hi!
Taking advantage of changes in #73, I reduced the overhead of NativeFunctions, reducing the amount of Clippy Warnings. I also added some lints for some potentially bad unwrap() use (and some others). If this gets merged, it should be merged first in the `addCtx` branch, and later to `master` with #73.
=> More changes with the context change

src/lib/exec.rs
For issue #19... Is something like this sufficient for solving the re-assigning of an existing binding?
=> Allow to re-assign value to an existing binding (issue #19)

.devcontainer/devcontainer.json, Dockerfile, src/lib/environment/global_environment_record.rs, src/lib/environment/object_environment_record.rs, src/lib/js/array.rs, src/lib/js/console.rs, src/lib/js/function.rs, src/lib/js/object.rs, src/lib/js/property.rs, src/lib/js/regexp.rs, src/lib/js/string.rs, src/lib/js/value.rs, src/lib/lib.rs
Merging for now as there's a lot of changes which will need follow up PRs
=> Adding object internal methods

src/lib/exec.rs, src/lib/syntax/ast/op.rs, src/lib/syntax/parser.rs
* Operators implemented: +=, -=, /=, *=, %=, &=, |=, ^=, <<=, >>=
* Add parser tests for new operators
=> Implement assign operators (#95)

benches/fib.rs, src/lib/exec.rs, src/lib/js/function.rs, tests/js/test.js
In Progress addition of arguments object
=> Addition of arguments object

index.html, index.js
I could remove certain commits if you don't like them.
=> Improve demo

src/lib/js/console.rs, src/lib/realm.rs
Updates the console object to be consistent with other global objects per #128.
=> Update console global

index.html, index.js, package.json, webpack.config.js, yarn.lock
=> Use Monaco Editor for demo.

src/lib/js/math.rs, src/lib/realm.rs
Updates the `Math` object to be consistent with other global objects per #128.
=> Updated Math Global

src/lib/js/object.rs, src/lib/realm.rs
Updates initialisation of `Object` global from #128.
=> Updated object global

src/lib/js/array.rs
=> Implement array.indexOf and .lastIndexOf

index.js
* Change editor theme from dark to light, to match the website theme
* Disable editor minimap
* Initialize the editor with "Hello, World!" program
=> demo: improve editor look, add initial code

index.js
Sorry, forgot to do this small thing in #169.
=> demo: evaluate initial code on page load

src/lib/js/array.rs
Added implementation for `findIndex` method.
Closes #166.
=> Added Array.prototype.findIndex

src/lib/builtins/array.rs
Hi, I noticed that some methods on arrays didn't have tests. So I implemented them.
=> array: implement tests for shift, unshift and reverse, pop and push

src/lib/exec.rs, src/lib/syntax/ast/expr.rs, src/lib/syntax/ast/op.rs, src/lib/syntax/parser.rs
=> Implement Tilde operator

src/lib/exec.rs
Hi,
I did not test my PR well enough yesterday, and this morning I've discovered a bug caused by it: when a function call is made inside a function body, a "return" in the nested call will also quit the outer function call.
I used the EnvironementType associated with a block to identify the end of a function call, it turns out that this approach doesn't work with nested functions call (I don't fully understand why, but in some cases the environment type associated with a function block could be "Declarative", not "Function").
To fix it, I've moved the `self.is_return = false` right after the function evaluation.
Sorry for the inconvenience
=> Fix early return (again)

.vscode/launch.json, src/lib/syntax/parser.rs, tests/js/test.js
Still bit of a WIP
Short function syntax in objects.
Tests need to be added.
=> short function syntax fixes #152

src/lib/exec.rs
This PR fixes https://github.com/jasonwilliams/boa/issues/201
Thanks for your time
=> Fix short-circuit evaluation

src/lib/builtins/array.rs
=> Initial implementation for Array.prototype.map

src/lib/syntax/parser.rs
Move argument parsing into separate function to be used as a utility
=> parse function arguments

src/lib/syntax/parser.rs
Fixing the stuff outlined in #207
=> Removed occurences of mk!

boa/src/syntax/parser.rs
=> fix(parser): handle trailing comma in object literals

CHANGELOG.md, Cargo.lock, boa/src/syntax/lexer.rs
I tried fixing more lexer panics. I think I got most of them. I think the errors could be better, but I think we should consider a new `LexerError` that includes file positions later on.
=> Fixed more Lexer Panics

boa/src/syntax/lexer/mod.rs, boa/src/syntax/lexer/tests.rs
Fixes errors regarding floating point parsing, as discussed in https://github.com/jasonwilliams/boa/pull/260.
=> Fix parsing of floats that start with a zero

boa/src/builtins/array/mod.rs, boa/src/builtins/array/tests.rs
I implemented the `Array.prototype.some` based on the [spec](https://tc39.es/ecma262/#sec-array.prototype.some). I used `Array.prototype.every` method as a reference point, since they are so similar.
=> Implemented the Array.prototype.some method.

boa/src/exec/tests.rs
This should prevent #208 from happening again. And I think that after this merges, we can close #208.
=> Added a test for #208

boa/src/lib.rs
Also added some documentation to boa lib.
=> Added logo and favicon to boa documentation

boa/src/builtins/array/mod.rs, boa/src/builtins/boolean/mod.rs, boa/src/builtins/boolean/tests.rs, boa/src/builtins/console/mod.rs, boa/src/builtins/error.rs, boa/src/builtins/function/mod.rs, boa/src/builtins/json/mod.rs, boa/src/builtins/math/mod.rs, boa/src/builtins/math/tests.rs, boa/src/builtins/mod.rs, boa/src/builtins/number/mod.rs, boa/src/builtins/number/tests.rs, boa/src/builtins/object/mod.rs, boa/src/builtins/regexp/mod.rs, boa/src/builtins/regexp/tests.rs, boa/src/builtins/string/mod.rs, boa/src/builtins/string/tests.rs, boa/src/builtins/symbol/mod.rs, boa/src/builtins/symbol/tests.rs, boa/src/builtins/value/conversions.rs, boa/src/builtins/value/mod.rs, boa/src/builtins/value/operations.rs, boa/src/exec/mod.rs, boa/src/exec/tests.rs, boa/src/realm.rs, boa/src/syntax/lexer/tests.rs
This PR is for cleaning the code-base mostly `builtins`, `exec` and `environment`.
=> Code cleanup

boa/src/exec/mod.rs, boa/src/exec/tests.rs
=> Implement unary increment and decrement

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This adds 3 templates for bugs, features and other stuff that people might want to report. It should make things easier to report and understand by the collaborators.
This will also stop people from creating empty issues, since writing some text is now mandatory.
=> Added issue/PR templates

README.md
It changes the following at [README.md](./README.md):
- Adds ponctuation at the end of lines.
- Improves text in some areas, such as in Debbuging and Benchmark sessions.
- Fixes or adds links when needed, such as in the licensing part at the end or at the Discord link.
=> Consistency at README.md

boa/src/builtins/number/tests.rs, boa/src/exec/mod.rs
This Pull Request fixes/closes #484 
- Re-wrote when **ValueData** is **Integer**
- Follows the same logic as the **Rational** case
- Added a test case in builtins/number/tests.rs to handle integer number primitive to number object
=> updated issue #484

boa/src/builtins/infinity/mod.rs, boa/src/builtins/infinity/tests.rs, boa/src/builtins/mod.rs
This Pull Request fixes/closes #480.
- adds the Infinity global property
=> add Infinity gloabal property (#480)

Cargo.lock, boa/Cargo.toml, boa_cli/Cargo.toml, boa_wasm/Cargo.toml, package.json, yarn.lock
This is just a minor dependency upgrade for the upcoming 0.9 release.
=> Upgraded dependencies before the 0.9 release

.github/dependabot.yml
This Pull Request fixes/closes #675 .
- `.github/dependabot.yml` to support version updates for `cargo`,`npm`, and `github-actions` on a daily rolling basis.
=> Adds `Dependabot` configuration file

boa/examples/classes.rs, boa/src/builtins/object/mod.rs, boa/src/class.rs, boa/src/exec/mod.rs, boa/src/lib.rs
This is a continuation of #627 
- Move class stuff from `object/mod.rs` to `class.rs`.
- Added class example and some documentation.
=> Class module

CHANGELOG.md, Cargo.lock, boa/Cargo.toml, boa_cli/Cargo.toml, boa_tester/Cargo.toml, boa_wasm/Cargo.toml
=> changelog for v0.10.0

CHANGELOG.md
Fix duplicate in the Changelog
=> Remove duplicate reference of issue 610

test262/index.html
This fixes the JS loading in the Test262 result representation.
=> Fixed JS loading for Test262 results

test262/results.js
This fixes some relative links on the Test262 results.
=> Fixing relative links to load Test262 results

test262/index.html
These are hopefully the latest fixes to make the test262 results show properly on GitHub Pages.
=> Fixed some extra links in the Test262 results

boa/src/exec/tests.rs, boa/src/syntax/ast/node/new/mod.rs
This Pull Request fixes/closes #801.
=> calling "new" on a primitive value throw a type error

.github/workflows/master.yml
This should fix the CI in the master branch. We were adding an extra folder to the cache.
=> Fix master CI

.github/workflows/master.yml
This should fix the master build, since it seems that we are caching what we shouldn't.
=> Update the master CI workflow

.github/workflows/test262.yml
This should fix PR builds for non-team-members.
=> Fixing PR builds

boa/src/property/mod.rs
- Corrects a word in a comment
=> Fix word in comment

Cargo.lock, boa/Cargo.toml, boa/src/object/gcobject.rs
=> Update to gc 0.4.0

boa/src/gc.rs
=> Fix a typo in gc.rs

boa/src/syntax/ast/node/declaration/mod.rs
Minor change to make Clippy happy
=> Clippy prefers From instead of Into

README.md
This has been bugging me for a while...
=> Update cli name in Readme

boa/src/context.rs
- Remove `Context::create_builtin_function` (this was not spec compliant and `FunctionBuilder` should be used instead).
- Make `Context::register_global_function` use `FunctionBuilder`.
- Added documentation to `Context::register_global_function`.
=> Fix `Context::register_global_function()`

boa/src/builtins/array/mod.rs
This will fix the broken builds.
=> Fix construct usage

.github/workflows/master.yml
This Pull Request fixes/closes #1325.
- Avoid documentation/benchmark master workflow if dependabot triggered
=> adds condition to avoid triggers from dependabot

boa/src/builtins/array/mod.rs, boa/src/builtins/map/mod.rs, boa/src/builtins/set/mod.rs
Implement missing species getters:
- `get Array [ @@species ]`
- `get Map [ @@species ]`
Adjust species getter docs/format:
- `get Set [ @@species ]`
=> Implement missing species getters

boa/src/lib.rs
This Pull Request fixes/closes #440.
=> Feature prelude module

boa/src/value/type.rs
Realized I made a typo while documenting `JsValue::get_type`.
=> Fix doc interlink on `JsValue::get_type`

boa/src/builtins/array/mod.rs, boa/src/builtins/array/tests.rs, boa/src/object/mod.rs
This Pull Request checks off a method from #36.
- Implements the `Array.prototype.sort` method
- Implements tests for `Array.prototype.sort`
=> Implement `Array.prototype.sort`

boa/src/builtins/bigint/mod.rs
- Make `BigInt.prototype.toString` spec compliant
=> Make `BigInt.prototype.toString` spec compliant

boa/src/builtins/json/mod.rs, boa/src/builtins/string/mod.rs, boa/src/object/gcobject.rs, boa/src/value/mod.rs
=> Refactor `JSON.stringify`

boa/src/builtins/number/mod.rs
=> Fix `Number.MIN_VALUE`

boa/src/string.rs
There are a lot of places in the spec where we concat more strings than two, so we can avoid unnecessary string allocations caused by `format!`.
=> Implement `JsString::concat_array()`

Cargo.lock, yarn.lock
This updates all the dependencies and the Test262 suite for the 0.13 release.
=> Updated all dependencies and Test262 test suite

boa/src/builtins/math/mod.rs
Fix Math tests #1559
This Pull Request closes #1599.
Things changed:
- Instead of using f64::min, we use the sign of the difference of the numbers to compare. There is certainly a more efficient way to do this.
- imul's length was changed to the right one
- pow now returns NaN when the exponent is infinite and the base is 1 or -1
- round now ceils for negative numbers with a fractionnal part of 0.5 instead of flooring
It's my first pull request on a repo, I'd love so me feedback.
Sorry for the first pull request I didn't want my real name or my address email to be available everywhere.
=> Fix non-conformant Math methods

Cargo.lock, test_ignore.txt, yarn.lock
This PR updates the test suite with the new "Temporal" tests, along with the new regeneration of some tests. It also brings some smaller tests.
I also took the opportunity to update the dependencies.
=> Updated test suite and dependencies

.github/workflows/release.yml
Fixing actions to correctly deploy the playground
=> Deploy playground to custom destination dir

test262/index.html, test262/results.js
This PR refactors the conformance page to hopefully be a bit more maintainable. The current js code is a bit confusing and hard to read IMO (nested functions, no async/await, jquery appends all over the place, ...). I tried to make it a bit more readable by dropping jquery in favor of some bigger template strings and native DOM apis. I also moved some html to the index.html file. Additionally I made some design adjustments to the page to make it look a bit more modern.
It's far from perfect, but let me know what you think.
=> Refactor conformance page

test262/results.js
Fix panics count in test suites:
=> Fix panics count display

dev/bench/index.html
This removes old benchmarks (>1 year old), and updates a couple of dependencies for benchmark display. I also removed the "points" in the graphs, to make it easier to see what's going on.
=> Cleaned up benchmarks, updated dependencies

test262/index.html, test262/results.js
Also adjusted the hide switch to hide the passed tests, since the logic is mostly the same as ES edition filtering.
Some screenshots of the final result:
On a tag without versioning (disables the selector):
=> Add ECMAScript edition selector

ABOUT.md
Adding a period to the end of the initial sentence in `ABOUT.md` 😄.
=> Add period to ABOUT.md

.vscode/launch.json, .vscode/tasks.json, boa_cli/src/main.rs, boa_engine/src/builtins/async_generator/mod.rs, boa_engine/src/bytecompiler/declarations.rs, boa_engine/src/bytecompiler/expression/mod.rs, boa_engine/src/bytecompiler/mod.rs, boa_engine/src/bytecompiler/statement/mod.rs, boa_engine/src/bytecompiler/utils.rs, boa_engine/src/job.rs, boa_engine/src/vm/code_block.rs, boa_engine/src/vm/completion_record.rs, boa_engine/src/vm/flowgraph/graph.rs, boa_engine/src/vm/flowgraph/mod.rs, boa_engine/src/vm/opcode/generator/mod.rs, boa_engine/src/vm/opcode/generator/yield_stm.rs, boa_engine/src/vm/opcode/iteration/iterator.rs, boa_engine/src/vm/opcode/mod.rs
This Pull Request fixes the last two failing tests from the async-generator suite.
Marking as draft since there's an execution bug that will be solved by this.
=> Fix remaining async generator tests

.github/workflows/webassembly.yml, .gitignore, .prettierignore, boa_wasm/e2e_test/boa_demo.spec.ts, boa_wasm/e2e_test/playwright.config.ts, boa_wasm/e2e_test/server.mjs, index.html, package-lock.json, package.json, webpack.config.js
This Pull Request add a e2e test for wasm32 target.
=> test: add wasm32 target e2e test

README.md
Adds a link to the main logo so you can click into the website
=> add link to the main logo

.github/workflows/release.yml
This should fix the 2 errors we got while doing the 0.17 release.
=> Fixing the release build errors

.github/workflows/release.yml
This should hopefully fix the release.
=> Removing the commented-out job

.github/workflows/release.yml
One more attempt to fix the workflow.
=> Fix syntax

.github/dependabot.yml, fuzz/Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/common.rs, fuzz/fuzz_targets/parser-idempotency.rs
This updates the fuzzer dependencies, adds them to Dependabot, and I also enhanced a couple of import syntaxes.
=> Updated Fuzzer dependencies and added them to Dependabot

Cargo.lock, Cargo.toml
=> Bump time from 0.3.31 to 0.3.33

Cargo.lock, core/engine/Cargo.toml, core/engine/src/builtins/temporal/calendar/mod.rs
This Pull Request bumps `temporal_rs` and reverts the commented out code. Also, runs `cargo update` to bump deps
=> Update `temporal_rs` and cargo update

.github/workflows/rust.yml
=> Fix CI for nextest step

Cargo.lock, Cargo.toml, core/engine/src/builtins/temporal/duration/mod.rs, core/engine/src/builtins/temporal/instant/mod.rs, core/engine/src/builtins/temporal/options.rs, core/engine/src/builtins/temporal/plain_date/mod.rs, core/engine/src/builtins/temporal/plain_date_time/mod.rs
This Pull Request is part of the continued work for Temporal.
- Makes updates for the new rounding functionality
- Implements some additional methods from `temporal_rs`
- Some general cleanup
=> Update Temporal rounding and implement additional methods

core/engine/src/bytecompiler/declaration/declaration_pattern.rs
- Fix evaluation order in destructive property assignments
=> Fix evaluation order in destructive property assignments

CHANGELOG.md
Changelog for v0.19
[Rendered](https://github.com/boa-dev/boa/blob/62cf6029857aa12d7e432e081a8762df0b4f929e/CHANGELOG.md)
=> changelog for v0.19

core/engine/src/try_into_js_result_impls.rs
This way JsFunction made with into_js_function can return vectors.
=> Add TryIntoJsResult for vectors

core/engine/src/lib.rs
This Pull Request fixes/closes #4006
=> docs: Fix link to examples

.github/workflows/nightly_build.yml
Hopefully this fixes the nightly Github Action.
Looks like the indentations were off a little bit.
=> Patch the indentation in nightly_build.yml

.github/workflows/nightly_build.yml
Another change to nightly build to address the current errors. I did try to manually run these commands locally, and they did appear to work.
=> Update night build's rename binary step

Cargo.lock, Cargo.toml, core/engine/Cargo.toml, core/engine/src/builtins/number/globals.rs, core/parser/Cargo.toml, core/parser/src/lexer/number.rs, core/string/Cargo.toml, core/string/src/lib.rs
Fixes one of our security alerts.
=> Migrate to fast-float2

.github/workflows/rust.yml, cli/src/main.rs, core/ast/src/expression/operator/assign/op.rs, core/engine/src/builtins/iterable/mod.rs, core/engine/src/builtins/temporal/mod.rs, core/engine/src/object/mod.rs, core/engine/src/property/mod.rs, core/engine/tests/macros.rs, core/interop/src/lib.rs, core/interop/tests/embedded.rs, core/macros/tests/tests.rs, core/parser/src/lexer/comment.rs, core/profiler/src/lib.rs, core/runtime/src/url.rs, ffi/wasm/tests/web.rs, tests/macros/tests/derive.rs, tests/macros/tests/optional.rs
=> Fix rust 1.83.0 lints

CHANGELOG.md, Cargo.lock, Cargo.toml
bump versions & fix changelog date
=> update changelog and bump versions for release

core/ast/src/keyword/mod.rs, core/ast/src/keyword/tests.rs, core/parser/src/lexer/identifier.rs, core/parser/src/parser/statement/declaration/export.rs, core/parser/src/parser/statement/declaration/tests.rs, core/parser/src/parser/tests/mod.rs
=> Allow bool and null literals in export aliases

core/ast/src/function/class.rs, core/ast/src/operations.rs, core/ast/src/scope_analyzer.rs, core/engine/src/bytecompiler/class.rs, core/engine/src/tests/class.rs, core/parser/src/parser/statement/declaration/hoistable/class_decl/mod.rs
=> Allow referencing `super` within initializer of static private property

.github/workflows/nightly_build.yml, .github/workflows/release.yml, .github/workflows/rust.yml
Add boa-macos-arm64 release file
This Pull Request fixes/closes  https://github.com/boa-dev/boa/issues/4159
=> add macos arm64

Cargo.lock, Cargo.toml, core/engine/src/builtins/temporal/plain_date/mod.rs, core/engine/src/builtins/temporal/plain_date_time/mod.rs, core/engine/src/builtins/temporal/plain_year_month/mod.rs, core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request related to ongoing work for #1804.
- Adds a missing `overflow` check in `to_zoneddatetime`
- Changes order of operations for `PlainYearMonth` method
- Bumps `temporal_rs` to include more fixes
=> Fix some engine specific bugs and bump version

.github/workflows/nightly_build.yml, .github/workflows/release.yml
=> Unify release workflows

.github/workflows/webassembly.yml, cli/src/main.rs, core/ast/src/module_item_list/mod.rs, core/ast/src/operations.rs, core/ast/src/scope_analyzer.rs, core/ast/src/statement/labelled.rs, core/engine/src/builtins/temporal/plain_date/mod.rs, core/engine/src/builtins/temporal/plain_date_time/mod.rs, core/engine/src/builtins/typed_array/builtin.rs, core/engine/src/job.rs, core/engine/src/module/mod.rs, core/engine/src/optimizer/mod.rs, core/engine/src/optimizer/walker.rs, core/engine/src/vm/runtime_limits.rs, core/parser/src/lexer/error.rs, core/parser/src/source/utf8.rs, core/string/src/builder.rs, ffi/wasm/Cargo.toml
=> Fix Rust 1.87.0 lints

README.md
This Pull Request fixes/closes #4253.
- README.md: Change 0.19.0 to 0.20.0
=> Update README.md to new version.

Cargo.lock, Cargo.toml, core/engine/src/builtins/temporal/plain_date/mod.rs, core/engine/src/builtins/temporal/plain_date_time/mod.rs, core/engine/src/builtins/temporal/plain_month_day/mod.rs, core/engine/src/builtins/temporal/plain_year_month/mod.rs
This Pull Request is related to ongoing work for #1804 
- Bumps temporal_rs to the newest version
- Some small changes related to order of operations for observable calls
=> Bump temporal_rs and fix some order of operation issues

Cargo.lock, Cargo.toml, core/engine/src/builtins/temporal/plain_date_time/mod.rs, core/engine/src/builtins/temporal/plain_month_day/mod.rs, core/engine/src/builtins/temporal/zoneddatetime/mod.rs
This Pull Request is related to the ongoing work for #1804
This bumps `temporal_rs` to the most recent version.
=> Bump temporal_rs to v0.0.9

.cargo/config.toml, core/engine/src/builtins/intl/locale/mod.rs, core/engine/src/builtins/intl/locale/options.rs, core/engine/src/builtins/intl/locale/utils.rs, core/engine/src/builtins/intl/number_format/options.rs, core/engine/src/builtins/intl/plural_rules/mod.rs, test262_config.toml
A couple of changes were introduced in ECMA-402's latest spec. This PR implements the couple of changes that only modify already implemented builtins.
=> Implement small changes from Intl's 2026 spec

Cargo.lock, core/engine/src/bytecompiler/mod.rs, core/engine/src/object/jsobject.rs, core/engine/src/realm.rs, core/parser/src/lexer/tests.rs, core/parser/src/parser/tests/mod.rs
=> Fix lints for rustc 1.88

cli/src/main.rs
Prevent evaluation of code when `--dump-ast` flag is provided.
Issue being that we are running the code after dumping the AST, so we are effectively running the code snippet twice (this does not happen for file execution AST dump). Which causes a duplicate lexical binding error, that causes the `collect_bindings` to fail.
=> Prevent evalutation of code with `--dump-ast` flag

Cargo.lock, Cargo.toml, core/engine/src/builtins/temporal/now.rs, core/engine/src/builtins/temporal/plain_year_month/mod.rs, core/engine/src/builtins/temporal/zoneddatetime/mod.rs
It bumps temporal_rs to the most recent version.
It also looks like there may be some formatting changes too.
=> Bump temporal_rs version to v0.0.11

core/engine/src/builtins/temporal/plain_month_day/mod.rs
This updates `to_month_day` to better align with the specification and fixes some bugs that was causing some broken tests.
=> Fix broken PlainMonthDay.from tests

core/engine/src/builtins/uri/mod.rs
This Pull Request fixes/closes #4404.
- Tightens percent-decoding boundary check in `core/engine/src/builtins/uri/mod.rs::decode` to prevent out-of-bounds access (uses `>=` per spec).
- Adds unit test `decode_uri_reports_uri_error_on_incomplete_sequence` to assert `decodeURI('%E7%9A%8')` raises `JsNativeErrorKind::Uri`.
=> Fix: prevent OOB panic in decodeURI by tightening percent-decoding bounds; add test for incomplete escape %E7%9A%8 (#4404)
